### ISSUE TITLE
Zeitverzögerung nur bei öffnen?

### ISSUE THREAD

**Issue by Pittini** [rg-engineering/ioBroker.heatingcontrol#101]
Hi,
ich weis jetzt nicht ob Bug oder FeatureRequest (weil aktuell evtl. so gewollt). Betrifft die Zeitverzögerung. Diese funktioniert einwandfrei beim öffnen des Fensters, schliesse ich innerhalb der Verzögerungszeit wird keine Regelung ausgeführt. Soweit ok.
Leider funktioniert das ganze andersrum nicht, d.h. sobald das Fenster geschlossen wird, wird sofort von der Absenktemperatur auf die Solltemperatur gestellt. Das ist deshalb unglücklich weil bei einfachen auf/zu Sensoren, beim Wechsel von auf zu gekippt (oder gekippt zu auf) ja immer ein schliessen dazwischen kommt.
Nehmen wir nun an, das Fenster war gekippt und wird nun ganz geöffnet, so wird beim Schliessvorgang sofort die Absenktemp auf Solltemp gestellt, und kurze Zeit später (weil da ja quasi wieder ein Wechsel von zu zu auf stattfand) wird das Thermostat erneut auf Absenktemp geregelt. Das sind 2 Regelvorgänge für die Katz.

**Comment by rg-engineering** [comment]
Der ursprüngliche Feature-Wunsch war, dass beim kurzzeitigen Öffnen des Fensters nicht abgeregelt werden soll. Genau so habe ich es implementiert.
Das hier beschriebene Szenario wurde bisher nicht bedacht und damit nicht berücksichtigt.
Ich nehme es als Feature-Request mit auf...

**Comment by Pittini** [comment]
> Ich nehme es als Feature-Request mit auf...

Super, das kann ja sogar unabhängig von der normalen Verzögerung fest eingebaut sein und kürzer, so 2-4 Sekunden. Mechanisch Bauart bedingt gehen ja alle Fenster immer erst übers schliessen beim Wechsel gekippt/offen und vice versa.

**Comment by rg-engineering** [comment]
ist in 0.5.0 eingebaut
