### ISSUE TITLE
Neuer DP "Override Heizperiode"

### ISSUE THREAD

**Issue by guergen1** [rg-engineering/ioBroker.heatingcontrol#106]
Könnte man noch einen sg. "override Heizperiode"-DP erstellen?
Hintergrund ist folgender: meine HP endete am 15.4. lt Adapter, jetzt war es am folgenden Tag extrem kalt, sodass ich das Datum ändern musste. Ich könnte mir vorstellen, dass es den Datenpunkt geben könnte, den man auch ansteuern kann, damit man von unterwegs "mal eben" dem Heizungsmonteur die Heizung einschalten kann, damit man die Wärme beim Messen der Abgaswerte weg bekommt.

**Comment by rg-engineering** [comment]
und warum nicht einfach Heizperiode auf true setzen?

**Comment by guergen1** [comment]
Hmmmh.... Ich sollte besser gucken bevor ich was schreibe...

Läuft....
