### ISSUE TITLE
No function (enums) selectable

### ISSUE THREAD

**Issue by CKMartens** [rg-engineering/ioBroker.heatingcontrol#11]
I have installed 0.2.0 today. I want to setup the instance, but in this version is no function (enum) selectable. In the last version i could.

![grafik](https://user-images.githubusercontent.com/19702758/64490150-7991d200-d25a-11e9-8d28-24c28074981a.png)
![grafik](https://user-images.githubusercontent.com/19702758/64490153-7e568600-d25a-11e9-8bb6-af1ce5d1d7b0.png)

**Comment by rg-engineering** [comment]
is the adapter running when you open the admin page?

**Comment by CKMartens** [comment]
Of courese, no

Is this the issue?
