### ISSUE TITLE
Einzelraumabschaltung

### ISSUE THREAD

**Issue by Starcon79** [rg-engineering/ioBroker.heatingcontrol#110]
Ich hätte den Wunsch das man in der Heizperiode einzelne Räume abschalten kann.
Beim Heizungsscript von Looxer hatte ich dies über die Profile gelöst. Dies ist aber beim Adapter nicht mehr möglich da die Profile alle Räume beeinflussen. Wäre super wenn du da noch was einbauen könntest.
Hier der Link zum Forum: https://forum.iobroker.net/topic/22579/test-adapter-heatingcontrol-v0-5-x/1158?page=58

**Comment by rg-engineering** [comment]
@Starcon79 kannst du den use case nochmal erklären? "abschalten" geht ja nur indirekt, indem man eine niedrige Zieltemperatur setzt. Idee könnte sein, dass man eine Zieltemperatur pro Raum konfigurieren kann, die dann per vis für den Raum permanent gesetzt wird...

**Comment by Starcon79** [comment]
@rg-engineering der use case ist das ich in der Übergangszeit manche Räume nicht heize. Deine Idee hört sich gut an das würde mir schon helfen. Hatte ich beim Script genau so gelöst das ich die Thermostate für die Räume welche ich nicht heize auf 5 grad gestellt habe.

**Comment by rg-engineering** [comment]
oder alternativ über Profile abdecken? Du könntest ja ein Profil "Sommer", "Frühling/Herbst" und "Winter" anlegen. Das geht jetzt schon....

**Comment by Starcon79** [comment]
Ja hatte ich auch erst versucht aber ist ziemlich umständlich da ich die Räume die noch geheizt werden um 1-2 Grad absenke und wenn es dann doch nochmal kalt wird ich einzelne Räume wieder zuschalten will werden es noch mehr Profile was dann doch den WAF senkt. Also es wäre echt toll wenn du die oben genannte Idee umsetzen könntest.

**Comment by rg-engineering** [comment]
was wäre, wenn du im admin die Räume abschaltest?
![grafik](https://user-images.githubusercontent.com/8238668/92408867-0c4fa000-f13f-11ea-8c07-7658d4da027b.png)

**Comment by Starcon79** [comment]
Hallo,
ja die Option habe ich gesehen. Für mich wäre das kein Problem. Allerdings kann es auch mal sein das ich nicht zu Hause bin(z.B. Krankenhausaufenthalt) dann wäre das zu umständlich für meine Frau (WAF). Wäre wirklich toll wenn du dafür einen Datenpunkt zu Verfügung stellen könntest.

**Comment by texiuozelotl** [comment]
Hallo,
mir fehlt so eine Option auch, entweder einzelne Räume per Datenpunkt "abschaltbar" machen oder besser: Die Profilauswahl nicht global, sondern per Raum selektierbar machen, oder noch besser: Beides :-) 

Mein Usecase betrifft nicht nur die Übergangszeiten sondern auch den Anwesenheits-Status: 
- Wenn keine Gäste da sind möchte ich das Gästezimmer erst gar nicht beheizen  
- Wenn ich nicht im Modus Telearbeit bin möchte ich das Arbeitszimmer nicht beheizen
- Wenn keine Party angesagt ist soll der Partykeller nicht beheizt werden

Die Möglichkeit die das Heizungsscript mit der Einstellbarkeit von Profilen pro Raum gab fand ich da sehr elegant und flexibel, die Option den entsprechenden Raum in den Admin Einstellungen zu deaktivieren finde ich weniger flexibel. Aber wenn's keine andere Möglichkiet gibt wäre das zumindest ein Workaround. Allerdigs weiß ich nicht wie ich via VIS oder JS-Script die Admin-Option steuern kann, velleicht kann mir da jemand auf die Sprünge helfen?

PS: Steige gerade vom Heizungsscript - mit dem ich etliche Probleme hatte - um und meine bisherigen Erfahrungen mit dem Adapter sind sehr positiv. Also vielen Dank dafür :-)

**Comment by MMeinhardt1** [comment]
@rg-engineering ist sowas in der Art für V2 vorgesehen?

**Comment by texiuozelotl** [comment]
Ich muss gestehen, ich bin wieder zurück auf das Heizungsscript migriert. Dort habe ich 3 Profile pro Raum angelegt (Winter, Übergangszeit und Standby), die sich individuell und übersichtlich handeln sowie gut automatisieren lassen.   

Das Konzept des Adapters die Profile ausschießlich global fürs ganze Haus und nicht pro Raum setzen zu können ist meiner Meinung nach grundsätzlich falsch gedacht. 

Wenn man ein Profil-Duplikat sämtlicher Räume des Hauses anlegen muss, nur um einen einzelnen Raum individuell anzupassen, dann ist das manuell für ein Einfamilienhaus mit einem dutzend beheizter Räume nicht mehr handelbar. Und selbst wenn man sich die Mühe machen würde: Im Ergebnis erhält man eine völlig überdimensionierte Redundanz von aberhunderten Datenpunkten derer man nicht mehr Herr wird. 

Rechenbeispiel: 12 Räume bei nur 6 Profilen zu je 15 Datenpunkte ergeben 1.080 Datenpunkte. 
Ich sehe da keine Chance (geschweigedenn einen Komfortgewinn) bei einem Änderungsbedarf der Soll-Temperaturen über alle Profile hinweg irgendwelche Datenpunkte synchron zu halten.

**Comment by rg-engineering** [comment]
available in 2.2; needs to be tested

**Comment by rg-engineering** [comment]
can we close that issue?

**Comment by Starcon79** [comment]
Tausend Dank für die Umsetzung. Issue kann geschlossen werden.
