### ISSUE TITLE
Checkbox "Urlaub anwesend wie Feiertag"

### ISSUE THREAD

**Issue by picnicorama** [rg-engineering/ioBroker.heatingcontrol#111]
Hallo und danke für den feien Adapter. In diesem Status wird er jetzt bei mir das Skript von looxon ersetzen. Was mir zu meinem Glück noch fehlt ist die Funktion Urlaub anwesend wie Feiertag/Sonntag und eine Checkbox mit der man diese Funktion aktivieren oder deaktivieren kann. Diese Funktion war/ist auch im Heizungssteuerungsskript, hat gut funktioniert und eine Menge Zeit erspart. Gerade wieder in den letzten Wochen, wenn dann an einem Tag doch wieder alle im Haus sind oder wenn man spontan mal frei hat/macht, dann muss man nicht Raum für Raum die Profile umstellen. Mit einem Klick hat die Heizung Sonntag und allen ist warm :-)

**Comment by rg-engineering** [comment]
reicht dir "heatingcontrol.0.HolidayPresent" dafür nicht?

**Comment by picnicorama** [comment]
Möglicherweise habe ich da etwas nicht geblickt, aber welche Werte werden denn dann für heatingcontrol.0.HolidayPresent geutzt?

**Comment by rg-engineering** [comment]
es werden die Profilwerte vom Wochenende verwendet (entweder Sa/So bei Profiltyp Mo-Fr/Sa-So oder So bei Profiltyp "jeden Tage separat"

**Comment by picnicorama** [comment]
Ok ... die Sache mit dem Lesen, verstehen und begreifen ... Danke ;-)
