### ISSUE TITLE
 Fensterübersicht wird als NaN angezeigt.

### ISSUE THREAD

**Issue by rg-engineering** [rg-engineering/ioBroker.heatingcontrol#112]
nach jedem Adapterneustart bzw. Iobroker Neustart wird im Vis, bzw. im zugrundeliegenden Datenpunkt bei der Fensterübersicht NaN angezeigt. Einmaliges Fensteröffnen behebt das Problem, aber nach jedem Start durchs ganze Haus gehen und jeden Fensterstatus einmal ändern zu müssen is ja auch keine Dauerlösung. Tritt bei 0.5.3 und 0.5.4 auf. Evtl. auch schon früher und mir isses nicht aufgefallen.

siehe https://forum.iobroker.net/topic/22579/test-adapter-heatingcontrol-v0-5-x/1166

**Comment by ChristianGrieger** [comment]
Ja, den Fehler habe ich auch gefunden. Ich freue mich über ein Fix :)

**Comment by Pittini** [comment]
Fix fixt das Urproblem, aber dafür gibts nen neuen Bug, jetzt werden bereits geöffnete Fenster bei Adapterstart nicht mehr als geöffnet gezeigt.

**Comment by Pittini** [comment]
Schaut gut aus jetzt, kannst dicht machen hier.
