### ISSUE TITLE
Override registered without temperature change

### ISSUE THREAD

**Issue by JoschaMiddendorf** [rg-engineering/ioBroker.heatingcontrol#120]
Der Adapter registriert Aktualisierungen meiner HomeMatic Thermostate als override, obwohl die aktualisierten Temperaturen nicht von denen, die durch Heatingcontroll gesetzt wurden, abweichen.

**Comment by rg-engineering** [comment]
kann es sein, dass die Thermostate regelmässig den aktuellen Wert senden? Bisher bin ich davon ausgegangen, dass nur veränderte Werte übertragen werden...

**Comment by JoschaMiddendorf** [comment]
Ich habe grade einmal die Events mitgelesen. Die Thermostate senden regelmäßig den aktuellen Wert, auch wenn sich dieser nicht ändert.
<img width="1575" alt="Bildschirmfoto 2020-09-05 um 21 33 33" src="https://user-images.githubusercontent.com/19818109/92312413-90c7e480-efc0-11ea-81d3-34aa4f59cfe9.png">

**Comment by rg-engineering** [comment]
okay, dann baue ich dafür noch einen check ein...

**Comment by rg-engineering** [comment]
mit 0.6.0 erledigt
