### ISSUE TITLE
Error (9027) HandleThermostat: different types string vs number with old FHT via FHEM

### ISSUE THREAD

**Issue by Wildbill-Z** [rg-engineering/ioBroker.heatingcontrol#122]
Hi,

I'm using some newer Homematic stuff with Pivccu which is working without problem. I also use some old FHT-thermostats which are implemented via a NanoCUL in FHEM and the via the FHEM-adapter to iobroker. Every time, your adapter changes a temperature from one of those old stuff, I get an warning in log:
`9027) HandleThermostat: different types string vs number`
All is working fine, but the log gets flooded. Here is one of the raw datapoints, which is set from your adapter:
`{
  "from": "system.adapter.fhem.0",
  "user": "system.user.admin",
  "ts": 1574602635513,
  "common": {
    "name": "FHT_Esszimmer desired-temp",
    "type": "number",
    "role": "level.temperature",
    "unit": "°C",
    "min": 5,
    "max": 30,
    "read": true,
    "write": true,
    "smartName": {
      "de": "FHT_Esszimmer",
      "smartType": "THERMOSTAT"
    }
  },
  "native": {
    "Name": "FHT_0703",
    "Attribute": "desired-temp",
    "possibleSets": true,
    "level_temperature": true,
    "Readings": true
  },
  "acl": {
    "object": 1638,
    "owner": "system.user.major",
    "ownerGroup": "system.group.user",
    "state": 1638
  },
  "_id": "fhem.0.FHT_0703.desired-temp",
  "type": "state"
}`
I don't see any reason, why the adapter or iobroker would think, that thera is a string instead of number?!

Greetings, Jürgen

**Comment by rg-engineering** [comment]
I do some verification stuff here. In the certain case I check whether the target temperature is really a number. That means it has nothing to do with hardware or different thermostats. The reason for the message is data type of target in the profile. Please check data types there. If you enable debug log you should see more... next line should show something like
`
set thermostat ABC to 20; current is 22
`
or
`
thermostat ABC nothing to do, already 22
`

**Comment by Wildbill-Z** [comment]
Hi,

I see some of these messages für every old FHT, but I wonder why the adapter doesn't recognize same temperatures:
`

heatingcontrol.0 | 2020-09-04 06:30:00.185 | info | (31652) set thermostat fhem.0.FHT_0702.desired-temp to 22.5; current is 22.5
-- | -- | -- | --
heatingcontrol.0 | 2020-09-04 06:30:00.182 | warn | (31652) HandleThermostat: different types string vs number

`
desired-temp was on 22.5 for hours and the adapter just sends 22.5 to FHEM which sends it to the FHT (I see in the log and I had some problems with duty cycle when installing the adapter for first time).

I just wonder, why it thinks it would be a string and needs to be converted to a number as the datapoints are type number as one can see above in first post.
My Homematic-thermostats don't behave like this. Here the adapter recognizes, if the temperature is the same and shows like this:
` thermostat ABC nothing to do, already 22`

Seems, I have to throw away the old FHT-stuff an buy new ones... :-)

Greetings

**Comment by rg-engineering** [comment]
> Seems, I have to throw away the old FHT-stuff an buy new ones... :-)
as I said: it is not related to your hardware. Here we write data from the adapter to the thermostat and the test is done before the data goes to the thermostat
The question is, where do the values ​​for the profile data come from? Do you use a script or visualisation?

**Comment by Wildbill-Z** [comment]
@rg-engineering I just use the script which is implemented in the adapter an the visualisation from Pittini. No other script, no manual setting or soemthing else. Thats why I wonder if there is something wrong with the datapoints of the FHT within the objects in iobroker, which come from the FHEM-Adapter. For datapoints of my Homematic or Homematic- IP-stuff which I also included in your adapter (and the vis of Pittini) there is no such message. 
Nevertheless, it seems to be just a cosmetic problem as all is working fine. I set lazy mode within FHEM, so if I get such a string/number-message an your adapter sends a new temperature to a FHT, FHEM will just ignore it and not send out any signal, as it recognizes, that nothing has changed.
And, as I said, I will get newer hardware as my FHT are about 10-15 years old an won't get any better. :-)


Greetings, Jürgen

**Comment by Wildbill-Z** [comment]
I'll close this issue as I bought new Homematic stuff to swap these old FHT-thermostats as I allways had little problems with them over the long time I had. If you change anything to solve this issue, I will no longer be able to test it.

Greetings, Jürgen
