### ISSUE TITLE
Falsche Meldungen im Log

### ISSUE THREAD

**Issue by Siggi0904** [rg-engineering/ioBroker.heatingcontrol#123]
Ich bekomme mit der aktuellen Stable folgende Meldungen ca, alle 30 Minuten ins Log obwohl ich kein Fenster öffne oder sonst irgendwas ändere. Die Meldungen kommen für alle Räume immer abwechselnd oder manchmal auch mehrere Räume gleichzeitig.

heatingcontrol.0 | 2020-09-03 18:47:34.023 | info | (5923) 7 cron jobs created
heatingcontrol.0 | 2020-09-03 18:47:23.882 | info | (5923) sensor close delay 10000 for Wohnzimmer

Ist das so gewollt,oder werden die Logs falsch ausgelöst?

**Comment by rg-engineering** [comment]
schalte doch mal debug log ein, dann müssten wir die Ursache sehen.

**Comment by Siggi0904** [comment]
Wo mache ich denn das? Bin ein Anfänger, was IOBroker angeht.
Danke.

**Comment by rg-engineering** [comment]
![grafik](https://user-images.githubusercontent.com/8238668/92147714-cb444c80-ee1b-11ea-98b1-d85b9d28e670.png)

**Comment by Siggi0904** [comment]
Gefunden, großen Dank.
Bisher kam seltsamer weise der Log-Eintrag noch nicht.

Muss ich das log offen lassen? Denn ich bekommme oft den Eintrag:
heatingcontrol.0 | 2020-09-03 19:56:46.327 | debug | (24220) system.adapter.admin.0: logging true
heatingcontrol.0 | 2020-09-03 19:56:20.865 | debug | (24220) system.adapter.admin.0: logging false

Danke.

**Comment by Siggi0904** [comment]
Die Meldungen sind nun aufgetaucht.
Hier das log, ich hab versucht das ein wenig zu anonymisieren.

Wirst du daraus schlau?
[heatingcontrol.txt](https://github.com/rg-engineering/ioBroker.heatingcontrol/files/5170617/heatingcontrol.txt)

**Comment by rg-engineering** [comment]
du hast eingestellt, dass der Adapter auf Änderungen der Soll-Temperatur vom Thermostat reagieren soll. Der Thermostat schickt regelmässig seine Soll-Temperatur (obwohl sich nichts geändert hat (steht immer auf 4,5) und auch der Fenstersensor hm-rpc.0.<id-hm>.1.STATE state schickt regelmässig den aktuellen Zustand (Fenster zu). Das führt dazu, dass der Adapter ständig prüft und zu dem Ergebnis kommt -> nichts zu tun...  Letztendlich schadet das nichts, aber der Adapter erhöht unnötigerweise die Systemlast... Mal schauen, ob man das verhindern kann...

**Comment by Siggi0904** [comment]
"Änderungen der Soll-Temperatur vom Thermostat" meinst du die Einstellung "Verwendung von Änderungen vom Thermostat
"? Ja, die steht auf Overrite. Da fehlt auch noch die Übersetzung.

Danke im Voraus, falls der Bug behoben werden kann.

**Comment by rg-engineering** [comment]
mit 0.6.0 erledigt
