### ISSUE TITLE
Pittini Vis

### ISSUE THREAD

**Issue by duczz** [rg-engineering/ioBroker.heatingcontrol#124]
Wäre es möglich im Objekt "heatingcontrol.0.vis.WindowStatesHtmlTable" die Bild Source separat zu deklarieren?

**Comment by rg-engineering** [comment]
das heisst, du möchtest ein eigenes Image dafür verwenden und den Pfad zum Image einstellen?

**Comment by duczz** [comment]
jup

**Comment by rg-engineering** [comment]
erste Version mit 0.6.0 verfügbar...
