### ISSUE TITLE
Nach Aktivierung der "HeatingPeriodActive" wird die falsche Periode genommen. Bei mir springt er am Montag immer wieder auf die Sa/So Einstellung

### ISSUE THREAD

**Issue by rg-engineering** [rg-engineering/ioBroker.heatingcontrol#13]
siehe Forum
https://forum.iobroker.net/topic/22579/adapter-heatingcontrol/76
und genauer
https://forum.iobroker.net/topic/22579/adapter-heatingcontrol/79

**Comment by Michael-Sauer** [comment]
siehe Forum.

**Comment by rg-engineering** [comment]
mit V0.2.3 erledigt
es wird die Reihenfolge der Uhrzeiten geprüft...
