### ISSUE TITLE
In Version 0.6.0 Fehler bei Cron-Jobs

### ISSUE THREAD

**Issue by stsch83** [rg-engineering/ioBroker.heatingcontrol#131]
Version 0.6.0

die Cron-Jobs verdoppeln sich auf einmal ohne Grund. Sie verdoppeln sich immer weiter und weiter bis die Fehlermeldung kommt, (10060) more then 500 cron jobs existing for this adapter, this might be a configuration error! (530).

Normalerweise habe ich 53 Jobs. Ich habe 2 Instanzen laufen. Evtl. ist das ein Hinweiß.

**Comment by stsch83** [comment]
[iobroker.2020-09-22.log.pdf](https://github.com/rg-engineering/ioBroker.heatingcontrol/files/5263357/iobroker.2020-09-22.log.pdf)

**Comment by rg-engineering** [comment]
okay, muss ich mir anschauen.
Kannst du das log nicht als normale txt hochladen?

**Comment by stsch83** [comment]
[iobroker.2020-09-23.log](https://github.com/rg-engineering/ioBroker.heatingcontrol/files/5265495/iobroker.2020-09-23.log)

**Comment by rg-engineering** [comment]
Du sagst, es laufen zwei Instanzen, im log ist aber nur heatingcontrol.0 zu sehen. Bei zwei Instanzen würde ich ein heatingcontrol.1 erwarten. Ist die Konfiguration beider Instanzen gleich (d.h. gleiche Räume, gleiche Geräte)?

**Comment by stsch83** [comment]
es scheint so, also ob der Adapter nicht damit zurecht kommt, wenn in mehreren Instanzen die gleichen Räume vorhanden sind. Dabei spielt es scheinbar keine Rolle ob beide Instanzen auch laufen. Die Räume müssen scheinbar auch nicht aktiv sein. 

Ich habe aus der Instanz.0 die überflüssigen Räume entfernt und anschließend auch keine Fehlermeldungen mehr erhalten.

**Comment by piscator83** [comment]
Konnte ein ähnliches Verhalten beobachten. Hatte aber nie 2 Instanzen, jedoch ungenutzte und inaktive Räume. Diese jetzt entfernt und vorerst keine Fehlermeldung mehr.

**Comment by rg-engineering** [comment]
wie sieht eure sonstige Konfiguration aus? (Profiltype, Anzahl Profile und Perioden, ...)

**Comment by piscator83** [comment]
Profiltyp: jeden Tag getrennt
Profile: 1
Perioden: 5
Feiertag wie Sonntag
Temperaturabsenkung relativ
keine Mindesttemperatur
keine vordefinierte Heizperiode

**Comment by stsch83** [comment]
[Uploading iobroker.2020-09-23.txt…]()

**Comment by stsch83** [comment]
Profiltyp: jeden Tag getrennt
Profile: 1
Perioden: 5
Feiertag wie Sonntag
Temperaturabsenkung absolut
keine Mindesttemperatur
keine vordefinierte Heizperiode

**Comment by rg-engineering** [comment]
ich kann das Problem hier nicht nachstellen... Habt ihr evtl. ein debug log von dem Verhalten?

**Comment by stsch83** [comment]
Ne, sorry hab leider nix. Ich möchte auch jetzt keine Experimente mehr machen, da die Heizsaison gerade bei uns begonnen hat.
