### ISSUE TITLE
Warnmeldung im Log

### ISSUE THREAD

**Issue by Siggi0904** [rg-engineering/ioBroker.heatingcontrol#134]
Hallo,

die Heizsaison ging heute los.
Das Addon machte auch pünklich los und alles funktioniert super.

Aber zwei Punkte.

**Warnmeldung im Log**
Es erscheint nun stündlich

    heatingcontrol.0 | 2020-10-01 17:09:03.366 | warn | (9288) override time not valid: 00:00
    heatingcontrol.0 | 2020-10-01 17:09:03.324 | info | (9288) change temperature override for room Bad

Wo kommt denn das her? Was kann ich dagegen machen?

**Umschaltung der Profile**
Ich hatte gestern abend noch vom Profil Mo-So auf Mo-Fr + Sa, So umgestellt.
Die Objekte des alten Profils bleiben aber unter Objekte erhalten.
Ist das so gewollt? Wäre doch besser, wenn die gelöscht werden würden, oder zumindest eine Nachfrage kommen würde.

**Comment by rg-engineering** [comment]
scchalte mal debug log ein. Ich vermute, dass dein Thermostat regelmässig den Ist-Wert der Zieltemperatur sendet. Das führt dazu, dass der Adapter prüft, ob etwas zu tun ist. Ich vermute weiterhin, dass du noch mit einer 0.5.x unterwegs bist. In der 0.6.x habe ich das Verhalten in diesem Zusammenhang ein wenig geändert, log-Meldungen kommen aber auch in der 0.6.x, das ist aber kein bug

Die Profile lösche ich absichtlich nicht, da es Leute geben soll, die zwischen den Einstellung hin-und herschalten und sich dann beschwerden würden, dass die Einstellungen verloren gehen. In deinem Fall müsstest du manuell löschen...

**Comment by Siggi0904** [comment]
Hi,
ja so ist es. Das hatten wir hier https://github.com/rg-engineering/ioBroker.heatingcontrol/issues/123#issuecomment-688448420 schon mal besprochen. Das sind ja die gleichen Thermostate. Dann warte ich erstmal auf die neue 0.6.x und berichte dann nochmal.

Okay, das mit den Profilen dachte ich mir schon fast.
Vielleicht kann man ja noch eine Abfrage zum Löschen integrieren.

Danke.
