### ISSUE TITLE
Presence control not working correctly when Override is Active

### ISSUE THREAD

**Issue by JoschaMiddendorf** [rg-engineering/ioBroker.heatingcontrol#137]
**Describe the bug**  
When an override temperature is active for one room `heatingcontrol.0.Rooms.Wohnzimmer.TemperaturOverride -> 22` and Presence changes to false `heatingcontrol.0.Present -> false `, only that room changes state to "not present" `heatingcontrol.0.Rooms.Wohnzimmer.State -> not present / override`. Other rooms stay in normal state `heatingcontrol.0.Rooms.Badezimmer.State -> normal` and therefore don't reduce target temperature.
`heatingcontrol.0.Rooms.Badezimmer.CurrentTarget -> 21`

**To Reproduce**  
1. Change Presence to true 
2. Set an Override temperature for one room
3. Change Presence to false
4. Check other rooms

**Expected behavior**  
Other rooms changing State to "not present".

**Versions:**  
 - Adapter version: 0.6.0
 - JS-Controller version: 3.1.6
 - Node version: v12.18.4
 - Operating system: UnRaid -> Docker -> buanet/iobroker -> debian:buster

**Comment by rg-engineering** [comment]
![grafik](https://user-images.githubusercontent.com/8238668/96347826-82331980-10a4-11eb-8840-e32d4ec2b0a4.png)

in my test case other rooms go to "not present" state. But there is still a bug in room where override was set (see picture)

In other words, I can not reproduce above described behavior.

**Comment by rg-engineering** [comment]
above described problem with null for CurrentTarget is fixed with 1.1.0...

**Comment by rg-engineering** [comment]
no further information received, so I close this issue
