### ISSUE TITLE
Until = bis, Adapter fährt ab der Uhrzeit die Temperaturen

### ISSUE THREAD

**Issue by guergen1** [rg-engineering/ioBroker.heatingcontrol#14]
Hallo,  
Wir haben grade 19:28Uhr und der Adapter zeigt Period 3:16:00:00 Uhr an, müsste er nicht danach in Period 4 sein?
Period 4 steht auf until 21:00:00 ?
Es würde ja reichen "ab" zu schreiben...

Ich nutze den Adapter im Übrigen mit einem Maxcul auf einem NUC, habe ihn aber grade auch erst mit einigen Schwierigkeiten installiert was die Räume angeht; aber da lag zu 99,9% an mir und meinem System

**Comment by guergen1** [comment]
Habe das jetzt mehrfach durchgespielt, scheint wirklich so zu sein, wie ich es beschrieben habe!

**Comment by rg-engineering** [comment]
so ist es auch implementiert: zum angegebenen Zeitpunkt wird die entsprechende Temperatur geschrieben. Beim nächsten angegebenen Zeitpunkt wird entsprechend die nächste Temperatur geschrieben. Es müsste also richtig heißen "ab" und nicht "bis". Das werde ich ändern...

**Comment by guergen1** [comment]
Perfekt!

**Comment by rg-engineering** [comment]
Ist mit 0.2.2 implementiert und kann getestet werden
