### ISSUE TITLE
Thermostat tut nicht was es soll

### ISSUE THREAD

**Issue by fischi87** [rg-engineering/ioBroker.heatingcontrol#142]
Hallo, im großen und ganzen erledigt der adapter was er soll. was mir auffällt, ab und an kommt es vor, das manche temperatureinstellungen, nach perioden wechsel nicht übernommen wird.

bsp. ich habe eingestellt, das alle thermostate ab 6:00 von 18 auf 21 grad gestellt werden soll. es kommt vor das ein thermostat nicht auf die neue temperatur geschaltet wird und bleib auf der temperatur von der letzten periode. es wechselt, welches thermostat nicht geschaltet wird, manchmal dass von der küche, manchmal dass vom wohnzimmer oder vom kinderzimmer. ich habe 5 thermostate in den adapter integriert, sollte von der menge her kein problem sein.

vielleicht kannst du mir dazu etwas sagen?

grüße Axel

**Comment by rg-engineering** [comment]
ohne weitere Info (debug log) kann ich dazu nichts sagen, da ich diesen Fehler nicht nachvollziehen kann... Also bitte debug log erstellen und hier posten.

**Comment by rg-engineering** [comment]
no further information received, so I close this issue
