### ISSUE TITLE
Fehler beim setzen eines Wertes und steigerung von Cron Jobs

### ISSUE THREAD

**Issue by EdgarM73** [rg-engineering/ioBroker.heatingcontrol#143]
Hi ,

seit ein paar Tagen bekomme ich immer Fehler im Log, dass er versucht NaN als Temperatur zu setzen.

Ich finde allerdings keinen Fehler in den Werten.

Außerdem macht der Adapter jedesmal neue Cron Jobs, nach 2 Tagen kommt dann die Fhelermeldung too many Cron Jobs (>500)

Mir ist leider nicht klar, was falsch sein könnte.

![grafik](https://user-images.githubusercontent.com/4679488/96029439-f7131300-0e5a-11eb-946e-45efcd72ebdb.png)

```
heatingcontrol.0 | 2020-10-14 20:16:26.241 | warn | (26055) target temperature is object null
-- | -- | -- | --
heatingcontrol.0 | 2020-10-14 20:16:24.366 | info | (26055) 203 cron job(s) created
heatingcontrol.0 | 2020-10-14 20:16:24.345 | info | (26055) set thermostat hm-rpc.0.LEQ1067412.4.SET_TEMPERATURE to NaN; current is 16
hm-rpc.0 | 2020-10-14 20:16:24.344 | error | (975) Cannot call setValue: Error: Missing element text
```

**Comment by rg-engineering** [comment]
Ds mit den cron jobs wurde schon hier diskutiert #131. Leider kann ich es nicht nachvollziehen, somit bisher noch keine Lösung...
Also bitte auch bzgl. des anderen Fehlers ein debug log posten. Danke.

**Comment by EdgarM73** [comment]
Hier das Debug log auf das es wohl ankommt:
Könnte es sein, dass es am Setting Override liegt?
btw, was bedeutet dieses Setting denn eigentlich?

grüße
E

`

heatingcontrol.0 | 2020-10-16 07:30:01.754 | warn | (9712) target temperature is object null
-- | -- | -- | --
heatingcontrol.0 | 2020-10-16 07:30:01.753 | debug | (9712) try to convert NaN to a number
heatingcontrol.0 | 2020-10-16 07:30:01.753 | debug | (9712) got {"val":16,"ack":true,"ts":1601490028542,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc":1601490028537}
heatingcontrol.0 | 2020-10-16 07:30:01.752 | debug | (9712) checking min temp with Rooms.Esszimmer.MinimumTemperature
heatingcontrol.0 | 2020-10-16 07:30:01.752 | debug | (9712) room Esszimmer Thermostat alias.0.Umwelt.esszimmer.ACTUAL target is NaN
heatingcontrol.0 | 2020-10-16 07:30:01.705 | debug | (9712) room Esszimmer setting new target null
heatingcontrol.0 | 2020-10-16 07:30:01.704 | debug | (9712) unsubscribe Esszimmer hm-rpc.0.LEQ1067412.4.SET_TEMPERATURE
heatingcontrol.0 | 2020-10-16 07:30:01.704 | debug | (9712) need to unsubscribe states
heatingcontrol.0 | 2020-10-16 07:30:01.704 | debug | (9712) in override target NaN
heatingcontrol.0 | 2020-10-16 07:30:01.615 | debug | (9712) room Esszimmer still in override until Fri Oct 16 2020 09:27:33 GMT+0200 (GMT+02:00)
heatingcontrol.0 | 2020-10-16 07:30:01.615 | debug | (9712) relative GuestIncrease {"val":0,"ack":true,"ts":1591722485579,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc":1591722485579} number
heatingcontrol.0 | 2020-10-16 07:30:01.615 | debug | (9712) relative AbsentDecrease {"val":3,"ack":true,"ts":1591724490287,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc":1591724490241} number
heatingcontrol.0 | 2020-10-16 07:30:01.614 | debug | (9712) relative PartyDecrease {"val":2,"ack":true,"ts":1591724488026,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc":1591724488023} number
heatingcontrol.0 | 2020-10-16 07:30:01.614 | debug | (9712) relative VacationAbsentDecrease {"val":10,"ack":true,"ts":1591724492717,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc":1591724492714} number
heatingcontrol.0 | 2020-10-16 07:30:01.583 | debug | (9712) relative WindowOpenDecrease {"val":10,"ack":true,"ts":1591724494781,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc":1591724494778} number
heatingcontrol.0 | 2020-10-16 07:30:01.540 | debug | (9712) Esszimmer window open is false
heatingcontrol.0 | 2020-10-16 07:30:01.540 | debug | (9712) check room Esszimmer

`

**Comment by rg-engineering** [comment]
Das Thema override wurde gerade heute im Forum diskutiert:
https://forum.iobroker.net/topic/22579/test-adapter-heatingcontrol-v1-0-x/1313
Anscheinend möchtest du keinen override setzen, der Adapter macht es aber trotzdem. Die Zieltemperatur für override kann auch nicht berechnet werden (NnN = not a number), die Frage ist, warum will der Adapter in den override? Kannst du mal die zwei DP TemperaturOverride und TemperaturOverrideTime prüfen? wenn TemperaturOverrideTime auf 00:00 steht, sollte die Funktion eigentlich ausgeschaltet sein...

**Comment by EdgarM73** [comment]
Jetzt verstehe ich das override.

Ich denke der Fehler war, dass ich override auf > 0 gesetzt habe, der Wert für override war aber "Inaktiv".

Da das Wort inaktiv keine Zahl ist kommt NaN dabei raus.

möglich?

grüße
E

**Comment by EdgarM73** [comment]
Meine Vermutung scheint richtig zu ein,
habe override auf 0 + inaktiv gesetzt -> es bleibt bei 12 cron Jobs und keine Fehlermeldung

Allerdings kann ich den CronJobs Fehler jetzt nicht mehr reproduzieren. Seltsam

**Comment by rg-engineering** [comment]
kannst du mir mal genau sagen, was du in TemperaturOverride und TemperaturOverrideTime  stehen hast / hattest (screenshot)? Vielleicht kann ich das ja nachvollziehen und einen zusätzlichen check einbauen, damit das niemanden anders mehr passiert...
Evtl. kannst du ja die settings wieder zurückändern und feststellen, ob dann die cron jobs wieder hochgehen? Dann wüssten wir wenigstens, dass dies die Ursache war...

**Comment by EdgarM73** [comment]
Ich versuche es mal, ob ich es doch reproduzieren kann.

**Comment by EdgarM73** [comment]
Selbst mit "falschen" Settings bekomme ich es nicht mehr hin, die Cron Jobs auf grösser 13 zu pushen :+1: 
Was ich gemacht hatte, um es zu vermeiden:

Habe initial mal alle override alle auf 0 gesetzt, und die Werte dazu auf inaktiv.

Seitdem schaffe ich es nichtmehr es kaputt zu machen.

Mehr infos hab ich leider nicht

grüße
E

**Comment by rg-engineering** [comment]
okay, dann schliesse ich das issue hier. Kann ja wieder geöffnet werden, wenn es neue Erkenntnisse gibt...
