### ISSUE TITLE
Ignorieren von Änderungen am Thermostat selbst

### ISSUE THREAD

**Issue by Wildbill-Z** [rg-engineering/ioBroker.heatingcontrol#144]
Momentan hat man ja nur die Möglichkeit Änderungen, die direkt am Thermostat oder der zugehörigen GUI (z.B. CCU) erfolgen, als Override zu verarbeiten, wobei eine Sollzeit zu hinterlegen ist, für wie lange die Änderung gelten soll, oder eben, dass der Adapter die Solltemperatur sofort wieder auf den im Profil hinterlegten Wert ändert.
Bei Homematic und Direktverknüpfungen heisst das z.B. dass beim Fensteröffnen die Direktverknüpfung den Sollwert senkt, der Adapter da aber sofort gegensteuern möchte. Das hat bei mir nie sauber geklappt und der Adapter ist irgendwann ausgestiegen mit diversen Fehlern. Und die gesamten Fensterfunktionen mit im Adapter zu regeln ist IMHO eher overkill, da das die Direktverknüpfungen perfekt regeln. Ehrlich gesagt brauche und wollte ich diese beiden Funktionalitäten auch gar nicht im Adapter bei mir.

Wie wäre es, bei der Option override eine zusätzliche Funktion "ignore" einzubauen, die dem Adapter sagt, dass manuelle Änderungen gar nicht beachtet werden sollen, sondern nur dann etwas zu tun ist, wenn ein Wochenprofil eine Änderung erfordert. Also den Adapter und die zugehörige VIS wirklich nur zum Einstellen und Abarbeiten von Wochenprofilen. Momentan helfe ich mir damit, dass ich zusätzliche Datenpunkte und Skripte verwende wie [HIER](https://forum.iobroker.net/topic/22579/test-adapter-heatingcontrol-v1-0-x/1318) beschrieben. Aber wenn das der Adapter von sich aus könnte, würde ich mir die Skripte sparen und hätte alles in Einem.

Gruss, Jürgen

**Comment by rg-engineering** [comment]
Änderungen vom Thermostat können bereits konfiguriert werden:
![grafik](https://user-images.githubusercontent.com/8238668/96332645-9572c480-1065-11eb-833f-6036af6ed931.png)

Trotzdem wird der Adapter immer versuchen, Abweichungen, die er erkennt (z.Bsp. in der Zieltemperatur) zu korrigieren. Das ist auch notwendig, weil ein Thermostat ja z.Bsp. einen restart gemacht haben könnte, und dann wollen wir ja, dass die richtige Zieltemperatur eingestellt wird.

**Comment by Wildbill-Z** [comment]
Die Punkte sind bekannt. Allerdings wäre da in meinen Augen eben ein weiterer Punkt "ignore" sinnvoll. Wenn ich ein fenster öffne, so regelt der Thermostat bei mir automatisch auf 12° und geht nach Schliessen wieder auf die vorherige Solltemperatur. Das geht auch selbst dann, wenn iobroker oder Pivccu nicht laufen würden, wegen Direktverknüpfung. Wenn ich jetzt im Adapter zum Einstellen direkt den jeweiligen Datenpunkt des Thermostats nehme, so versucht er sofort, den Wert wieder auf den Profilwert zu setzen, was nichts wird, da die Absenkung auf jeden Fall bleibt, bis das Fenster geschlossen wird. Wenn ich den "neuen" Wert "als Override" nehme, so wird es der Adapter versuchen, sobald die hinterlegte Override-Zeit vorbei ist. Wenn dann das Fenster noch offen ist, wird das auch nichts. Ebenso, wenn ich die Temperatur am Thermostat manuell ändere (was normal nicht vorkommt). Dann sollte das auch gelten, bis ich es ändere und nicht nach einer festgelegten Zeitspanne.
Andersrum, wenn es "ignore" im Adapter gäbe, so würde das gelten bis in einem Wochenprofil ein neuer Wert kommt. Dann darf der Adapter das gerne ändern, denn das habe ich ja mal gewollt so eingestellt. Wenn dann noch Fenster offen sind, dann ist es eben so.
Vielleicht liegt es ja daran, dass ich den Adapter eben nur mit eingeschränktem Funktionsumfang verwende, also quasi nur zum Einstellen und Ändern der Wochenprofile mittels der VIS, und alles andere (Override und Fenstersteuerung) eben nicht damit verwende. Aber wenn man die Override-Funktion wahlweise hätte oder eben Änderungen nur ignoriert würden, wäre am Adapter ja keinerlei Funktionalität verloren (wie von Dir oben erwähnt, könnte man ja weiterhin verwenden), sondern es käme etwas dazu, was der eine oder andere sicher brauchen könnte (indem man dem Adapter eben sagt dass er bestimmte Dinge eben nicht machen soll).

Gruss, Jürgen

**Comment by rg-engineering** [comment]
die 2.x liegt zum testen bereit. Aber Achtung: ist noch alpha-Status, also evtl. nicht fehlerfrei..

**Comment by rg-engineering** [comment]
sollte mit 2.0 jetzt passen, deshalb schliesse ich das issue hier...
