### ISSUE TITLE
Sensor typ != bool

### ISSUE THREAD

**Issue by udondan** [rg-engineering/ioBroker.heatingcontrol#146]
Hallo,

soweit ich das sehe, muss ein Sensor vom Typ bool sein. Ich habe einen Fibaro Fenster-Sensor, der liefert die Werte `22` oder `23` je nach Status. Damit habe ich keine Chance diesen als Sensor zu verwenden, oder? Wenn ich damit richtig liege, würde ich folgenden Vorschlag einbringen wollen:

**Describe wanted Enhancement !**  
Es sollte möglich sein, eine Bedingung in den Sensor-Einstellungen anzugeben. Per default kann diese `== true` sein. In meinem Fall würde ich dann `== 23` angeben.

**Why should we put effort in it ?**  
Weil nicht alle Sensoren einen boolschen Wert liefern.

Liebe Grüsse,
Daniel

**Comment by MMeinhardt1** [comment]
Hi, Du könntest Dir vorübergehend ein Script “basteln” mit dem Du Dir aus den Werten Deines Kontaktes mithilfe eines User DP die Werte z.B. 22 in true und 23 in false in dem neuen DP schreiben läßt. So sollte es dann zumindest erstmal funktionieren.

**Comment by AndreGl** [comment]
Hallo, 

ich habe ein ähnliches Problem mit den Sensoren von Bosch. Die zeigen im value nur OPEN und CLOSED an. Vielleicht wäre es eine gute Erweiterung, wenn man gleich den Wert für Offen und Geschlossen konfigurieren kann. 

Bis dahin muss eine eigene Variable mit einem kleinen Skript. 

Hier ein Screenshot von BSH
![20201216_232113](https://user-images.githubusercontent.com/146518/102413609-7d7fd880-3ff5-11eb-9813-3a27c3020cdf.jpg)

Viele Grüße

**Comment by rg-engineering** [comment]
@AndreGl kannst du mal schauen, von welchem Type dein "value" ist?

![grafik](https://user-images.githubusercontent.com/8238668/107121274-cf283f00-6891-11eb-9bb7-ac8320999b7d.png)

**Comment by AndreGl** [comment]
Hi, 
Das ist als STRING definiert.

`{
  "from": "system.adapter.bshb.0",
  "user": "system.user.admin",
  "ts": 160781685,
  "common": {
    "name": "Fenster Küche rechts.ShutterContact.value",
    "type": "string",
    "role": "text",
    "read": true,
    "write": true
  },
  "native": {
    "state": "value",
    "device": {
      "@type": "device",
      "rootDeviceId": "64-d7",
      "id": "hdm:HomeMaticIP:3014F711A000A42",
      "deviceServiceIds": [
        "ShutterContact",
        "BatteryLevel"
      ],
      "manufacturer": "BOSCH",
      "roomId": "hz_7",
      "deviceModel": "SWD",
      "serial": "3014F71142",
      "profile": "REGULAR_WINDOW",
      "name": "Fenster Küche rechts",
      "status": "AVAILABLE",
      "childDeviceIds": []
    },
    "deviceService": {
      "@type": "DeviceServiceData",
      "id": "ShutterContact",
      "deviceId": "hdm:HomeMaticIP:3014F711A0000092",
      "state": {
        "@type": "shutterContactState",
        "value": "CLOSED"
      },
      "path": "58FA42/services/ShutterContact"
    }
  },
  "acl": {
    "object": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1638
  },
  "_id": "bshb.0.hdm:HomeMaticIP:3014F71FA42.ShutterContact.value",
  "type": "state"
}`

Ich habe das mal hier reinkopiert.

**Comment by rg-engineering** [comment]
okay, dann füge ich string als möglichen Datentyp hinzu.... Danke.

**Comment by AndreGl** [comment]
Und wie konfiguriere ich dann, welcher String für Offen und welcher für Geschlossen steht?

Könnte man das irgendwo hinterlegen?

**Comment by rg-engineering** [comment]
Das wird so aussehen:

![grafik](https://user-images.githubusercontent.com/8238668/107122403-e36f3a80-6897-11eb-9d3f-f0ab77c38cdd.png)

**Comment by AndreGl** [comment]
Ja, das sieht sehr universell und vielversprechend aus.
Ich bin gespannt.

**Comment by udondan** [comment]
Vielen Dank für eure Arbeit! Als Ersteller des requests muss ich aber mal rückmelden, dass ich persönlich dieses Feature nicht mehr benötige. Den entsprechenden Sensor habe ich ausgetauscht, die neuen Sensoren haben alle boolean states 🖖

**Comment by rg-engineering** [comment]
available in 2.2; needs to be tested

**Comment by rg-engineering** [comment]
can we close that issue?
