### ISSUE TITLE
Bei Änderung vom Thermostat bis zum nächsten Profilpunkt müssen Sensoren berücksichtigt werden

### ISSUE THREAD

**Issue by rg-engineering** [rg-engineering/ioBroker.heatingcontrol#148]
siehe
https://forum.iobroker.net/topic/22579/test-adapter-heatingcontrol-v1-0-x/1410

gleichzeitig könnte der Mode zurückgesetzt werden, wenn am Thermostat die Profiltemperatur wieder eingestellt wird.

**Comment by Ahrenfelde** [comment]
Hi,
ich klinke mich mal hier ein.
Folgende Situation:
Im Schlafzimmer wird Grundsätzlich mit offenem Fenster geschlafen. Als Periode ist eine Absenkung um 21.30 Uhr auf 18C und eine Anhebung um 7.00 Uhr auf 21C eingestellt. 
Wenn jetzt abends das Fenster aufgeht, stellt der Adapter auch brav auf die Absenktemperatur um. Bei mir sind das absolut 4C, damit sind die HM Thermostate auf OFF.

Wenn dann allerdings die Periode um 7 Uhr auf 21C hochregelt geht die Heizung an, obwohl das Fenster noch offen ist. Hier müsste der Fensterkontakt doch Priorität haben, und damit auf OFF bleiben?

Als Override Einstellung habe ich, bis zum nächsten Profilpunkt gewählt, was bei manuellen Temperatur Änderungen auch gut passt, nur halt beim Fensterkontakt nicht.

Grüße
Jan

**Comment by rg-engineering** [comment]
die 2.x liegt zum testen bereit. Aber Achtung: ist noch alpha-Status, also evtl. nicht fehlerfrei..

**Comment by rg-engineering** [comment]
Mit 2.0 getestet, damit schliesse ich das issue hier...
