### ISSUE TITLE
exception, bei nur einem Profilpunkt (Raum) nach Tageswechsel

### ISSUE THREAD

**Issue by rg-engineering** [rg-engineering/ioBroker.heatingcontrol#149]
siehe
https://forum.iobroker.net/topic/22579/test-adapter-heatingcontrol-v1-0-x/1429

**Comment by KrX3D** [comment]
Hello, i got the same problem

(6340) exception in CheckTemperatureChange [TypeError: Cannot read property '0' of undefined]

in my bedroom 

period 0 is 27C at 00;00
perios 1 is 4.5C at 05:45

when i stand up at 6o clock the thermostat says still 27C and does not go down to 4.5C

it also says:

`

 
--
heatingcontrol.0 | 2020-10-30 17:32:02.923 | info | (30475) no temperature degrease configured 3
heatingcontrol.0 | 2020-10-30 17:32:02.869 | info | (30475) no temperature degrease configured 3
heatingcontrol.0 | 2020-10-30 17:32:02.862 | info | (30475) no temperature degrease configured 3
heatingcontrol.0 | 2020-10-30 17:32:02.781 | info | (30475) starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.heatingcontrol, node: v12.19.0, js-controller: 3.1.6

`

it worked so far last week but after i updated to the newest version i get this error only on my bedroom

**Comment by rg-engineering** [comment]
bug fix available, would be good if someone could test it...

**Comment by rg-engineering** [comment]
solved wit V1.1.1
