### ISSUE TITLE
Fenstererkennung im manuellen Modus

### ISSUE THREAD

**Issue by KraxelHuber** [rg-engineering/ioBroker.heatingcontrol#152]
Die Kombination "Fenster auf --> Temperatur fährt runter" funktioniert grundsätzlich gut. Allerdings mit einer Einschränkung: Die Temperatur wird nur automatisch abgesenkt, wenn der ``state`` in dem entsprechenden ``Room`` auf ``normal`` steht, d.h. wenn gerade ein Wochenprogramm aktiv ist. Sobald die Temperatur am Thermostat manuell verstellt wird und der ``state`` damit den Wert ``change from thermostat`` annimmt, wird die Temperatur nicht mehr automatisch abgesenkt, wenn man das entsprechende Fenster öffnet.

Grundsätzlich sollte es meiner Meinung nach jedoch keine Rolle spielen, ob sich das Thermostat gerade im Auto- oder manuellen Modus befindet. Wenn der Fenstersensor auf ``true`` steht, sollte die Heizung herunterfahren.

Gegebenenfalls könnte man die Aktivierung dieses Features optional gestalten, d.h. wenn jemand die Heizung im manuellen Modus nicht herunterfahren möchte, sobald das Fenster geöffnet wird, kann er dieses Feature dann deaktivieren.

**Comment by rg-engineering** [comment]
die 2.x liegt zum testen bereit. Aber Achtung: ist noch alpha-Status, also evtl. nicht fehlerfrei..

**Comment by rg-engineering** [comment]
Mit 2.0 getestet, damit schliesse ich das issue hier...
