### ISSUE TITLE
Wert für Fenster offen überschreibt Temperaturen in der Periode.

### ISSUE THREAD

**Issue by Hohenbostler** [rg-engineering/ioBroker.heatingcontrol#154]
ich habe einen absoluten Wert für Fenster offen . Jetzt hat gerade der Adapter von eine Periode auf die nächste geschaltet. Aber dazu war das Fenster offen. Jetzt hat er die Periode geändert aber alle Werte mit dem absolut wert von Fenster offen überschrieben. Das soll doch eigentlich nicht sein oder ?

**Comment by rg-engineering** [comment]
nein, das sollte nicht sein. Zur Fehlereingrenzung benötige ich aber mehr informationen (Einstellungen, debug log file ...)
hast du evtl. ein "vom Thermostat holen und auf Profil schreiben" aktiviert?

**Comment by Hohenbostler** [comment]
Hi, 

oh man da war ich wohl zu voreilig. Ich habe es am abend noch weiter getestet und entsprechend bin ich mir nicht mehr 100% ig sicher. Ich glaube es war -> Wenn jemand am Thermostat dreht pro Raum einstellbar. Der Fenster auf Wert war auf absolut und 5° . Perioden habe ich nur 2. Und beim umschalten von Periode 0 auf 1 war das Fenster geöffnet.

**Comment by w0nk1** [comment]
Guten Morgen,

ich habe ebenfalls ein Problem mit dem Status "Fenster offen". Ich habe nur eine Heizperiodeaktiv (Abschnitt). Die Absenkungsmethode ist auf "relativ" gestellt. Die Temperatur soll sich um -10 relativ zu den 21.5 °C absenken. Das funktioniert auch erstmal ohne größere Probleme.

Wenn nun allerdings jemand während das Fenster geöffnet wurde, nun am Thermostat einen manual Override startet von z.B 22 °C und danach das Fenster geschlossen wird, scheint die Berechnung nicht mehr zu stimmen und der gesetzte Wert rutscht dramatisch nach unten ab. Dann steht plötzlich ein -5.5 °C im Raum oder ein +4.5 °C.

Ist dieser Fehler auf dem Schirm? Oder brauchst du da mehr Logs etc.?

Danke, für den tollen Adapter. :-)
