### ISSUE TITLE
Ignore periods for single thermostates

### ISSUE THREAD

**Issue by tsvsj** [rg-engineering/ioBroker.heatingcontrol#158]
Hi there,

thanks for this great adapter. It took me a while to get it up and running, but the idea behind this is great.

I'm struggling with the periods. For a single device I need 5 periods, while all others only need 4. I've set the temp to 0°C in hope, that this value is ignored. Unfortunately not. The adapter tries to set a temp of 0°C. Is there any way to kind of disable periods or do all devices always need all periods, that are globally configured?

Another thing is the difference between the current and target temp in the device configuration. The adapter logs a warning message, that the configuration is wrong, because current = target OID. Unfortunately the Danfoss Living Z doesn't provide a current value, only the target value, so I've set both to the same OID.
I'm aware, that warnings are ignorable, but may this could be considered in future versions.

Regards

**Comment by rg-engineering** [comment]
you can set target temperature for different profile points (periods) to the same value. Then it works as expected. It's not possible to use different number of profile periods for different rooms.
if you don't use actuators then it's not necessary to configure current OID. Just leave it empty. This will avoid above mentioned warning.

**Comment by tsvsj** [comment]
When removing the current value, I receive
```
error: heatingcontrol.0 (30589) exception in CheckTemperatureChange [Error: The id is empty! Please provide a valid id.]
``` 
in the Log.

Additionally I saw the message
```
warn: heatingcontrol.0 (29061) more then 500 cron jobs existing for this adapter, this might be a configuration error! (15340)
```
a hundred times.

**Comment by rg-engineering** [comment]
the cron job issue was discussed already a few times (see  #153 or forum). Right now I can not fix that behavior in 1.x but it will be fixed in 2.x. Until release of 2.x you need to wait one ore two seconds between different changes in profil... or restart adapter.

The above mentioned exception should not appear. Here I would like to have a debug log. But keep in mind I will fix only critical bugs in 1.x because I'm working already on 2.x

**Comment by tsvsj** [comment]
That's ok for me. After 1 day with the full configuration of iobroker.heatingcontrol everything seem to work fine. So for now, I wouldn't rate any of the issues as critical. Let's move on 2.x :-)

**Comment by tsvsj** [comment]
Hi,

sorry for re-opening this issue, but I'm not sure whether the message
```
error: heatingcontrol.0 (12049) exception in CheckTemperatureChange [Error: The id is empty! Please provide a valid id.]
```
is only a cosmetic issue. I constantly get this message, even if the current temperature OID is provided for a thermostat. The message is displayed during the initialization of the adapter and each time the window open mechanism tries to set the target temperature.
I've set the adapter to debug mode, but there are no relevant messages around.
```
2020-12-09 09:36:50.987  - debug: heatingcontrol.0 (12049) room Bathroom  setting new target 21
2020-12-09 09:36:51.000  - debug: heatingcontrol.0 (12049) room Bathroom Thermostat zigbee.0.xxxxx.heating_setpnt_current target is 21
2020-12-09 09:36:51.004  - debug: heatingcontrol.0 (12049) checking min temp with Rooms.Bathroom.MinimumTemperature
2020-12-09 09:36:51.007  - debug: heatingcontrol.0 (12049) got {"val":0,"ack":true,"ts":1607461532465,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc":1607461532465}
2020-12-09 09:36:51.012  - info: heatingcontrol.0 (12049) set thermostat zigbee.0.xxxxx.heating_setpnt_occupied to 21; current is 5
--> 2020-12-09 09:36:51.033  - error: heatingcontrol.0 (12049) exception in CheckTemperatureChange [Error: The id is empty! Please provide a valid id.]
2020-12-09 09:37:00.988  - debug: heatingcontrol.0 (12049) need to subscribe states now
```

Althoug I'm not really experienced with ioBroker adapter dev, I've search the string `The id is empty` in the main.js, but wasn't able to find it. So I'm not sure, from where the error is created. I've seen, that `CheckTemperatureChange` is executed each time, when the window open timeout is reached (wait times).

**Comment by rg-engineering** [comment]
You need to provide a OID for "target OID" but you can leave "current OID" empty.
![grafik](https://user-images.githubusercontent.com/8238668/101991214-79795100-3cab-11eb-823a-b271346ea5ef.png)

**Comment by tsvsj** [comment]
Target is always set. Only current is left empty for a single device, that do not provide the current value.

**Comment by rg-engineering** [comment]
but the exception is thrown in "set thermostat" and there I use only target OID. The exception itself comes from the system, not from adapter...
Can you show me your configuration for that room (or download the complete configuration here:

![grafik](https://user-images.githubusercontent.com/8238668/102006139-0d383500-3d1f-11eb-9ddf-0322f3466a92.png)
?

**Comment by tsvsj** [comment]
That's weird. Is there a way to provide the configuration privately?

**Comment by rg-engineering** [comment]
just send an email to info@rg-engineering.eu

**Comment by rg-engineering** [comment]
die 2.x liegt zum testen bereit. Aber Achtung: ist noch alpha-Status, also evtl. nicht fehlerfrei..

**Comment by rg-engineering** [comment]
see #177
