### ISSUE TITLE
Trigger windowOpen OID of Thermostates directly

### ISSUE THREAD

**Issue by tsvsj** [rg-engineering/ioBroker.heatingcontrol#159]
**Describe wanted Enhancement !**  
Various Thermostates have a writeable windowOpenState included (boolean). It would be great, if the adapter would optionally publish the state from the sensor to the Thermostate OID itself. I'm using the Zigbee Thermostate Eurotronic SPZB0001 widely, which turns itself to `OFF`, when an open window is detected, instead of reducing the temperature. Unfortunately the sensivity of the included window open sensor doesn't work quite well, why I use additional sensors.

**Why should we put effort in it ?**  
Because it would be a great enhancement, to fully disable heating of a Thermostate, if supported.

**Comment by rg-engineering** [comment]
There is already a DP ("WindowIsOpen"). why not use it?
The only problem I foresee is what will the thermostat sends as a current target temperature?

**Comment by tsvsj** [comment]
It's not about a missing DP. I'm asking for a sync between the DP from heatingcontrol and the Thermostat. The Thermostag send 5°C as temperature, the lowest possible. Currently I'm decreasing the temperature to the absolute value of 5 degree. But it's is not the same as setting if to `OFF` by `windows_open=true`.

**Comment by rg-engineering** [comment]
understood, but with a very small script you can achive such a behavior

```
on("heatingcontrol.0.Room.WindowIsOpen", function(obj) {

    var val = obj.newState.val;

    setState('your_Thermstat-DP', val );

});

```

Do you use 
![grafik](https://user-images.githubusercontent.com/8238668/102005947-25a75000-3d1d-11eb-8558-9da008615d39.png)
other than "none"?

**Comment by tsvsj** [comment]
Sorry for the delay. Yeah, I'm aware of the simple code that is necessary to sync the state. But there is more complexity to achieve the wait time into window open and out of window open, what you adapter is already doing.

It was just an idea. If you say, that it needs to much effort to implement that sync, that's ok for me. Maybe I'm the only one who would see an advantage in such a feature. ;-)

**Comment by tsvsj** [comment]
> Do you use
> ![grafik](https://user-images.githubusercontent.com/8238668/102005947-25a75000-3d1d-11eb-8558-9da008615d39.png)
> other than "none"?

No

**Comment by rg-engineering** [comment]
> But there is more complexity to achieve the wait time into window open and out of window open, what you adapter is already doing.

yes and therefore you could use WindowOpen-datapoint together with a small script...

**Comment by tsvsj** [comment]
Ah..now I got your point and that makes sense to me. I wasn't aware, that the DP from the adapter will change after wait time. That's great. Thanks!
