### ISSUE TITLE
Profil springt zur angegebenen Zeit nicht um. 

### ISSUE THREAD

**Issue by emddummi** [rg-engineering/ioBroker.heatingcontrol#161]
Ich habe dazu mal ein Bildschirmvideo gemacht indem man sieht das er erst noch auf dem alten Zeitfenster steht und dann erst umspringt wenn man was ändert. 

![Screenshot_2020-12-15-21-40-00-346_com android chrome](https://user-images.githubusercontent.com/1787935/102270767-b0a36880-3f1e-11eb-9d6b-4775d16364d4.jpg)

Also als Bild von vorher, sobald ich einen Wert ändere springt er sofort auf die richtige Heizperiode... 

Wie kann ich bei der Fehlersuche unterstützen? 

Mit freundlichen Grüßen 
eMd

**Comment by dsiggi** [comment]
Hi,
ich hab das gleiche Problem. Ab und zu wird nicht Zeitfenster nicht automatisch gewechselt.
Mit einem Neustart des Adapters oder dem ändern eines Wertes springt er dann in das richtige zeitfenster.

Gruß,
dsiggi

**Comment by rg-engineering** [comment]
habt ihr euch die Datenpunkte angeschaut? ist das dort auch falsch oder nur in der vis?

**Comment by dsiggi** [comment]
> habt ihr euch die Datenpunkte angeschaut? ist das dort auch falsch oder nur in der vis?

Hi,
ich hab mir die Datenpunkte nicht angesehen. Meine Heizungen standen aber alle noch auf der Solltemperatur des letzten Zeitfensters. Darum ist es mir auch aufgefallen das nicht umgeschalten wurde.

Gruß,
dsiggi

**Comment by rg-engineering** [comment]
okay, dann wäre ein debug log von dem entsprechenden Umschalt-Zeitpunkt der nächste Schritt. Dazu den Adpater auf debug umschalten, warten bis das Problem wieder auftritt und dann den entsprechenden log-Abschnitt mir zukommen lassen. Im Idealfall hilft auch ein flot-Diagramm wie dieses (das ist ein Beispiel aus meinem Dauertest der 2.x, mit override, Fenster auf/zu und Profil-Änderungen)):
![grafik](https://user-images.githubusercontent.com/8238668/102765020-566e3180-437c-11eb-82f2-7aea9bf65fc3.png)

**Comment by dsiggi** [comment]
Hi,
ich hab den Log mal auf debug gestellt und mir ein Flot angelegt. Ich melde mich dann hier wieder sobald es wieder passiert.

Gruß,
Daniel

**Comment by dsiggi** [comment]
So, es ist wieder passiert.

Da auf dem Flot nicht wirklich etwas zu erkenne ist, hier kurz der Stand zu den Datenpunkten als das Profil eigentlich umschalten sollte. Ich nehme jetzt hier exemplarisch das Wohnzimmer. Das Problem ist aber in allen Räumen.

- heatingcontrol.0.HolidayPresent = **true**
- heatingcontrol.0.Present = **true**
- heatingcontrol.0.VacationAbsent = **false**
- heatingcontrol.0.Rooms.Wohnzimmer.ActiveTimeSlot = **7**
- heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod = **3**

Um 8:30 hätte die Heizung von 17°C auf 21,5°C umschalten müssen.
Als ich dann kurz die Temperatur für "Wochenende 08:30" geändert habe (ca. um 09:30), wurde auch auf die passende Zeit umgeschaltet.

Hier kurz die Einstellungen des Heizplanes:
![Heizplan](https://user-images.githubusercontent.com/11602767/102868573-a14e7e80-443a-11eb-92a2-c79b974b363c.png)

Und hier der Debug-Log:
[heatingcontrol.log](https://github.com/rg-engineering/ioBroker.heatingcontrol/files/5728728/heatingcontrol.log)

Ich hoffe du kannst damit etwas anfangen.

Gruß,
dsiggi

**Comment by rg-engineering** [comment]
passiert das immer bei heatingcontrol.0.HolidayPresent=true?
Im log sehe ich, dass um 6:30Uhr Wohnzimmer neu berechnet wird, dort aber die 17°C von gestern abend gefunden werden (was ja richtig ist, da erst um 8:30Uhr auf 21,5°C geschaltet werden soll.) Nächster cron Termin ist dann 8:00Uhr, was auch aus dem Mo-Fr-Profil stammt. Es sieht mir danach aus, als ob bei heatingcontrol.0.HolidayPresent=true die cron jobs nach Mo-Fr berechnet werden, die Zieltemperaturen aber richtigerweise vom Wochenende.
Wenn das so stimmt, würde ich gern auf die Version 2.x diesbezüglich verweisen

**Comment by dsiggi** [comment]
Hi,
da ich im Moment Urlaub habe ist HolidayPresent im Moment um diese Uhrzeit immer true. Ich werde es aber heute Abend mal auf false setzen und schauen wie es sich dann morgen früh verhält. Sollte es dann funktionieren werde ich mal die Version 2 testen.

Gruß und danke,
dsiggi

**Comment by rg-engineering** [comment]
ich bin zwar mit V2.x auf der Zielgeraden, die ist aber sicher noch nicht für den live-Einsatz geeignet. Das braucht noch etwas Zeit...

**Comment by dsiggi** [comment]
Hi,
also es liegt definitiv an HolidayPresent=true. Ich habe die letzten beiden Tage HolidayPresent auf false gesetzt und somit das "normale" Wochenheizprogramm genutzt. Hier wurde ohne Probleme das Zeitfenster umgeschaltet.

Ich habe mir jetzt erst mal ein Workaround-Script gebastelt, welches um 8:30 Uhr immer kurz eine Temperatur hin und her ändert. Freue mich dann aber natürlich schon auf die Version 2 sobald sie fertig ist.

Gruß und schöne Freitage,
dsiggi

**Comment by emddummi** [comment]
Also ich nutze diesen Datenpunkt nicht und trotzdem habe immer wieder mal den Fehler. Ich vermute das liegt manchmal an einer schlechten Verbindung der homematic thermostate, aber leider prüft heatingcontrol innerhalb einer Profil Zeit nicht ob immer noch die gewünschte Temperatur eingestellt ist. Es wird Punkt 12uhr umgeschaltet, bis zum nächsten Zeitpunkt werden die Werte nicht mehr kontrolliert... Bei Fenster auf und wieder zu springt er auch auf den falschen Wert vorher und nicht auf den der aktuell sein sollte...

**Comment by rg-engineering** [comment]
die 2.x liegt zum testen bereit. Aber Achtung: ist noch alpha-Status, also evtl. nicht fehlerfrei..

**Comment by Denkra** [comment]
Habe es probiert. Das Problem was ich habe ist nicht das er nicht umspringt, sondern das er eine total falsche Zeit nimmt. Wenn er um 8 Uhr auf 21 Grad gehen soll dann ist er aber 2 Zeitfenster weiter und stellt die Wohnung wieder auf 16.5

**Comment by rg-engineering** [comment]
auch mit der 2.0 von hier?

**Comment by Denkra** [comment]
Ja gerade bei der 2.0 macht er das. Die aktuelle macht auch Probleme siehe #183

**Comment by rg-engineering** [comment]
sollte mit 2.0 jetzt passen, deshalb schliesse ich das issue hier...
