### ISSUE TITLE
(2612) exception in CheckTemperatureChange [Error: The id is empty! Please provide a valid id.]

### ISSUE THREAD

**Issue by Grizzlyco** [rg-engineering/ioBroker.heatingcontrol#162]
(2612) exception in CheckTemperatureChange [Error: The id is empty! Please provide a valid id.]
taucht im Log auf. 
Fehler kann ich keinen finden.

**Comment by rg-engineering** [comment]
das Thema wurde schon hier diskutiert : #158
dort sind wir zu keiner Lösung gekommen.

**Comment by rg-engineering** [comment]
see #177
