### ISSUE TITLE
Abwesend Temp für nur beim 1. Gerät gesendet. MaxCube

### ISSUE THREAD

**Issue by Grizzlyco** [rg-engineering/ioBroker.heatingcontrol#163]
Wenn ich den Datenpunkt "Anwesend" auf False stelle wird nur das Thermostat im obersten Raum auf die geänderte Temp gestellt. Wenn ich die Räume tausche wird auch nur das 1. ( oberste ) verstellt. Im Log steht auch nur das 1. Von den andren steht nichts im Log.

**Comment by rg-engineering** [comment]
schaun wir uns in der 2.x an...

**Comment by rg-engineering** [comment]
sollte mit 2.0 passen, deshalb schliesse ich das issue hier...
