### ISSUE TITLE
Übersetzungsfehler?

### ISSUE THREAD

**Issue by Siggi0904** [rg-engineering/ioBroker.heatingcontrol#166]
Hi,

in den Objekten gibt es "heatingcontrol.0.VacationAbsent"
aber in der Heatingcontrol Instanz kann ich den Pfad zum Datenpunkt "Urlaub zu Hause" einstellen.

Sollte das dann nicht Pfad zum Datenpunkt "Urlaub **_nicht_** zu Hause" heißen?

Der andere Urlaubsdatenpunkt scheint "heatingcontrol.0.HolidayPresent" zu sein.
Dieser scheint dann "Pfad zum Datenpunkt "Urlaub" in der Instanzeinstellung zu sein.

Und ein anderer Optimierungspunkt in den Instanzeinstellungen gibt es unter
den Thermostateinstellungen die Option "als Override"
In der Anleitung hier, also die Readme.md steht dann noch, dass man zusätzlich in den
Profileinstellungen eine Override Zeit einstellen soll.

Evtl. könnte man diese Hinweise auch in den Instanzeinstellungen anfügen, um es genauer zu erklären.
Dabei gleich die Frage, was ist diese Override time?

Danke.

**Comment by rg-engineering** [comment]
die Bezeichnungen schaue ich mir an.

bzgl. override: es gibt TemperaturOverride und TemperaturOverrideTime. Die liegen parallel unter dem jeweiligen Raum:
heatingcontrol.0.Rooms.Wohnzimmer.TemperaturOverride
heatingcontrol.0.Rooms.Wohnzimmer.TemperaturOverrideTime

Für den "normalen" override werden diese beiden DP benötigt. Für den override, ausgelöst durch Änderung vom Thermostat wird TemperaturOverrideTime benötigt, um anzugeben, wie lange dieser override Gültigkeit hat...

**Comment by Siggi0904** [comment]
Macht diese Umsetzung Sinn?

Folgendes UseCase:
Jemand kommt zu Besuch und stellt abends am Thermostat um, weil es ihm beim Duschen zu kalt ist.
Dann kann ich doch nicht noch extra eine Zeit definieren, sondern das Override sollte sofort gelten.

Aus dem o.g. Grund mit der Override Time habe ich das aktuell auf "bis zum nächsten Profilpunkt" umgestellt.
Vielleicht kann man die vielen Optionen ein wenig ausdünnen.

Dank dir.

**Comment by rg-engineering** [comment]
naja, die vielen Optionen sind ja von den usern gewünscht, weil es jeder ein wenig anders haben will. Trotzdem habe ich eine dieser Optionen schon entfernt. Man kann das ganze nicht mehr pro Raum separat einstellen...
Die override-Zeit kann übrigens permanent stehen bleiben. Andere user haben sich ein kleines script gebaut, welches Zeit und Temperatur anpasst...

**Bzgl. der Datenpunkte:**
* heatingcontrol.0.VacationAbsent -> bedeutet, ich bin im Urlaub verreist und möchte eine Absenkung. Dazu passend ist heatingcontrol.0.Profiles.1.Raum.relative.AbsentDecrease.  Der externe Datenpunkt wird im admin unter "Pfad zum Datenpunkt Urlaub" eingestellt
* heatingcontrol.0.HolidayPresent -> bedeutet, ich bin im Urlaub zu Hause. Im admin der Instanz kann man nun einstellen, dass dann das Sonntags-Profil verwendet werden soll. Der externe Datenpunkt wird im admin unter "Pfad zum Datenpunkt Urlaub zu Hause" eingestellt

Ich werde nun im admin die Beschreibung "Pfad zum Datenpunkt Urlaub" in "Pfad zum Datenpunkt "Urlaub abwesend" ändern.

**Comment by rg-engineering** [comment]
@Siggi0904 passt das so und können wir das issue hier schliessen?

**Comment by Siggi0904** [comment]
Was müsste denn bei Override Time stehen, wenn der Override immer gelten soll?

Am Besten wäre es, wenn die Erklärungen zu den Funktionen mit in den Adapter im IOBroker fließen würden.
Dann kann man die Funktionen entsprechend nachlesen.

Ansonsten kann das dann zu, ja.

**Comment by rg-engineering** [comment]
> Was müsste denn bei Override Time stehen, wenn der Override immer gelten soll?

z.Bsp. "00:20" für zwanzig Minuten...

Bzgl. Dokumentation: ich werde im Rahmen der 2.x die Doku anpassen. Habe damit schon teilweise begonnen, aber wie immer kommt das meist zu kurz...

**Comment by Siggi0904** [comment]
Ach, das ist eine Angabe für die Dauer. Ich dachte, das ist eine Bis-Uhrzeit.

So entdeckt man so viele Sachen, die mit dem Adapter gehen.

**Comment by rg-engineering** [comment]
👍 
aber stimmt, das steht so noch nicht in der Doku.
