### ISSUE TITLE
SA/SO wird nicht richtig gespeichert.

### ISSUE THREAD

**Issue by detafun** [rg-engineering/ioBroker.heatingcontrol#169]
Deine Versionen 3.1.0 Adaper und VIS (ZIP) installiert.

![grafik](https://user-images.githubusercontent.com/44980055/103301789-60d69e00-4a02-11eb-9894-740dab6abd19.png)

Wenn ich jetzt den Wert unter SA/SO ändere, bleibt er nicht gespeichert. Sobald ich auf einen Anderen Raum gehe.

Stelle ich jetzt 16 Uhr auf 27 Grad
![grafik](https://user-images.githubusercontent.com/44980055/103301906-ae530b00-4a02-11eb-8126-3a5d424d933b.png)

Gehe jetzt auf Raum Wohnzimmer
![grafik](https://user-images.githubusercontent.com/44980055/103301967-ccb90680-4a02-11eb-8ae6-55e0071006f9.png)
Steht für Wohnzimmer 21 Grad drinnen.
Stelle ich gleich wieder auf Badezimmer
![grafik](https://user-images.githubusercontent.com/44980055/103302014-ed815c00-4a02-11eb-98d4-96202e425c27.png)

Steht nicht mehr 27 Grad bei 16 Uhr sondern 21 Grad wieder.

**Comment by detafun** [comment]
Nachtrag, scheint ein VIS Problem zu sein, hab es mal Manuell in den Objekten verbessert, da bleibt es.

**Comment by rg-engineering** [comment]
muss ich mir anschauen...

**Comment by rg-engineering** [comment]
Änderungen waren hier im adapter und im vis notwendig.
Unter https://github.com/rg-engineering/iobroker-heatingcontrol-vis#update-von-version-301-auf-die-neue-310 erkläre ich, was für das Profil Mo-Fr/Sa-Su geändert werden muss

**Comment by detafun** [comment]
Hab jetzt das auf Sa-Su geändert, aber leider immer noch nicht.
heatingcontrol.0.vis.ProfileTypes.Sa-Su.Periods.1.Temperature

**Comment by rg-engineering** [comment]
du hast das für alle Perioden (5 ?) und da jeweils für Zeit und Temperatur im vis gemacht?
und du hast den aktuellen Adapter von hier installiert?

**Comment by detafun** [comment]
Den Adapter hab ich noch nicht wieder seit gestern aktuallisiert. 
Alle 5? In Mo bis Fr steht bei 2 auch nur "heatingcontrol.0.info.NumberOfPeriods" Da es ja wohl bei Mo - Fr funktioniert.

Kannst du vielleicht einen Export von dem View hier runterladen, das ok ist.

**Comment by detafun** [comment]
Es war das Problem, das der Adapter noch nicht auf die wieder neue Version vom Git war. Wäre gut zwischen durch eine Info zu bekommen, das es da ein Update gibt.
Und bei mir ist es jetzt so, das bei 
Per1.    heatingcontrol.0.vis.ProfileTypes.Sa-Su.Periods.1.Temperature  steht
Per2.    heatingcontrol.0.info.NumberOfPeriods
dite Per 3 - 5

**Comment by detafun** [comment]
geht doch noch nicht richtig

**Comment by rg-engineering** [comment]
> Wäre gut zwischen durch eine Info zu bekommen, das es da ein Update gibt.

habe ich doch oben geschrieben: 

> Änderungen waren hier im adapter und im vis notwendig.

bei Periode 2 bis 5 muss auch `ProfileTypes.Sa-Su` und nicht `NumberOfPeriods` aktualisiert werden!
Im vis-repo habe ich die Änderungen schon hochgeladen..

**Comment by detafun** [comment]
Du meinst, 
heatingcontrol.0.info.NumberOfPeriods
muss mit 
 heatingcontrol.0.vis.ProfileTypes.Sa-Su.Periods.1.Temperature
ersetzt werden?

**Comment by detafun** [comment]
So hab es runtergeladen das komplette zip. neu importiert und das eine VIEW dann in mein eigentliches kopiert. Es geht jetzt.

**Comment by rg-engineering** [comment]
> Du meinst,
> heatingcontrol.0.info.NumberOfPeriods
> muss mit
> heatingcontrol.0.vis.ProfileTypes.Sa-Su.Periods.1.Temperature
> ersetzt werden?
> 

Nein! Ich meine, überall wo `heatingcontrol.0.vis.ProfileTypes.Sa-So` steht muss auf `heatingcontrol.0.vis.ProfileTypes.Sa-Su ` geändert werden. Die Datenpunkte selbst dürfen nicht verwechselt werden...
