### ISSUE TITLE
Sekunden werden nicht in der Timeliste benötigt

### ISSUE THREAD

**Issue by guergen1** [rg-engineering/ioBroker.heatingcontrol#17]
Hi,

kannst Du die Zeiten auf Stunden und Minuten begrenzen?
Es sieht einerseits ziemlich komisch in der Zeitentabelle aus, noch bracht man sekundengenaue Zeiteinstellungen!?

**Comment by rg-engineering** [comment]
Ist mit 0.2.2 implementiert und kann getestet werden

**Comment by guergen1** [comment]
Alles Klar, die Sekunden sind weg; sieht gleich viel Besser aus!
Danke!
