### ISSUE TITLE
Urlaub Anwesend, wird die Zeit Mo - Fr benuztzt nicht SA/SO

### ISSUE THREAD

**Issue by detafun** [rg-engineering/ioBroker.heatingcontrol#170]
Wenn Urlaub Anwesend aktiv, wird die Temperatur aus den Einstellungen Mo - Fr benutzt, sollte aber Sa / So sein.

**Comment by rg-engineering** [comment]
ja, das muss ich noch ändern...

**Comment by detafun** [comment]
Wäre schön, was du geändert hast dann.. Vielleicht die View hier als Export

**Comment by detafun** [comment]
Hast du bei dem Problem auch bereits was gemacht? Bei mir Wird trotz Urlaub anwesend, Mo-Fr benutzt nicht Sa/So

**Comment by rg-engineering** [comment]
nein, das ist noch offen... muss erst noch ein anderes Problem beheben, dann kommt das hier dran...

**Comment by rg-engineering** [comment]
sollte nun auch funktionieren. Im admin habe ich noch eine Option hinzugefügt, dass bei Urlaub zu Hause das Sonntags-Profil verwendet wird, ähnlich wie Feiertag. Wenn man das nicht aktiviert, wird Urlaub zu hause einfach ignoriert...

**Comment by detafun** [comment]
Jep Adapter Update gemacht,
Test Top funktioniert, sowohl als auch klasse.
Wenn jetzt das noch in Deutsch wäre :"Status: auto holiday at home" :-)
