### ISSUE TITLE
V2 - Frage zu DP CurrentTimePeriod

### ISSUE THREAD

**Issue by MMeinhardt1** [rg-engineering/ioBroker.heatingcontrol#171]
Hi,
ich weiß nicht ob es ein Fehler ist, aber mir es aufgefallen.
Der Wert in dem Datenpunkt "heatingcontrol.0.Rooms.*Raumbezeichnung*.CurrentTimePeriod" wird in rot, also als nicht bestätigt dargestellt.

Gruß Michael

**Comment by rg-engineering** [comment]
verwendest du die Pittini-vis?

**Comment by MMeinhardt1** [comment]
Nein

**Comment by rg-engineering** [comment]
okay, dann Fehler gefunden... für die Pittini-vis darf ich das ack nicht setzen, weil der Adapter sich selbst triggern muss, um vis-Daten zu aktualisieren. Dann wird von dort das ack gesetzt. Ohne vis muss ich das ack direkt setzen...

**Comment by MMeinhardt1** [comment]
Erledigt
