### ISSUE TITLE
Kamin / Kachelofen Modus

### ISSUE THREAD

**Issue by detafun** [rg-engineering/ioBroker.heatingcontrol#173]
Kamin Modus.
Ich hab das bei mir gerade Improvisiert gemacht.

Starte den Partymodus (sogar mit der Dame Alexa, schalte Kachelofenmodus an) dann geht er in den PartyModus. 
Und über ein extra Blocky, geht er wieder Aus gegen Mitternacht. Sonst ist die Bude kalt am morgen 😁

Also cool wäre ein Punkt Kamin/Ofen Modus, das man eine Zeit Angeben kann wo er wieder Off geht automatisch, also eine feste Zeit. Nicht er soll jetzt x Stunden bleiben und dann off gehen. Sonder schaltet wieder um XX Ab.

**Comment by dm2302git** [comment]
Als Idee: Ich habe es mit einem mqtt TempFühler am Ofenrohr gelöst. Zudem ein Script über das die Grenztemperatur usw geschaltet wird. Ich schalte ebenfalls bei Temp > X Grad auf den PartyModus um.

**Comment by Newan** [comment]
> Als Idee: Ich habe es mit einem mqtt TempFühler am Ofenrohr gelöst. Zudem ein Script über das die Grenztemperatur usw geschaltet wird. Ich schalte ebenfalls bei Temp > X Grad auf den PartyModus um.

Kannst du mehr zu dem Fühler sagen, interessiert mich sehr!

**Comment by rg-engineering** [comment]
@detafun can we close that issue now?
