### ISSUE TITLE
Temperatur wird bei Wechsel der Periode richtig berechnet aber nicht zum Thermostat übertragen

### ISSUE THREAD

**Issue by detafun** [rg-engineering/ioBroker.heatingcontrol#174]
Hallo
Dachte erst der letzte Prio nur, aber es ist egal. Es wird zwar im VIS die Reglertemperatur die geändert ist angezeigt, aber wird nicht an die CCU übergeben.
Der Temperaturen im Prio , wird zwar übergeben, steht dann auch in den Objekten unter dem Thermostat im HM RPC 0, wird aber wohl nicht abgesendet.
Somit kommt die letzte Temperaturänderung nicht an der CCU an.
Wenn ich in den Objekten eine andere Temperatur manuell eingebe, wird diese auch an die CCU sauber übergeben.

**Comment by rg-engineering** [comment]
was meinst du mit "Letzer Prio"? du meinst, die neue Zieltemperatur wird zwar korrekt berechnet aber erreicht das Thermostat nicht? Das könnte daran liegen, dass ich den Datenpunkt mit Wert und gesetztem ack-Flag schreibe. Dann reagiert hm-rpc wahrscheinlich nicht. Schaue ich mir an...

**Comment by detafun** [comment]
Sorry konnte den Heat nicht mehr ändern.
Also noch mal, die Temperatur wird im Objekt HM RPC zwar geschrieben, aber nicht ausgeführt, als wenn das Enter da fehlt.
![grafik](https://user-images.githubusercontent.com/44980055/103399929-959e3e80-4b43-11eb-9bc6-90978d105c01.png)

Hier ist es der    hm-rpc.0.00129993968020.1.SET_POINT_TEMPERATURE

Dort wird zwar zur Angegeben Timer Zeit dann z.b. 27 Grad eingetragen, aber nicht übertragen an die CPU als wenn das Enter fehlt.

Trage ich aber Manuell von Hand eine andere Temperatur ein und sende diese mit Enter ab, wird diese sofort an die CCU übertragen und geändert.

Ich hab das erst gestern Abend bemerkt, da die Heitzung nach 22 Uhr immer noch voll auf war. Stand 17 Grad drinnen im Set Point aber in der ccu noch 27 Grad.  Ich hab zum Testen sofort mal Manuell 17 Grad eingegeben und versendet und schwupp wars in der CCU auch gändert.

Hoffe du versteht was ich meine.

**Comment by detafun** [comment]
genau, bude war heute früh kalt   :-(

**Comment by detafun** [comment]
yes , funktioniert wieder... Danke
