### ISSUE TITLE
V2 - Windows Open

### ISSUE THREAD

**Issue by detafun** [rg-engineering/ioBroker.heatingcontrol#178]
Windows soll noch offen sein , obwohl es zu ist. Von der CCU kommt es auf jedenfall richtig an
![grafik](https://user-images.githubusercontent.com/44980055/103414502-8b4d6600-4b7e-11eb-822b-4b8e3fecba5a.png)

Aber in der VIS sagt er, das es noch Offen ist. Mh...
Die Anzeige scheint wirkürlich zu sein. Ob offen oder zu.. Da stimmt was nicht.

An der Sensoreintragung hab ich nichts verändert.

![grafik](https://user-images.githubusercontent.com/44980055/103414700-51c92a80-4b7f-11eb-90b5-66a21918a296.png)

**Comment by rg-engineering** [comment]
verwendest du das Sensor-Delay?
![grafik](https://user-images.githubusercontent.com/8238668/103414948-58a46d00-4b80-11eb-9d63-cddc0c356f8a.png)

Welche Anzeige in der vis stimmt nicht? Die Fenster-Status-Liste oder im Raum-Template oder im Raum-Status?

**Comment by detafun** [comment]
Hab ich aktiv. 
![grafik](https://user-images.githubusercontent.com/44980055/103416314-5fce7980-4b86-11eb-9c4c-63029fde1201.png)
im VIS

**Comment by detafun** [comment]
Wenn es deaktiviert ist geht nix. Also wieder an. Mh

**Comment by rg-engineering** [comment]
die Sensoren musst du schon aktiv haben, aber das Delay auf der rechten Seite ist für mich interssant.
Mach bitte mal einen screen shot, welcher Wert im vis nicht stimmt... bei mir funktioniert es (im live System und im Test-System)

**Comment by detafun** [comment]
Also bei mir ist das jetzt so, das nix mehr angezeigt wird Egal wo. Ob Offen oder Zu.

Hier 
![grafik](https://user-images.githubusercontent.com/44980055/103419415-497aea80-4b93-11eb-8329-e0fd60971b3b.png)

Sagt mir es ist jetzt zu, obwohl das Fenster im Wohnzimmer offen ist.

![grafik](https://user-images.githubusercontent.com/44980055/103419462-7deea680-4b93-11eb-8a2f-d0214a1a6c97.png)

Auch hier sagt er zu.
![grafik](https://user-images.githubusercontent.com/44980055/103419488-95c62a80-4b93-11eb-9a0d-565976319cfa.png)

Sensor einstellung ist auch richtig 
![grafik](https://user-images.githubusercontent.com/44980055/103419524-b2faf900-4b93-11eb-984c-bc25d2bb0fc7.png)

**Comment by detafun** [comment]
Gesundes neues Jahr 2021.
Hab noch mal probiert, folgendes;
Fenster auf, passiert nix in der VIS bleibt alles zu.
HeatingControl Adapter neu Start, zeigt er Fenster auf.
Fenster zu, passiert nix, im VIS bleibt das Fenster auf.
Adapter neu Start, zeigt er Fenster zu,

Vielleicht hilft es dir,,,,

**Comment by rg-engineering** [comment]
Wünsche ebenfalls Gesundes Neues Jahr und danke für das Testen hier!

Was du oben schreibst hilft insofern, dass klar ist, dass der Fenstersensor richtig konfiguriert ist. Jetzt ist nur die Frage, warum der Adapter Änderungen von dem Sensor nicht erkennt.

Ich habe eben hier bei mir im live System nochmal probiert, und es funktioniert hier. Ich habe den Adapter im dubug-Modus laufen und sehe folgende logs:

```
Arbeitszimmer ### ChangeStatus Sensor to {"val":true,"ack":true,"ts":1609491743961,"q":0,"from":"system.adapter.hm-rpc.0","user":"system.user.admin","lc":1609491743961} in auto
Change Status WindowOpen in Arbeitszimmer to true
CalculateRoomTemperature for Arbeitszimmer auto
Arbeitszimmer auto mode: target 23

...

### handle state change heatingcontrol.0.Rooms.Arbeitszimmer.WindowIsOpen {"val":true,"ack":false,"ts":1609491744732,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc":1609491744732}
HandleStateChangeGeneral heatingcontrol.0.Rooms.Arbeitszimmer.WindowIsOpen
HandleStateChanges heatingcontrol.0.Rooms.Arbeitszimmer.WindowIsOpen with true refreshVis false
HandleStateChanges WindowIsOpen true
```

Kannst du deinen Adapter auch mal mit debug laufen lassen und dann nach Öffnen des Fensters das log anschauen und hier posten?

**Comment by detafun** [comment]
Moin, hab ich gemacht, passiert nix. Zeigt keine Log Einträge an.
Der Adapter hab ich umgestellt auf debug und neu gestartet
![grafik](https://user-images.githubusercontent.com/44980055/103436556-2ac13600-4c1d-11eb-9e45-ff7d1a586ccb.png)

Aber beim öffnen oder schließen steht nix drinnen im Log unter HeatingControl

**Comment by rg-engineering** [comment]
okay, dann benötige ich wohl doch das ganze log vom start-Vorgang des Adapters... Du kannst das auch per mail an info@rg-engineering.eu senden, wenn du das her nicht posten möchtest...

**Comment by detafun** [comment]
Email raus

**Comment by detafun** [comment]
Fehler wurde behoben durch Update des Adapter noch mal...
