### ISSUE TITLE
V2 - Fehlerhafte Darstellung der Uhrzeiten in DPs und im Log

### ISSUE THREAD

**Issue by MMeinhardt1** [rg-engineering/ioBroker.heatingcontrol#179]
Hallo @rg-engineering,

in den Datenpunkten und auch im Log werden die Uhrzeiten zum Teil nicht richtig dargestellt,

![hc_time](https://user-images.githubusercontent.com/56205459/103445976-a2717e00-4c7a-11eb-942b-f861711325b1.png)

`2021-01-01 19:00:00.010 - warn: heatingcontrol.0 (25757) ChangeStatus fired with [{"room":"Badezimmer","target":18,"currentTimePeriod":4,"ActiveTimeSlot":4,"CurrentTimePeriodTime":"19:0","CurrentTimePeriodFull":"Period 4 19:0"}]`

**Comment by rg-engineering** [comment]
du meinst damit die Darstellung von 19:00 Uhr, oder? dh. anstatt 19:0 sollte 19:00 stehen?

**Comment by MMeinhardt1** [comment]
Ganz genau das meine ich.

**Comment by MMeinhardt1** [comment]
Funktioniert jetzt, Danke.
