### ISSUE TITLE
V2 - VIS Zeigt Feiertag obwohl kein Feiertag

### ISSUE THREAD

**Issue by detafun** [rg-engineering/ioBroker.heatingcontrol#180]
Adapter gerade neu vom Git.

Heute am 2.1. ist kein Feiertag.
Dennoch sagt das VIS es ist Feiertag.
![grafik](https://user-images.githubusercontent.com/44980055/103453596-e052be80-4cdb-11eb-90e7-6228a709e304.png)
![grafik](https://user-images.githubusercontent.com/44980055/103453620-04ae9b00-4cdc-11eb-8512-03efc4fad67a.png)

In dem Feiertags Adapter ist er auch auf false
![grafik](https://user-images.githubusercontent.com/44980055/103453509-0d52a180-4cdb-11eb-9862-83da9493904d.png)

**Comment by rg-engineering** [comment]
ja, sehe es gerade auch bei mir. wollte mich heute sowieso mit dem issue https://github.com/rg-engineering/ioBroker.heatingcontrol/issues/175 beschäftigen....

**Comment by detafun** [comment]
ok , sag bescheid, wenn ich testen kann.

**Comment by rg-engineering** [comment]
aber nach Neustart vom adapter war kein Feiertag mehr, oder?

**Comment by detafun** [comment]
Doch, hab sogar extra noch ein Update vom Git ein Update gemacht. und ist immer noch Feiertag

**Comment by rg-engineering** [comment]
Dann ist das anders als bei mir.
Ich finde bei mir im log um 00:00 Uhr

`heatingcontrol.0 (4054) !!! Statechange not handled feiertage.0.heute.boolean {"val":false,"ack":true,"ts":1609542014989,"q":0,"from":"system.adapter.feiertage.0","user":"system.user.admin","lc":1609542014989}`

Das erklärt, warum nicht wieder zurückgeschaltet wurde. Aber bei Neustart wird der Datenpunkt neu eingelesen und dann passt das.

Du nutzt den kompletten Pfad feiertage.0.heute.boolean und ich habe nur feiertage.0 als Pfad zum Feiertag-Adapter. 

Kannst du in deinem log während der Adapter-Start-Phase mal "start SetCurrent" suchen?
dort sollte etwas wie


```
PublicHolidyToday type ==1 ??? false
PublicHolidyToday set to false
```

stehen, und danch sollte auch noch

`subscribe feiertage.0.heute.boolean
`

vorkommen.

**Comment by detafun** [comment]
Also komisch.
Ich habe ja den Adapter neu vom Git installiert.
Da macht der Adapter ja selber einen neustart ohne zutun.

Nun hatte ich gerade den Adapter Manuell deaktiviert , das Log auf Null gesetzt, damit ich sehen kann was passiert.
Und seit dem ist  KEIN Feiertag mehr.. 

Im Log


heatingcontrol.0 | 2021-01-02 10:31:59.875 | debug | (21472) PublicHolidyToday set to false
-- | -- | -- | --
heatingcontrol.0 | 2021-01-02 10:31:59.873 | debug | (21472) PublicHolidyToday type ==1 ??? false
heatingcontrol.0 | 2021-01-02 10:31:59.821 | debug | (21472) HolidayPresent set to true
heatingcontrol.0 | 2021-01-02 10:31:59.819 | debug | (21472) HolidayPresent type ==1 ??? true
heatingcontrol.0 | 2021-01-02 10:31:59.815 | info | (21472) start SetCurrent
heatingcontrol


Wird der Adapter beim Update nicht komplett deaktiviert und neu gestartet?

**Comment by detafun** [comment]
Nur noch mal zur Info.
Wenn ich in den Objekten, des Feiertagsadapter den Wert heute Feiertag mauell ändere Schaltet die VIS jetzt sauber um.

Die Frage ist aber immer noch, warum? Warum ging es vorher nicht? Es hat sich am Adapter nichts verändert.
Werde es auf jedenfall weiter beobachten, im Moment gibt es ja keine Feiertage mehr. Dauert wieder

**Comment by rg-engineering** [comment]
kannst du mal zeigen, welchen Wert du veränderst, damit der Adapter Feiertag erkennt? Bei mir erkennt er Feiertag nur, wenn ich in der vis vom HeatingControl auf Feiertag schalte:

![grafik](https://user-images.githubusercontent.com/8238668/103455757-de92f600-4cef-11eb-8e9b-bcddeb7c1d14.png)

**Comment by detafun** [comment]
Wenn ich Manuell den Wert hier in den Objekten ändere.
![grafik](https://user-images.githubusercontent.com/44980055/103455825-b8218a80-4cf0-11eb-8d33-4be6f679a4f2.png)

Ich kann auf false klicken und denn Abhacken speichern und dann steht true drinnen. Dann wird sofort der Schalter im VIS auf Feiertag ja gestellt.
Ändere ich den wieder Manuell auf false wieder zurück, geht er sofort wieder auf Feiertag nein.
So wie es jetzt auch sein soll.
Aber ich habe den Punkt
![grafik](https://user-images.githubusercontent.com/44980055/103455855-033b9d80-4cf1-11eb-957c-271aca65bcc2.png)

benutzt-.

**Comment by rg-engineering** [comment]
okay, ist aber nicht ganz real. Das ist der gleiche Test, den ich per javascript gemacht habe. Nur eines hatte ich (wieder) nicht beachtet: die anderen Adapter setzen Werte mit ack=true. Das machst du vermutlich manuell nicht:

![grafik](https://user-images.githubusercontent.com/8238668/103456011-67129600-4cf2-11eb-9686-f7c745fa0d97.png)

Wenn du den bestätigt - Haken setzt, sollte es nicht mehr gehen...

**Comment by detafun** [comment]
Ich hab direkt auf das wort false geklickt, dann macht er das nur so auf:
![grafik](https://user-images.githubusercontent.com/44980055/103456117-83630280-4cf3-11eb-8bbc-0dccb815bddb.png)

Mache ich es wie du, ändert er nicht auf true

**Comment by rg-engineering** [comment]
aber der Wert (true oder false) wird rot? dann ist das ack (=bestätigt) nicht gesetzt und mein Adapter reagiert. Wenn der Wert schwarz dargestellt wird, ist das ack gesetzt, und mein Adapter reagiert nicht.
Ich baue das jetzt mal so um, dass es auch bei anderen DP so funktionert, dann schauen wir mal...

**Comment by detafun** [comment]
Nach meiner Art, wird beim Setzen erst Grün, dann Rot
Genauso anders rum wieder.

**Comment by rg-engineering** [comment]
nein, das passt schon. die Anzeige wechselt erst nach einer Verzögerung auf schwarz (bestätigt) oder rot (also nicht bestätigt). grün bedeutet, der Wert hat sich verändert.

**Comment by detafun** [comment]
ok, sag bescheid wenn du geändert hast und was probieren soll

**Comment by rg-engineering** [comment]
hab das Feiertags-Problem hier und unter #175 (hoffentlich) behoben
