### ISSUE TITLE
V2 - Thermostat behandelt Fenster offen selbst, Adapter soll dieses Verhalten unterstützen

### ISSUE THREAD

**Issue by detafun** [rg-engineering/ioBroker.heatingcontrol#181]
Situation,
bevor, das Fenster auf geht, ist im Status Auto
Fenster auf  ist im Status Manuell  ok
Fenster zu ist weiter im Status Manuell  falsch , müste auf Auto wieder gehen.

![grafik](https://user-images.githubusercontent.com/44980055/103456225-5e22c400-4cf4-11eb-91ee-838af47adcf0.png)

Wenn ich jetzt mal auf das "A" klicke, wird dann Auto wieder angezeigt.

Weiter Fehler:

![grafik](https://user-images.githubusercontent.com/44980055/103456242-88748180-4cf4-11eb-8951-d1d0c2fc53f8.png)

Hier wird auch der Status nicht wieder von Manuell auf Auto aktualliesiert.
Und die Soll Temperatur bleibt bei Fenster Offen 12 Grad in dem Fall obwohl 
das Fenster wieder zu ist und müste eigentlich jetzt wieder  21 Grad anzeigen.

**Comment by rg-engineering** [comment]
ja, das ist ein Fehler, aber anders als du vermutest:
wenn ein Raum im Status "auto" ist und das Fenster geöffnet wird, darf nicht auf manuell gewechselt werden. Der richtige Status hier wäre "auto window open". In diesem Fall würde nach Schliessen des Fensters wieder auf "auto" gewechselt werden und die richtige Zieltemperatur gesetzt werden.

An der Ecke des Codes habe ich lange getüfftelt, anscheinend nicht lange genug... das Problem ist, zu erkennen, ob ein Nutzer am Thermostat dreht oder ob der Thermostat von sich aus aktualisierte Soll-Temperaturen sendet.

Was passiert in deinem Fall (das folgende sind Vermutungen, bitte korrigiere mich)
* du hast folgende Einstellung aktiv
![grafik](https://user-images.githubusercontent.com/8238668/103456424-71cf2a00-4cf6-11eb-9023-217b431c2d74.png)
* dein Thermostat reagiert direkt auf die Fenstersensoren?
* somit folgender (konstruierter) Ablauf:
1) Fenster geht auf
2) Thermostat regelt auf niedrigere Temperatur
3) Thermostat sendet diese Temperatur an den Adapter
4) Adapter interpretiert diese Temperatur als "manuellen" Eingriff und setzt diese Temperatur als Zieltemperatur bis zum nächsten Profilpunkt
5) mit dem A-Knopf schaltest du wieder auf auto, damit sollte egeintlich iweder die Profiltemperatur gesetzt werden 

Ideal wäre nun ein debug log von dem ganzen Vorgang Fentser auf -> Fenster zu -> Auto-Knopf drücken

**Comment by detafun** [comment]
du hast folgende Einstellung aktiv
grafik
dein Thermostat reagiert direkt auf die Fenstersensoren?

JA genau.

Ideal wäre nun ein debug log von dem ganzen Vorgang Fentser auf -> Fenster zu -> Auto-Knopf drücken
Bitte sehr

heatingcontrol.0 | 2021-01-02 13:06:16.499 | warn | (21472) !!! Statechange not handled heatingcontrol.0.Rooms.Wohnzimmer.TemperaturOverride {"val":0,"ack":true,"ts":1609589176492,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin
-- | -- | -- | --
heatingcontrol.0 | 2021-01-02 13:06:16.489 | warn | (21472) !!! Statechange not handled heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod {"val":8,"ack":true,"ts":1609589176471,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin"
heatingcontrol.0 | 2021-01-02 13:06:16.392 | debug | (21472) HandleStateChanges CurrentTimePeriod 8
heatingcontrol.0 | 2021-01-02 13:06:16.392 | debug | (21472) HandleStateChanges heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod with 8 refreshVis false
heatingcontrol.0 | 2021-01-02 13:06:16.391 | debug | (21472) HandleStateChangeGeneral heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod
heatingcontrol.0 | 2021-01-02 13:06:16.390 | debug | (21472) ### handle state change heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod {"val":8,"ack":false,"ts":1609589176383,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","l
heatingcontrol.0 | 2021-01-02 13:06:16.273 | info | (21472) UpdateDPs for Wohnzimmer auto
heatingcontrol.0 | 2021-01-02 13:06:16.272 | info | (21472) HandleActors for Wohnzimmer auto
heatingcontrol.0 | 2021-01-02 13:06:16.271 | debug | (21472) Wohnzimmer nothing to do to for hm-rpc.0.00129993968020.1.SET_POINT_TEMPERATURE , target 23 is already set 23
heatingcontrol.0 | 2021-01-02 13:06:16.268 | info | (21472) SetRoomTemperature started for Wohnzimmer target 23
heatingcontrol.0 | 2021-01-02 13:06:16.267 | debug | (21472) got {"val":12,"ack":false,"ts":1609251032847,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc":1608993970752}
heatingcontrol.0 | 2021-01-02 13:06:16.225 | warn | (21472) !!! Statechange not handled heatingcontrol.0.Rooms.Wohnzimmer.ResetManual {"val":true,"ack":true,"ts":1609589176209,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","l
heatingcontrol.0 | 2021-01-02 13:06:16.212 | debug | (21472) checking min temp with Rooms.Wohnzimmer.MinimumTemperature
heatingcontrol.0 | 2021-01-02 13:06:16.211 | debug | (21472) Wohnzimmer auto mode (incl. reduced): target 23
heatingcontrol.0 | 2021-01-02 13:06:16.210 | debug | (21472) AbsentDecrease got {"val":0,"ack":true,"ts":1609321844271,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc":1609321844271}
heatingcontrol.0 | 2021-01-02 13:06:16.204 | debug | (21472) checking reduced temp with Profiles.1.Wohnzimmer.relative.AbsentDecrease
heatingcontrol.0 | 2021-01-02 13:06:16.203 | debug | (21472) profile 1
heatingcontrol.0 | 2021-01-02 13:06:16.201 | debug | (21472) get current profile
heatingcontrol.0 | 2021-01-02 13:06:16.200 | debug | (21472) Wohnzimmer auto mode: target 23
heatingcontrol.0 | 2021-01-02 13:06:16.200 | info | (21472) CalculateRoomTemperature for Wohnzimmer auto
heatingcontrol.0 | 2021-01-02 13:06:16.199 | debug | (21472) ChangeStatus ResetManual
heatingcontrol.0 | 2021-01-02 13:06:16.198 | info | (21472) Wohnzimmer ### ChangeStatus ResetManual to true in manual
heatingcontrol.0 | 2021-01-02 13:06:16.197 | debug | (21472) HandleStateChangeGeneral heatingcontrol.0.Rooms.Wohnzimmer.ResetManual
heatingcontrol.0 | 2021-01-02 13:06:16.196 | debug | (21472) ### handle state change heatingcontrol.0.Rooms.Wohnzimmer.ResetManual {"val":true,"ack":false,"ts":1609589176190,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":16093626819
heatingcontrol.0 | 2021-01-02 13:05:53.327 | warn | (21472) !!! Statechange not handled heatingcontrol.0.Rooms.Wohnzimmer.TemperaturOverride {"val":0,"ack":true,"ts":1609589153320,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin
heatingcontrol.0 | 2021-01-02 13:05:53.319 | warn | (21472) !!! Statechange not handled heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod {"val":8,"ack":true,"ts":1609589153308,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin"
heatingcontrol.0 | 2021-01-02 13:05:53.303 | debug | (21472) AddStatusToLog skip Wohnzimmer manual holiday at home 12°C
heatingcontrol.0 | 2021-01-02 13:05:53.248 | debug | (21472) HandleStateChanges CurrentTimePeriod 8
heatingcontrol.0 | 2021-01-02 13:05:53.248 | debug | (21472) HandleStateChanges heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod with 8 refreshVis false
heatingcontrol.0 | 2021-01-02 13:05:53.247 | debug | (21472) HandleStateChangeGeneral heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod
heatingcontrol.0 | 2021-01-02 13:05:53.246 | debug | (21472) ### handle state change heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod {"val":8,"ack":false,"ts":1609589153239,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","l
heatingcontrol.0 | 2021-01-02 13:05:53.066 | info | (21472) UpdateDPs for Wohnzimmer manual
heatingcontrol.0 | 2021-01-02 13:05:53.065 | debug | (21472) Change Status target temperature in Wohnzimmer to 23 (profile 23) in manual
heatingcontrol.0 | 2021-01-02 13:05:53.064 | info | (21472) Wohnzimmer ### ChangeStatus Thermostats_Target to {"val":23,"ack":true,"ts":1609589153021,"q":0,"from":"system.adapter.hm-rpc.0","user":"system.user.admin","lc":1609589153021} in manual
heatingcontrol.0 | 2021-01-02 13:05:51.919 | warn | (21472) !!! Statechange not handled heatingcontrol.0.Rooms.Wohnzimmer.WindowIsOpen {"val":false,"ack":true,"ts":1609589151911,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin",
heatingcontrol.0 | 2021-01-02 13:05:51.862 | debug | (21472) CreateWindowStatesTable done
heatingcontrol.0 | 2021-01-02 13:05:51.797 | warn | (21472) !!! Statechange not handled heatingcontrol.0.Rooms.Wohnzimmer.TemperaturOverride {"val":0,"ack":true,"ts":1609589151783,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin
heatingcontrol.0 | 2021-01-02 13:05:51.789 | debug | (21472) CreateWindowStatesTable called
heatingcontrol.0 | 2021-01-02 13:05:51.767 | debug | (21472) Reaching SetWindowState for Rooms.Wohnzimmer.WindowIsOpen
heatingcontrol.0 | 2021-01-02 13:05:51.766 | debug | (21472) HandleStateChanges WindowIsOpen false
heatingcontrol.0 | 2021-01-02 13:05:51.765 | debug | (21472) HandleStateChanges heatingcontrol.0.Rooms.Wohnzimmer.WindowIsOpen with false refreshVis false
heatingcontrol.0 | 2021-01-02 13:05:51.764 | debug | (21472) HandleStateChangeGeneral heatingcontrol.0.Rooms.Wohnzimmer.WindowIsOpen
heatingcontrol.0 | 2021-01-02 13:05:51.763 | debug | (21472) ### handle state change heatingcontrol.0.Rooms.Wohnzimmer.WindowIsOpen {"val":false,"ack":false,"ts":1609589151755,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc
heatingcontrol.0 | 2021-01-02 13:05:51.762 | debug | (21472) AddStatusToLog skip Wohnzimmer manual holiday at home 12°C
heatingcontrol.0 | 2021-01-02 13:05:51.709 | warn | (21472) !!! Statechange not handled heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod {"val":8,"ack":true,"ts":1609589151703,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin"
heatingcontrol.0 | 2021-01-02 13:05:51.680 | debug | (21472) HandleStateChanges CurrentTimePeriod 8
heatingcontrol.0 | 2021-01-02 13:05:51.679 | debug | (21472) HandleStateChanges heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod with 8 refreshVis false
heatingcontrol.0 | 2021-01-02 13:05:51.678 | debug | (21472) HandleStateChangeGeneral heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod
heatingcontrol.0 | 2021-01-02 13:05:51.676 | debug | (21472) ### handle state change heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod {"val":8,"ack":false,"ts":1609589151631,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","l
heatingcontrol.0 | 2021-01-02 13:05:51.522 | info | (21472) UpdateDPs for Wohnzimmer manual
heatingcontrol.0 | 2021-01-02 13:05:51.521 | info | (21472) HandleActors for Wohnzimmer manual
heatingcontrol.0 | 2021-01-02 13:05:51.520 | debug | (21472) Wohnzimmer nothing to do to for hm-rpc.0.00129993968020.1.SET_POINT_TEMPERATURE , target 12 is already set 12
heatingcontrol.0 | 2021-01-02 13:05:51.511 | info | (21472) SetRoomTemperature started for Wohnzimmer target 12
heatingcontrol.0 | 2021-01-02 13:05:51.509 | debug | (21472) got {"val":12,"ack":false,"ts":1609251032847,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc":1608993970752}
heatingcontrol.0 | 2021-01-02 13:05:51.494 | debug | (21472) checking min temp with Rooms.Wohnzimmer.MinimumTemperature
heatingcontrol.0 | 2021-01-02 13:05:51.493 | warn | (21472) Wohnzimmer CalculateRoomTemperature for manual 12
heatingcontrol.0 | 2021-01-02 13:05:51.492 | info | (21472) CalculateRoomTemperature for Wohnzimmer manual
heatingcontrol.0 | 2021-01-02 13:05:51.491 | debug | (21472) Change Status WindowOpen in Wohnzimmer to false
heatingcontrol.0 | 2021-01-02 13:05:51.490 | info | (21472) Wohnzimmer ### ChangeStatus Sensor to false in manual
heatingcontrol.0 | 2021-01-02 13:05:51.488 | debug | (21472) Window close timeout for Wohnzimmer state manual
heatingcontrol.0 | 2021-01-02 13:05:50.487 | info | (21472) sensor close delay 1000 for Wohnzimmer
heatingcontrol.0 | 2021-01-02 13:05:50.486 | debug | (21472) handle sensor manual true 0 1 1
heatingcontrol.0 | 2021-01-02 13:05:43.853 | warn | (21472) !!! Statechange not handled heatingcontrol.0.Rooms.Wohnzimmer.TemperaturOverride {"val":0,"ack":true,"ts":1609589143844,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin
heatingcontrol.0 | 2021-01-02 13:05:43.841 | warn | (21472) !!! Statechange not handled heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod {"val":8,"ack":true,"ts":1609589143830,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin"
heatingcontrol.0 | 2021-01-02 13:05:43.771 | debug | (21472) HandleStateChanges CurrentTimePeriod 8
heatingcontrol.0 | 2021-01-02 13:05:43.770 | debug | (21472) HandleStateChanges heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod with 8 refreshVis false
heatingcontrol.0 | 2021-01-02 13:05:43.769 | debug | (21472) HandleStateChangeGeneral heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod
heatingcontrol.0 | 2021-01-02 13:05:43.768 | debug | (21472) ### handle state change heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod {"val":8,"ack":false,"ts":1609589143760,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","l
heatingcontrol.0 | 2021-01-02 13:05:43.583 | info | (21472) UpdateDPs for Wohnzimmer manual
heatingcontrol.0 | 2021-01-02 13:05:43.582 | info | (21472) HandleActors for Wohnzimmer manual
heatingcontrol.0 | 2021-01-02 13:05:43.581 | debug | (21472) Wohnzimmer nothing to do to for hm-rpc.0.00129993968020.1.SET_POINT_TEMPERATURE , target 12 is already set 12
heatingcontrol.0 | 2021-01-02 13:05:43.578 | info | (21472) SetRoomTemperature started for Wohnzimmer target 12
heatingcontrol.0 | 2021-01-02 13:05:43.577 | debug | (21472) got {"val":12,"ack":false,"ts":1609251032847,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc":1608993970752}
heatingcontrol.0 | 2021-01-02 13:05:43.571 | debug | (21472) checking min temp with Rooms.Wohnzimmer.MinimumTemperature
heatingcontrol.0 | 2021-01-02 13:05:43.569 | debug | (21472) WindowOpenDecrease got {"val":0,"ack":true,"ts":1609321844261,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc":1609321844261}
heatingcontrol.0 | 2021-01-02 13:05:43.489 | debug | (21472) checking reduced temp with Profiles.1.Wohnzimmer.relative.WindowOpenDecrease
heatingcontrol.0 | 2021-01-02 13:05:43.488 | debug | (21472) profile 1
heatingcontrol.0 | 2021-01-02 13:05:43.357 | debug | (21472) get current profile
heatingcontrol.0 | 2021-01-02 13:05:43.356 | warn | (21472) Wohnzimmer CalculateRoomTemperature for manual 12
heatingcontrol.0 | 2021-01-02 13:05:43.355 | info | (21472) CalculateRoomTemperature for Wohnzimmer manual
heatingcontrol.0 | 2021-01-02 13:05:43.353 | debug | (21472) Wohnzimmer manual mode 12
heatingcontrol.0 | 2021-01-02 13:05:43.352 | debug | (21472) Wohnzimmer got target from thermostat until next profil point: 12
heatingcontrol.0 | 2021-01-02 13:05:43.351 | warn | (21472) CheckStartManualMode: current target 23 new 12
heatingcontrol.0 | 2021-01-02 13:05:43.349 | debug | (21472) Change Status target temperature in Wohnzimmer to 12 (profile 23) in auto
heatingcontrol.0 | 2021-01-02 13:05:43.348 | info | (21472) Wohnzimmer ### ChangeStatus Thermostats_Target to {"val":12,"ack":true,"ts":1609589143288,"q":0,"from":"system.adapter.hm-rpc.0","user":"system.user.admin","lc":1609589143288} in auto
heatingcontrol.0 | 2021-01-02 13:05:42.859 | warn | (21472) !!! Statechange not handled heatingcontrol.0.Rooms.Wohnzimmer.WindowIsOpen {"val":true,"ack":true,"ts":1609589142850,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","
heatingcontrol.0 | 2021-01-02 13:05:42.836 | debug | (21472) CreateWindowStatesTable done
heatingcontrol.0 | 2021-01-02 13:05:42.776 | warn | (21472) !!! Statechange not handled heatingcontrol.0.Rooms.Wohnzimmer.TemperaturOverride {"val":0,"ack":true,"ts":1609589142767,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin
heatingcontrol.0 | 2021-01-02 13:05:42.768 | debug | (21472) CreateWindowStatesTable called
heatingcontrol.0 | 2021-01-02 13:05:42.716 | warn | (21472) !!! Statechange not handled heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod {"val":8,"ack":true,"ts":1609589142693,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin"
heatingcontrol.0 | 2021-01-02 13:05:42.707 | debug | (21472) Reaching SetWindowState for Rooms.Wohnzimmer.WindowIsOpen
heatingcontrol.0 | 2021-01-02 13:05:42.706 | debug | (21472) HandleStateChanges WindowIsOpen true
heatingcontrol.0 | 2021-01-02 13:05:42.705 | debug | (21472) HandleStateChanges heatingcontrol.0.Rooms.Wohnzimmer.WindowIsOpen with true refreshVis false
heatingcontrol.0 | 2021-01-02 13:05:42.704 | debug | (21472) HandleStateChangeGeneral heatingcontrol.0.Rooms.Wohnzimmer.WindowIsOpen
heatingcontrol.0 | 2021-01-02 13:05:42.703 | debug | (21472) ### handle state change heatingcontrol.0.Rooms.Wohnzimmer.WindowIsOpen {"val":true,"ack":false,"ts":1609589142693,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc"
heatingcontrol.0 | 2021-01-02 13:05:42.701 | debug | (21472) AddStatusToLog skip Wohnzimmer auto holiday at home 23°C
heatingcontrol.0 | 2021-01-02 13:05:42.636 | debug | (21472) HandleStateChanges CurrentTimePeriod 8
heatingcontrol.0 | 2021-01-02 13:05:42.636 | debug | (21472) HandleStateChanges heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod with 8 refreshVis false
heatingcontrol.0 | 2021-01-02 13:05:42.635 | debug | (21472) HandleStateChangeGeneral heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod
heatingcontrol.0 | 2021-01-02 13:05:42.634 | debug | (21472) ### handle state change heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod {"val":8,"ack":false,"ts":1609589142627,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","l
heatingcontrol.0 | 2021-01-02 13:05:42.523 | info | (21472) UpdateDPs for Wohnzimmer auto
heatingcontrol.0 | 2021-01-02 13:05:42.522 | info | (21472) HandleActors for Wohnzimmer auto
heatingcontrol.0 | 2021-01-02 13:05:42.521 | debug | (21472) Wohnzimmer nothing to do to for hm-rpc.0.00129993968020.1.SET_POINT_TEMPERATURE , target 23 is already set 23
heatingcontrol.0 | 2021-01-02 13:05:42.516 | info | (21472) SetRoomTemperature started for Wohnzimmer target 23
heatingcontrol.0 | 2021-01-02 13:05:42.515 | debug | (21472) got {"val":12,"ack":false,"ts":1609251032847,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc":1608993970752}
heatingcontrol.0 | 2021-01-02 13:05:42.511 | debug | (21472) checking min temp with Rooms.Wohnzimmer.MinimumTemperature
heatingcontrol.0 | 2021-01-02 13:05:42.510 | debug | (21472) Wohnzimmer auto mode (incl. reduced): target 23
heatingcontrol.0 | 2021-01-02 13:05:42.509 | debug | (21472) AbsentDecrease got {"val":0,"ack":true,"ts":1609321844271,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc":1609321844271}
heatingcontrol.0 | 2021-01-02 13:05:42.505 | debug | (21472) checking reduced temp with Profiles.1.Wohnzimmer.relative.AbsentDecrease
heatingcontrol.0 | 2021-01-02 13:05:42.504 | debug | (21472) profile 1
heatingcontrol.0 | 2021-01-02 13:05:42.502 | debug | (21472) get current profile
heatingcontrol.0 | 2021-01-02 13:05:42.501 | debug | (21472) WindowOpenDecrease got {"val":0,"ack":true,"ts":1609321844261,"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc":1609321844261}
heatingcontrol.0 | 2021-01-02 13:05:42.490 | debug | (21472) checking reduced temp with Profiles.1.Wohnzimmer.relative.WindowOpenDecrease
heatingcontrol.0 | 2021-01-02 13:05:42.489 | debug | (21472) profile 1
heatingcontrol.0 | 2021-01-02 13:05:42.470 | debug | (21472) get current profile
heatingcontrol.0 | 2021-01-02 13:05:42.469 | debug | (21472) Wohnzimmer auto mode: target 23
heatingcontrol.0 | 2021-01-02 13:05:42.468 | info | (21472) CalculateRoomTemperature for Wohnzimmer auto
heatingcontrol.0 | 2021-01-02 13:05:42.467 | debug | (21472) Change Status WindowOpen in Wohnzimmer to true
heatingcontrol.0 | 2021-01-02 13:05:42.466 | info | (21472) Wohnzimmer ### ChangeStatus Sensor to true in auto
heatingcontrol.0 | 2021-01-02 13:05:42.464 | debug | (21472) Window open timeout for Wohnzimmer state auto
heatingcontrol.0 | 2021-01-02 13:05:41.463 | info | (21472) sensor open delay 1000 for Wohnzimmer
heatingcontrol.0 | 2021-01-02 13:05:41.462 | debug | (21472) handle sensor auto false 1 1 1

**Comment by rg-engineering** [comment]
das heisst, der Adapter müsste eigentlich gar nicht auf die Fenstersensoren reagieren?

**Comment by detafun** [comment]
Ja ich denke es ggf. je nach dem was vorhanden ist.
Meine Festerkontakte sind ja über die ccu3 verknüpft.
Wie es mit anderen Thermostaten Aussieht weis ich noch nicht. 
Ich habe nur die HM Thermostate und HM Fensterkontakte

**Comment by rg-engineering** [comment]
okay, dann anders herum gefragt: was willst du erreichen?
* Absenkung der Soll-Temperatur, wenn Fenster geöffnet ist -> das wäre, was der Adapter machen würde. braucht es aber nicht, da es deine Thermostate direkt können
* einfache Möglichkeit, die Absenkung pro Raum zu konfigurieren -> kann der Adapter, aber nicht parallel zur Direkt-Verknüpfung 
* Anzeige, ob Fenster offen sind?
* brauchst du den manuellen Modus, d.h. jemand ändert direkt am Thermostat und das bleibt dann bis zum nächsten Profilpunkt?

Mein Problem ist eben, welche Werte vom Thermostat muss der Adapter verarbeiten und welche kann er ignorieren.
Ich könnte z.Bsp. nicht auf manuell schalten, wenn eine neue Ziel-Temperatur vom Thermostat kommt, während ein Fenster offen ist. Das könnte ich mit deinen settings, da Window Open früher erkannt wird, als die neue Zieltemperatur vom Thermostat. Aber mit SensorOpenDelay von mehr als 2 Sekunden würde das schon nicht mehr funktionieren. Dann kommt erst die neue Ziel-Temperatur und dann erst Window Open. Das würde wieder im manuellen Modus enden.

Ich in meinem Fall habe ebenfalls HM Sensoren und Thermostate. Ich habe diese aber nicht direkt verkoppelt. Somit kann der Adapter alles notwendige tun. Aber ich sehe natürlich auch den Vorteil von direkter Kopplung der Sensoren an die Thermostate...

-> Bin mir also noch nicht schlüssig, was ich hier einbauen sollte. Ich packe diese Frage mal in's Forum...

**Comment by detafun** [comment]
Also es sollte:
Status Fenster auf oder zu stehen , je nach dem.
Im Soll Wert sollte, der Wert drinnen stehten von , wie der Regler eingestellt ist.
In meinen Beispiel 
Fenster zu, Reglerwert gem. Zeitplan.
Fenster auf, reglerwert, gem. Fenster auf

z.b.Status: "Fenster auf, Ferien" ,   wenn der Fenster auf ist und Ferien sind.
Status: "Fenster auf, Ferien, Feiertag"   wenn Fenster auf ist, Ferien und Feiertag ist.
Status: "Fenster auf"   Wenn Weder Ferien oder Feiertag ist.
Status: "Auto"    Wenn Fester zu, keine Ferien oder Feitag ist.

Bei Party dito.
Status: "Party, Ferien, Feiertag"
Status: "Party, Feiertag"

Wenn Party ist und jemand das Fenster auf macht.
Status "Party, Fenster Auf, Feiertag, Ferien"

**Ich in meinem Fall habe ebenfalls HM Sensoren und Thermostate. Ich habe diese aber nicht direkt verkoppelt. Somit kann der Adapter alles notwendige tun. Aber ich sehe natürlich auch den Vorteil von direkter Kopplung der Sensoren an die Thermostate...**

Ja vor und Nachteile: Ich denke immer weiter, wenn ioBroker mal nicht funktioniert, erreichbar ist, Steuert die CCU dann es.
Schade, das man den Timer der CCU nicht von Aussen stellen kann. Oder doch? Im HM Adapter geht es ja nicht. Wenn das mahbar wäre, dann hätte man doppelte Absicherung, für den Fall, das ioBroker nicht geht.

**Comment by rg-engineering** [comment]
jetzt nochmal einen Schritt zurück.
oben sagst du:

> dein Thermostat reagiert direkt auf die Fenstersensoren?
> JA genau.

und jetzt

> ich in meinem Fall habe ebenfalls HM Sensoren und Thermostate. Ich habe diese aber **nicht** direkt verkoppelt

Laut log sehe ich aber, dass dein Thermostat 12°C als neue Soll-Temperatur schickt, ohne dass der Adapter etwas zum Thermostat geschickt hat. Das führt zu dem "manual" Zustand. Ich gehe deshalb davon aus, dass dein Thermostat selbständig auf 12°C regelt, wenn ein Fenster auf geht...

**Comment by detafun** [comment]
jetzt nochmal einen Schritt zurück.
oben sagst du:

    dein Thermostat reagiert direkt auf die Fenstersensoren?
    JA genau.

So ist es, Da in der CCU , Thermostat und Fenstersendor verknüpft sind. In der CCU ist auch die 12 Grad eingetragen.
![grafik](https://user-images.githubusercontent.com/44980055/103460222-dd27f480-4d14-11eb-9df9-e4bf262496ed.png)

Wenn Fenster auf Stelle auf 12 Grad, sobald Fenster zu, wieder zurück auf aktuellen Timer



und jetzt

    ich in meinem Fall habe ebenfalls HM Sensoren und Thermostate. Ich habe diese aber nicht direkt verkoppelt

Diese Aussage kommt von dir.

**Comment by rg-engineering** [comment]
ja, okay, dann passt es wieder.
aber mein Problem besteht weiterhin: wie soll ich mit den 12°C umgehen, die mir das Thermostat schickt? als manuelle Änderung übernehmen ist nicht zielführend, da das bis zum nächsten Profil-Punkt oder bis Drücken des Auto-Buttons bestehen bleibt...

**Comment by detafun** [comment]
Was ist, wenn du solange der Status Fenster auf ist, dazu nutzt auf Manuel zu gehen.
Sobald Fenster zu wieder auf Auto.

Denn es wird ja Manuel durch das Fenster eingegriffen.

Und nicht in dem Fall den Status über die gesendete Temperatur abfragen.

**Comment by rg-engineering** [comment]
Ich habe mal versucht, eine Lösung zu bauen:
(da ich keine Thermostate habe, die so eine Direktverknüpfung erlauben, muss ich das Verhalten per script simulieren....)

Im Test sieht es so aus:
![grafik](https://user-images.githubusercontent.com/8238668/103484341-665f2a00-4dee-11eb-8542-0c02e91cfa34.png)

Der Status darf nicht nach "manual" wechseln, sondern muss immer "auto" bleiben. Sobald das Fenster auf geht,
wird der Status auf "auto WindowOpen" gesetzt und die Temperatur vom Thermostat (12°C) übernommen. Wenn das Fenster wieder zu geht, wird wieder alles auf "auto" gesetzt. Der Adapter sollte keine Temperatur an das Thermostat senden, er soll nur anzeigen, was das Thermostat macht


In dem Graph ist
* blau = Ziel-Temperatur
* grün = Ist-Temperatur (simuliert)
* grau = Fenster offen
* rot = Aktor (on oder off) -> ist hier nicht interessant
![grafik](https://user-images.githubusercontent.com/8238668/103484349-74ad4600-4dee-11eb-8ab7-b0f535634bb3.png)


### Wie nutzen?

es gibt eine neue Option:
![grafik](https://user-images.githubusercontent.com/8238668/103484394-d4a3ec80-4dee-11eb-896d-f5e6a4f2e3d2.png)

**Achtung**: SensorOpenDelay muss auf 0 stehen! Wenn das nicht auf 0 steht, funktioniert die Erkennung nicht und der Status wechselt wieder auf "manual" sobald die Temperatur vom Thermostat kommt.

![grafik](https://user-images.githubusercontent.com/8238668/103484417-0452f480-4def-11eb-99a5-cdc45dea5c57.png)

kurze Beschreibung siehe https://github.com/rg-engineering/ioBroker.heatingcontrol#thermostat-handles-window-is-open

**Comment by detafun** [comment]
Fubktioniert noch nicht ganz
Fenster auf, ok
.
Fenster zu teilweise offen noch obwohl zu
![grafik](https://user-images.githubusercontent.com/44980055/103506293-ad840400-4e5c-11eb-973a-ae15355a36e5.png)
Sagt er weiterhin Fenster auf

Bei 
![grafik](https://user-images.githubusercontent.com/44980055/103506347-c5f41e80-4e5c-11eb-8fff-efbaec3d8465.png)

dito im Status, Farbbalken richtig

**Comment by rg-engineering** [comment]
scahu mal mit den letzten Änderungen, sollte nun passen...

**Comment by detafun** [comment]
ok, dann schauen wir mal.
- Update Adapter
- Neustart Adapter Manuell
- Status vor Fenster auf:
- 
![grafik](https://user-images.githubusercontent.com/44980055/103561453-d1c1fe00-4eb9-11eb-89e8-3281878395de.png)
![grafik](https://user-images.githubusercontent.com/44980055/103561536-f4541700-4eb9-11eb-96fc-964a84b5daba.png)

- Status Fenster auf:

![grafik](https://user-images.githubusercontent.com/44980055/103561656-1a79b700-4eba-11eb-91ce-bb7a299e116a.png)
![grafik](https://user-images.githubusercontent.com/44980055/103561691-2796a600-4eba-11eb-98b6-319011c6e7e5.png)

- Status Fenster wieder zu:

![grafik](https://user-images.githubusercontent.com/44980055/103561785-5280fa00-4eba-11eb-896f-754ad76bf343.png)
![grafik](https://user-images.githubusercontent.com/44980055/103561806-60cf1600-4eba-11eb-8567-93b0b598e982.png)

Würde sagen ! Top 100% Funktioniert :-)

**Comment by detafun** [comment]
Close, da funktioniert.
