### ISSUE TITLE
Color inconsistence

### ISSUE THREAD

**Issue by Pittini** [rg-engineering/ioBroker.heatingcontrol#190]
Kann you please correct the colors for the automatically generated tables, so they match color with the other components.
red should be: #f44336
green should be: #4caf50

**Comment by Pittini** [comment]
Ich bin untröstlich, aber ich hab Dir falsche (zu helle) Farben gegeben und etwas nicht bedacht. Neuer Plan, wenn simple vis gewählt wurde, verwende green/red, wenn MaterialDesign Variante gewählt wurde verwende mdui-green/red für Textfarbe und/oder mdui-green/red-bg für Hintergrundfarben.

**Comment by rg-engineering** [comment]
kein Problem, wird prompt erledigt... ;-)

**Comment by rg-engineering** [comment]
sollte dann so aussehen:
![grafik](https://user-images.githubusercontent.com/8238668/104632890-a059e700-569e-11eb-8635-07d2450e73fc.png)

**Comment by Pittini** [comment]
passt.
