### ISSUE TITLE
Missing column "Ist" in Roomstatustable

### ISSUE THREAD

**Issue by Pittini** [rg-engineering/ioBroker.heatingcontrol#192]
At the forum you've shown this:
![1609231105990-room_state_list](https://user-images.githubusercontent.com/51408942/104194478-af803100-5421-11eb-96ca-0229c34f89e7.png)

But atm it looks like this:
![2021-01-11 15_29_30-Window](https://user-images.githubusercontent.com/51408942/104194618-d63e6780-5421-11eb-9bee-a28f7fa3abf9.png)

Theres a column missing, and its not a vis problem, 'cause the column is also missing in generated html:

`<div><table><tr><th> Raum </th><th> Soll </th><th> Fenster </th><th> Status </th></tr><tr><td>Wohnzimmer </td><td style='background-color:green'>22°C </td><td style='background-color:green' > geschlossen </td><td>auto </td></tr><tr><td>Schlafzimmer_C </td><td style='background-color:green'>22°C </td><td style='background-color:green' > geschlossen </td><td>auto </td></tr><tr><td>Bad </td><td style='background-color:red'>22°C </td><td>n/a</td><td>auto </td></tr><tr><td>Werkstatt </td><td style='background-color:red'>22°C </td><td style='background-color:green' > geschlossen </td><td>auto </td></tr><tr><td>Toilette </td><td style='background-color:red'>22°C </td><td style='background-color:green' > geschlossen </td><td>auto </td></tr><tr><td>Dachboden </td><td style='background-color:red'>22°C </td><td>n/a</td><td>auto </td></tr><tr><td>Flur_EG </td><td style='background-color:red'>22°C </td><td style='background-color:green' > geschlossen </td><td>auto </td></tr><tr><td>Kueche </td><td style='background-color:red'>22°C </td><td style='background-color:green' > geschlossen </td><td>auto </td></tr><tr><td>Buero </td><td style='background-color:green'>22°C </td><td style='background-color:green' > geschlossen </td><td>auto </td></tr></table></div>
`

**Comment by rg-engineering** [comment]
"current" = "ist" is only shown when actuators are used. So it's a feature not a bug ;-) The idea behind is that only if actuators are used current OID of thermostat must be filled out, otherwise it's an option.
but I can add that column without conditions...

**Comment by rg-engineering** [comment]
can we close that issue?
