### ISSUE TITLE
No refresh of decreasemode

### ISSUE THREAD

**Issue by Pittini** [rg-engineering/ioBroker.heatingcontrol#193]
Hi,
I've set my decreasemode normally to "relative". This is shown at: _heatingcontrol.0.TemperatureDecreaseMode_
Now I tried to set the decreasemode to "Kein Absenken" because i wanted to know what the value is for "Kein Absenken", i asumed "none", but surprisingly the value dont changed and stayed at "relative".

**Comment by rg-engineering** [comment]
the code is like this:


```
switch (parseInt(parentAdapter.config.TemperatureDecrease)) {
        case 1:
            mode = "relative";
            break;
        case 2:
            mode = "absolute";
            break;
        case 3:
            mode = "none";
            break;
        default:
            mode = "unknown";
            break;
    }
   await parentAdapter.setStateAsync("info.TemperatureDecreaseMode", { ack: true, val: mode });
```
But the path is

`heatingcontrol.0.info.TemperatureDecreaseMode`

and it's called only when adapter starts...
will check again...

**Comment by Pittini** [comment]
> But the path is
> 
> `heatingcontrol.0.info.TemperatureDecreaseMode`

Ok, then i have looked at a relict from an old Version, because i have two of them. Can be closed then.
![Inked2021-01-11 19_43_03-Window_LI](https://user-images.githubusercontent.com/51408942/104224672-99846780-5445-11eb-9435-e7ad9a648ec0.jpg)
