### ISSUE TITLE
Profile benennen

### ISSUE THREAD

**Issue by Pittini** [rg-engineering/ioBroker.heatingcontrol#198]
Hi,
ich hielte es grad für ne leicht integrierbare und der Übersichtlichkeit dienende Idee, wenn man den Profilen noch Namen (im Admin) verpassen könnte, und diese dann auch gleich in "heatingcontrol.0.vis.ProfileValueListText" eingetragen werden würden. Damit können die Leute die Profile dann z.B. passend als "Spätschicht, Frühschicht, etc.) benamen, und es würde auch direkt im Vis anzeigbar sein.

**Comment by rg-engineering** [comment]
einfacher wäre es, die Namen im ObjektBaum einzugeben, d.h. einfach einen neuen Datenpunkt hinzufügen. Wenn ich es im admin mache, kommt wahrscheinlcih gleich die Forderung, den Pfad im Objektbaum auch anzupasssen (also anstatt Profile.1. dann Profil.Küche.) Wie siehst du das?

**Comment by Pittini** [comment]
1. Stellt sich mir dann die Frage wenn im Objektbaum eingegeben, wie kommt das dann in die Auswahlliste ("heatingcontrol.0.vis.ProfileValueListText)?
2. Was passiert wenn der User dort nix eingibt? (Ok, könnte man einfach dann wieder Profil1..2 usw beim erstellen anlegen)
3. Man muß nicht jeder Forderung/Wunsch nachkommen, sähe auch keinen Sinn darin die Struktur zu benamen.

**Comment by rg-engineering** [comment]
>     Stellt sich mir dann die Frage wenn im Objektbaum eingegeben, wie kommt das dann in die Auswahlliste ("heatingcontrol.0.vis.ProfileValueListText)?

das ist kein Poblem, kann ich sogar dynamisch machen. Bei Änderung des Namens eines Profils die Liste aktualisieren...

>     Was passiert wenn der User dort nix eingibt? (Ok, könnte man einfach dann wieder Profil1..2 usw beim erstellen anlegen)

Dann bleibt alles so wie bisher...

Ziel ist doch nur, dass wir im Auswhahlmenü "sprechende" Namen für die Profile anbieten wollen...

**Comment by Pittini** [comment]
> das ist kein Poblem, kann ich sogar dynamisch machen. Bei Änderung des Namens eines Profils die Liste aktualisieren...

Na dann, gekauft :)

**Comment by rg-engineering** [comment]
available in 2.1; can we close that issue now?
