### ISSUE TITLE
Falscher ActiveTimeSlot

### ISSUE THREAD

**Issue by stsch83** [rg-engineering/ioBroker.heatingcontrol#199]
Hallo, ich habe vermehrt das Problem das in einzelnen Räumen (nicht allen) der erste ZeitSlot am Tag nicht richtig eingestellt ist. Ich kann es aktuell aber noch nicht nachvollziehen was die Gründe sind bzw. ist es für mich noch nicht reproduzierbar. Ein Neustart der Instanz hilft. HeatingPeriodActive ein und wieder ausschalten hilft nicht. Der Log zeigt keinen Fehler an.

Version: 1.1.2

zur Info:
Ich habe 2 Instanzen (4 Räume und 12 Räume) eine für die Einliegerwohnung und eine für die Hauptwohnung.
bei mir haben auch vereinzelt Räume mehr als einen Sensor.

**Comment by rg-engineering** [comment]
ein debug log vom Neustart des Adapters (bis "statemachine started") könnte helfen, da dort auch die cron jobs inkl. der dort hinterlegten Daten berechnet und geloggt werden...

**Comment by stsch83** [comment]
> ein debug log vom Neustart des Adapters (bis "statemachine started") könnte helfen, da dort auch die cron jobs inkl. der dort hinterlegten Daten berechnet und geloggt werden...

[2021-01-14 heatingcontrol.0.txt](https://github.com/rg-engineering/ioBroker.heatingcontrol/files/5812709/2021-01-14.heatingcontrol.0.txt)

**Comment by rg-engineering** [comment]
Das ist leider kein debug log, da der Adapter nicht im debug-Mode gestartet wurde.

**Comment by stsch83** [comment]
> Das ist leider kein debug log, da der Adapter nicht im debug-Mode gestartet wurde.

Wie geht das?

**Comment by rg-engineering** [comment]
![grafik](https://user-images.githubusercontent.com/8238668/104601192-392a3b80-567a-11eb-9332-060b1fb58a83.png)

**Comment by stsch83** [comment]
So hier der Log
[2021-01-14 heatingcontrol.0.txt](https://github.com/rg-engineering/ioBroker.heatingcontrol/files/5814878/2021-01-14.heatingcontrol.0.txt)

**Comment by stsch83** [comment]
Das Problem ist heute Morgen wieder aufgetreten, scheint also was systematisches zu sein.
[2021-01-15 heatingcontrol.0.txt](https://github.com/rg-engineering/ioBroker.heatingcontrol/files/5818608/2021-01-15.heatingcontrol.0.txt)

**Comment by rg-engineering** [comment]
was heisst:

> der erste ZeitSlot am Tag nicht richtig eingestellt is

genau?
Zu welchem Zeitpunkt sollte was eingestellt werden, bzw. was ist dann eingestellt? In welchem Raum? Ist nur die Anzeige falsch, oder leigt am Thermostat der falsche Zielwert an? Damit könnte ich das log etwas gezielter durchsuchen...

**Comment by stsch83** [comment]
> was heisst:
> 
> > der erste ZeitSlot am Tag nicht richtig eingestellt is
> 
> genau?
> Zu welchem Zeitpunkt sollte was eingestellt werden, bzw. was ist dann eingestellt? In welchem Raum? Ist nur die Anzeige falsch, oder leigt am Thermostat der falsche Zielwert an? Damit könnte ich das log etwas gezielter durchsuchen...

Ich kann das Problem bis im Raum Küche feststellen, hier sind morgens gegen 6 Uhr 15 Grad eingestellt. Der TimeSlot beginnt aber um 5:30 Uhr. Hier sollte die Temperatur auf 21 Grad gestellt werden.

Wenn ich die Instanz neu starte, dann sind auch die 21 Grad eingestellt.

**Comment by rg-engineering** [comment]
Laut log beginnt der time slot jeden Tag um 05:00Uhr in der Küche, Ausnahme ist Samstag und Sonntag, da geht es um 06:00Uhr los. Ich vermute, in der 1.x Version gbt es ein Problem, wenn zum gleichen Zeitpunkt mehrere Räume ihr Profil umschalten, nachvollziehen kann ich es mit dem vorliegenden log nicht, da um 5:00Uhr debug log nicht aktiviert war.
Ich schlage vor, die Küche wirklich um 5:30 beginnen zu lassen und dann auf das Release der 2.0 vom adapter zu warten. Dort habe ich das Verhalten gründlich überarbeitet und da sollte es dieses Problem nicht mehr geben...

**Comment by stsch83** [comment]
> Laut log beginnt der time slot jeden Tag um 05:00Uhr in der Küche, Ausnahme ist Samstag und Sonntag, da geht es um 06:00Uhr los. Ich vermute, in der 1.x Version gbt es ein Problem, wenn zum gleichen Zeitpunkt mehrere Räume ihr Profil umschalten, nachvollziehen kann ich es mit dem vorliegenden log nicht, da um 5:00Uhr debug log nicht aktiviert war.
> Ich schlage vor, die Küche wirklich um 5:30 beginnen zu lassen und dann auf das Release der 2.0 vom adapter zu warten. Dort habe ich das Verhalten gründlich überarbeitet und da sollte es dieses Problem nicht mehr geben...

Es ist richtig die Küche fängt 5:00 an. Ich probiere es mal und gebe Rückmeldung. Wann kommt denn das Release 2.0?

**Comment by rg-engineering** [comment]
Ich hoffe, dass ich die 2.0.0 am Wochenende in's latest (also beta) bringen kann...
