### ISSUE TITLE
Edit Room: Datenpunkte manuell auswählen bringt Auswahlliste nicht in den Vordergrund

### ISSUE THREAD

**Issue by OstfrieseUnterwegs** [rg-engineering/ioBroker.heatingcontrol#200]
Wenn ich Thermostate manuell zu einem Raum hinzufügen möchte, dann wird das Fenster zur Objektauswahl _*hinter*_ dem Edit Room Fester aufgemacht. Eine Auswahl der Datenpunke für SET und ACTUAL ist also nicht möglich.

V 2.0 - frisch installiert, 1.2 Instanz vorher gelöscht

EDIT: Das scheint nur direkt nach der Installation ein Problem zu sein. Abgespeichert und instanz neu gestartet. Das Problem war behoben. --> low priority

**Comment by rg-engineering** [comment]
eben hier nochmal probiert:

![grafik](https://user-images.githubusercontent.com/8238668/104611549-8bbd2500-5685-11eb-8824-4f5d2d6c733a.png)

**Comment by OstfrieseUnterwegs** [comment]
Ich mach das mal zu - kann ich nicht reproduzieren.
