### ISSUE TITLE
Strange behavior at Window open

### ISSUE THREAD

**Issue by Pittini** [rg-engineering/ioBroker.heatingcontrol#202]
If i open a window, everything is fine. But ca. 10Mins after (if the window is still open) it switches to manu mode without any interaction. You can see it at the Wohnzimmer Log. I see this yesterday evening, and now again. When i close the window, the manual mode stays aktivated, so it stays at 10°C, what is....atm....a little fresh. 

![2021-01-15 12_07_42-vis](https://user-images.githubusercontent.com/51408942/104718249-e066ab80-572a-11eb-9f0e-e0b7b2d9f086.png)

Hier das Log dazu:

```
heatingcontrol.0 | 2021-01-15 12:04:43.219 | info | (2121) HandleActors for Wohnzimmer manual
-- | -- | -- | --
heatingcontrol.0 | 2021-01-15 12:04:43.171 | info | (2121) SetRoomTemperature started for Wohnzimmer target 10
heatingcontrol.0 | 2021-01-15 12:04:43.171 | info | (2121) target 7 lower then minimum 10 : setting to min
heatingcontrol.0 | 2021-01-15 12:04:43.147 | warn | (2121) Wohnzimmer CalculateRoomTemperature for manual 12
heatingcontrol.0 | 2021-01-15 12:04:43.147 | info | (2121) CalculateRoomTemperature for Wohnzimmer manual
heatingcontrol.0 | 2021-01-15 12:04:43.146 | warn | (2121) CheckStartManualMode: current target 15 new 12
heatingcontrol.0 | 2021-01-15 12:00:02.426 | info | (2121) HandleActors for Buero auto
heatingcontrol.0 | 2021-01-15 12:00:02.379 | info | (2121) SetRoomTemperature started for Buero target 20
heatingcontrol.0 | 2021-01-15 12:00:02.247 | info | (2121) CalculateRoomTemperature for Buero auto
heatingcontrol.0 | 2021-01-15 12:00:01.667 | info | (2121) HandleActors for Kueche auto
heatingcontrol.0 | 2021-01-15 12:00:01.618 | info | (2121) SetRoomTemperature started for Kueche target 19
heatingcontrol.0 | 2021-01-15 12:00:01.608 | info | (2121) CalculateRoomTemperature for Kueche auto
heatingcontrol.0 | 2021-01-15 12:00:01.164 | info | (2121) HandleActors for Flur_EG auto
heatingcontrol.0 | 2021-01-15 12:00:01.155 | info | (2121) SetRoomTemperature started for Flur_EG target 20
heatingcontrol.0 | 2021-01-15 12:00:01.052 | info | (2121) CalculateRoomTemperature for Flur_EG auto
heatingcontrol.0 | 2021-01-15 12:00:00.613 | info | (2121) HandleActors for Dachboden auto
heatingcontrol.0 | 2021-01-15 12:00:00.607 | info | (2121) SetRoomTemperature started for Dachboden target 11
heatingcontrol.0 | 2021-01-15 12:00:00.518 | info | (2121) CalculateRoomTemperature for Dachboden auto
heatingcontrol.0 | 2021-01-15 12:00:00.053 | info | (2121) HandleActors for Werkstatt auto
heatingcontrol.0 | 2021-01-15 12:00:00.052 | info | (2121) SetRoomTemperature started for Werkstatt target 20
heatingcontrol.0 | 2021-01-15 12:00:00.017 | info | (2121) CalculateRoomTemperature for Werkstatt auto
heatingcontrol.0 | 2021-01-15 11:55:22.835 | info | (2121) HandleActors for Wohnzimmer auto
heatingcontrol.0 | 2021-01-15 11:55:22.788 | info | (2121) SetRoomTemperature started for Wohnzimmer target 15
heatingcontrol.0 | 2021-01-15 11:55:22.785 | info | (2121) CalculateRoomTemperature for Wohnzimmer auto
heatingcontrol.0 | 2021-01-15 11:55:12.783 | info | (2121) sensor open delay 10000 for Wohnzimmer


```
And here some settings:
![2021-01-15 12_19_30-Window](https://user-images.githubusercontent.com/51408942/104718980-0e98bb00-572c-11eb-907b-254f96f722b8.png)
![2021-01-15 12_19_52-Window](https://user-images.githubusercontent.com/51408942/104718981-0f315180-572c-11eb-9f96-fffa4cd4cc51.png)

**Comment by rg-engineering** [comment]
Das log zeigt was passiert:
Um 12:04 kommt vom Thermostat eine Zieltemperatur von 12°C. Diese ist anders als die vom Adapter gesetzten 15°C, damit geht dieser Raum in "manuell". Da das Fenster offen ist, reduziert der Adapter diese 12°C um 5°C (Fenster Offen Absenkung) und kommt auf 7°C. Da 7°C kleiner als das eingestellte minimum von 10°C ist, wird auf 10°C Zieltemperatur gesetzt.
Der Ausgangspunkt ist aber die Änderung, die vom Thermostat kommt...
Handelt dein Thermostat das "Fenster offen" selbst? Dann wäre die entsprechende Option zu setzen. Das hilft aber wahrscheinlich nicht wirklich, weil der Adapter dem Thermostat nur zwei Sekunden Zeit gibt, das selbst zu handeln... Hier haben wir 10 Minuten dazwischen... Warum schickt also dein Thermostat die 12°C?

**Comment by Pittini** [comment]
Das sind HM-Thermostate HM-CC-RT-DN, also nix exotisches. Und die Fenstersensoren sind Aqara, auch nix besonderes. Ich wüsste nicht dass ich iwo eingestellt hab das die Thermostate was selber machen und sind ja zudem im manu Modus. Könnte aber schon sein dass die Dinger nach 10Minuten merken dasses kalt wird und dann selber runterregeln. Nur...warum erst jetzt, ich hab den Adapter ja schon nen Jahr laufen.

**Comment by Pittini** [comment]
Ok, gefunden, der Adapter kann nix dafür, aber evtl. für Dich interessant falls andere ähnliche Effekte kriegen. Das ganze nennt sich Temperatursturzerkennung und ist wie folgt beschrieben:
![2021-01-15 15_49_58-Window](https://user-images.githubusercontent.com/51408942/104741505-98a34c80-5749-11eb-8514-b65b6aa47660.png)
![2021-01-15 15_50_18-Window](https://user-images.githubusercontent.com/51408942/104741508-993be300-5749-11eb-951f-0022f1b58f95.png)

Ich stell das jetzt mal um und mach dann hier dicht wenns passt.

**Comment by rg-engineering** [comment]
ich habe die 2.x begonnen, weil der Wunsch bestand, Änderungen vom Thermostat mit zu übernehmen. Das habe ich mit der alten Implementierung nicht hinbekommen, deshalb ist das Verhalten in der 2.x komplett überarbeitet. Diesen manuell-Mode habe ich ja auch erst mit 2.x genau aus dem Grund eingeführt. Ich sehe, seitdem ich mich mit der Übernahme der Werte vom Thermostat beschäftige, ständig neues Verhalten der Thermostate. Das macht es extrem schwierig, zu erkennen, wann ein user am Thermostat gedreht hat (und damit der Adapter die Änderung übernehmen muss) oder wann einfach das Thermostat irgendetwas schickt, was ich ignorieren muss...

sehe gerade dein update oben... ja, wie erwartet. Die zweite Funktion kannte ich schon (mit Sensor)
