### ISSUE TITLE
Manuelle Temperatur, beim Fenster schließen

### ISSUE THREAD

**Issue by FI84** [rg-engineering/ioBroker.heatingcontrol#204]
Manuelle Temperatur eingestellt, beim Fenster öffnen wird auch abgesenkt. Dann wird allerdings die Abgesenkte Temperatur Einstellung, als neue manuelle Temperatur genommen.

17.01.2021 19:15:32 manual 5°C
17.01.2021 19:15:25 manual WindowOpen 5°C
17.01.2021 19:15:12 manual 22°C
17.01.2021 19:14:54 auto 20°C
17.01.2021 19:14:50 auto WindowOpen 5°C
17.01.2021 19:14:34 auto 20°C
17.01.2021 19:14:31 starting 20°C

[iobroker.2021-01-17.log](https://github.com/rg-engineering/ioBroker.heatingcontrol/files/5826582/iobroker.2021-01-17.log)

**Comment by rg-engineering** [comment]
ist wahrscheinlich eine Folge von https://github.com/rg-engineering/ioBroker.heatingcontrol/commit/a2ef51c7de941e713fbc9d33232a50cf38f27a8a

**Comment by FI84** [comment]
Die Fenster offen Erkennung im Thermostst ist deaktiviert

**Comment by rg-engineering** [comment]
![grafik](https://user-images.githubusercontent.com/8238668/104949776-ca254d80-59bf-11eb-8e55-5b6c7b822acf.png)

Mit einer kleinen Änderung könnte das nun ebenfalls funktionieren...

* Änderungen der Temperatur im manual - Mode werden übernommen
* bei Reduzierung durch "Window Open" wird reduziert, aber dieser Wert wird nicht übernommen
* bei Schliessen des Fensters wird wieder auf den alten manal-Wert gesetzt.

Nachteil: Änderungen der Temperatur während ein Fenster offen ist, wird nicht in den Adapter übernommen, d.h. bei Schliessen des Fensters wird auf jeden Fall auf den Wert vor Öffnen gesetzt...

**Comment by FI84** [comment]
Eine manuell Änderung der Temperatur ist sehr unwahrscheinlich wenn das Fenster offen ist.

Allerdings bei Einstellung "bis nächsten Profilpunkt" wenn dies grade bei Fenster offen passiert, sollte natürlich der neue Profilpunkt beim Schließen des Fensters eingestellt werden und wieder in Auto Modus gewechselt werden

**Comment by rg-engineering** [comment]
funktioniert das jetzt mit der 2.0.1?

**Comment by FI84** [comment]
Sehr sehr gut. Bin begeistert. Sogar Temperatur Änderung bei offenen Fenster funktioniert.
