### ISSUE TITLE
Copy Buttons für Vis integrieren

### ISSUE THREAD

**Issue by Pittini** [rg-engineering/ioBroker.heatingcontrol#207]
Hi, so wie die Buttons aktuell sind, kann ich das nicht ins Vis übernehmen, würde ich aber gern. Was ich bräuchte wären "dumme" Buttons in der Vis Channelstruktur. Die Logik dahinter müßte vom Adapter kommen, also z.b. Ob der Klick auf den Profil kopieren Button jetzt von 1>2 kopiert oder von 2>3 muß je nach aktuellem gewähltem Profil entschieden werden. Das gleiche gilt auch für die anderen Buttons. Hoffe Du verstehst was ich mein.

**Comment by rg-engineering** [comment]
@Pittini ich werde die DP für die vis so anlegen:
![grafik](https://user-images.githubusercontent.com/8238668/106363598-b4057e80-6329-11eb-9da1-42eae98d9b5b.png)

**Comment by rg-engineering** [comment]
available in 2.2; needs to be tested

**Comment by rg-engineering** [comment]
can we close that issue?

**Comment by Pittini** [comment]
Please let it open until i have it implemeted and tested.

**Comment by Pittini** [comment]
Zested and working. I'll close.
