### ISSUE TITLE
Not all open windows are recognized

### ISSUE THREAD

**Issue by CKMartens** [rg-engineering/ioBroker.heatingcontrol#209]
Since version 2.x all open windows are no longer recognized. I use HM IP twist grip sensors (HmIP-SRH) and HM IP window sensors (HmIP-SWDO) on the windows.

The opening of a window is recognized in the "Kitchen" room, but the second window is not. Rotary handle sensors are built into both.

Log:
```
heatingcontrol.0	2021-01-21 09:38:41.852	debug	(7491) Change Status WindowOpen in Küche to true
heatingcontrol.0	2021-01-21 09:38:41.852	debug	(7491) result for AddSensorState in Küche is true
heatingcontrol.0	2021-01-21 09:38:41.852	debug	(7491) one window open in Küche alias.0.detektoren.kueche.drehgriff_fenster.WINDOWS_STATE
heatingcontrol.0	2021-01-21 09:38:41.852	debug	(7491) add new sensor state in Küche alias.0.detektoren.kueche.drehgriff_fenster.WINDOWS_STATE 1
heatingcontrol.0	2021-01-21 09:38:41.852	debug	(7491) Küche ### ChangeStatus Sensor to {"OID":"alias.0.detektoren.kueche.drehgriff_fenster.WINDOWS_STATE","state":1} in auto

heatingcontrol.0	2021-01-21 09:40:32.164	debug	(7491) ChangeStatus called, while already changing, push to list Küche Sensor {"OID":"alias.0.detektoren.wohnzimmer.drehgriff_terrassentuer.WINDOWS_STATE","state":2} (2)
heatingcontrol.0	2021-01-21 09:40:32.164	debug	(7491) handle sensor auto false 2 0 0
heatingcontrol.0	2021-01-21 09:40:32.164	debug	(7491) ChangeStatus called, while already changing, push to list Wohnzimmer Sensor {"OID":"alias.0.detektoren.wohnzimmer.drehgriff_terrassentuer.WINDOWS_STATE","state":2} (1)
heatingcontrol.0	2021-01-21 09:40:32.164	debug	(7491) handle sensor auto false 2 0 0
heatingcontrol.0	2021-01-21 09:40:32.164	debug	(7491) UpdateDPs for Wohnzimmer auto
heatingcontrol.0	2021-01-21 09:40:32.164	debug	(7491) result for AddSensorState in Wohnzimmer is false
heatingcontrol.0	2021-01-21 09:40:32.164	debug	(7491) add new sensor state in Wohnzimmer alias.0.detektoren.wohnzimmer.drehgriff_terrassentuer.WINDOWS_STATE 2
heatingcontrol.0	2021-01-21 09:40:32.163	debug	(7491) Wohnzimmer ### ChangeStatus Sensor to {"OID":"alias.0.detektoren.wohnzimmer.drehgriff_terrassentuer.WINDOWS_STATE","state":2} in auto
```
![grafik](https://user-images.githubusercontent.com/19702758/105325559-0b3e7d00-5bcd-11eb-9461-702b039b1b5d.png)
![grafik](https://user-images.githubusercontent.com/19702758/105325582-10033100-5bcd-11eb-8d2e-67bb12607994.png)
![grafik](https://user-images.githubusercontent.com/19702758/105325897-64a6ac00-5bcd-11eb-98a7-d0d3d797d5e3.png)
![grafik](https://user-images.githubusercontent.com/19702758/105325909-683a3300-5bcd-11eb-8018-5018b34c26c1.png)

The same problem occurs in the "living room" room. No open window is recognized in the "bedroom" room.

In the "office" room, however, everything is recognized correctly.

My first guess was that the senor designation couldn't cope with spaces, but in the "office" space there are spaces in the designations as well.

**Comment by rg-engineering** [comment]
wurde doch schon hier https://github.com/rg-engineering/ioBroker.heatingcontrol/issues/191 besprochen und sollte mit 2.0.1 erledigt werden.
Für 2.0.1 bitte direkt hier von github installieren wegen https://github.com/rg-engineering/ioBroker.heatingcontrol/issues/208

**Comment by rg-engineering** [comment]
scheint doch ein anderes Problem zu sein.
meldet
`alias.0.detektoren.wohnzimmer.drehgriff_terrassentuer.WINDOWS_STATE`
true/false oder 2?

**Comment by CKMartens** [comment]
Die melden wie alle HM Fenstersensoren 0 für closed und 1 bzw 2 für open bzw tilted

**Comment by rg-engineering** [comment]
deshalb erkennt der Adapter Fenster offen in der Küche (1) aber nicht im Wohnzimmer (2)

bedeutet, geöffnete Fenster werden erkannt, gekippte also nicht...

muss ich umbauen...

**Comment by CKMartens** [comment]
Für die HmIP Drehgriffsensoren gelten 0=closed, 1=tilted und 2=open, für die HmIP Tür-/Fenstersensoiren 0=closed und 1=open. Und es, ich habe es gerade geprüft kippe ich die Fenster nur werden tatsächlich alle erkannt.

**Comment by rg-engineering** [comment]
ich habe die Logik umgedreht, anstatt auf `value==true` frage ich auf` value !=false`.
sollte also mit 2.0.2 dann passen...

**Comment by CKMartens** [comment]
In 2.0.2 behoben. Es funktioniert wie es soll. Ich schließe das Issue.

Danke für Deine Arbeit.
