### ISSUE TITLE
Bei Änderung der Zeittabelle wird cron nicht sofort neu konfiguriert

### ISSUE THREAD

**Issue by rg-engineering** [rg-engineering/ioBroker.heatingcontrol#21]

**Comment by rg-engineering** [comment]
Wenn ich aber die Zeit ändere, muss ich den Adapter neu staretn:
Genauer gesagt: Wenn ich schon in der Period 4 bin, ich die Zeit aber nach hinten verschiebe, aktuell grade von 22:00 Uhr auf 23:00 Uhr, merkt er es nicht. Finde ich nicht so schlimm, aber sieht seltasam aus....

**Comment by rg-engineering** [comment]
@guergen1 die Zeittabelle für cron wird aber sofort neu berechnet, richtig? Einzig die Ziel-Temperatur wird nicht nochmal neu gesetzt?

**Comment by guergen1** [comment]
Bei mir wird grade überhaupt keine Temeratur gesetzt. Die Zeittabelle wird abder nach ein paar Sekunden neu berechnet und passend gemacht!

**Comment by guergen1** [comment]
Nach einem Neustart gibt es nur einen Haufen "device not found heatingcontrol.0.Profiles.0.Toilette.Tue.Periods.2.Temperature"

**Comment by rg-engineering** [comment]
Ich bitte wieder um ein log im debug-Mode. Danke.

**Comment by rg-engineering** [comment]
mit V0.2.3 erledigt
