### ISSUE TITLE
CurrentTimePeriod is out of range

### ISSUE THREAD

**Issue by fastback2000** [rg-engineering/ioBroker.heatingcontrol#210]
The value of field "CurrentTimePeriod" is out of range.
I have max. 6 definitions of period, but the value is "9".

Ate value of CurrentTimePeriodFull has the correct information.

<img width="1230" alt="CurrentTimePeriod_out_of_range" src="https://user-images.githubusercontent.com/59114529/105577551-b5a7d300-5d7a-11eb-90f6-0a4fa5fea952.png">

**Comment by rg-engineering** [comment]
that's no bug it's a feature! you are in 3rd period of Sa-Su. means 6 (=Mo-Fr) plus 3 is 9 ...
We need that value for Pittini vis and there it's correct.

**Comment by fastback2000** [comment]
oh - ok great feature. I will switch from CurrentTimePeriod to ActiveTimeSlot.
THX for the quick support!
