### ISSUE TITLE
ActiveTimeSlot inkorrekt

### ISSUE THREAD

**Issue by Pittini** [rg-engineering/ioBroker.heatingcontrol#212]
Bezugnehmend auf https://github.com/Pittini/iobroker-heatingcontrol-vis/issues/16 scheint es ein Problem zu geben bei Verwendung von weniger als 5 Perioden. Der Adapter zählt zwar korrekt hoch, aber da ist das Problem. Folgendes Szenario, 3 Perioden eingestellt Mo-Fr/SaSo
Active Timeslot zählt unter der Woche täglich brav bis 3. Dann kommt Wochende und die dortige erste Periode welche mit 4 rechnerisch richtig ist, aber vergisst dass das Vis da nicht dynamisch ändert. Die erste Periode des 3ten Blocks ist IMMER die 6 egal wieviele Perioden eingestellt sind.

**Comment by rg-engineering** [comment]
@Pittini Deswegen damals im Forum meine Aussage, dass man das selbst anpassen muss...
Aber so würde das auch funktionieren... baue ich ein...

**Comment by SkeeveKlah** [comment]
Ich habe jeden Tag einzeln, das wären 7 Perioden ?!, klappt trotzdem nicht, zumindest nicht bei „Urlaub Anwesend“ bei manchen Räumen ja, bei manchen nein.
heatingcontrol 2.1.1 vis 3.1.2

**Comment by rg-engineering** [comment]
available in 2.1; can we close that issue now?
