### ISSUE TITLE
TemperaturOverride wird bei Periodenwechsel nicht zurückgestellt

### ISSUE THREAD

**Issue by easybeat** [rg-engineering/ioBroker.heatingcontrol#214]
**Describe the bug**  
Ich habe auf einem Raum die Werte für TemperaturOverride und TemperaturOverrideTime gesetzt und in den Einstellungen die Gültigkeit bis zum nächsten Periodenwechsel definiert. Allerdings bleibt die TemperaturOverride auch nach dem Periodenwechsel bestehen:

![Screenshot 2021-01-28 100043](https://user-images.githubusercontent.com/37217887/106118037-f2e1db80-6153-11eb-9811-d7e4452e46e1.png)

![Screenshot 2021-01-28 100210](https://user-images.githubusercontent.com/37217887/106118030-f1b0ae80-6153-11eb-8f32-339488ed41bb.png)

![Screenshot 2021-01-28 100129](https://user-images.githubusercontent.com/37217887/106118034-f2494500-6153-11eb-8c25-7e16a3598ce6.png)

**To Reproduce**  
Siehe Screenshots

**Expected behavior**  
Nach meinem Verständnis müsste das CurrentTarget um 10.01 wieder auf 19 Grad zurück da der nächste Profilpunkt erreicht wurde.

**Screenshots & Logfiles**  

**Versions:**  
 - Adapter version: 2.03
 - JS-Controller version: 3.1.6
 - Node version: 10.22.1
 - Operating system: Debian auf Proxmox VM

**Additional context**

**Comment by rg-engineering** [comment]
Die Thermostateinstellungen und der Override haben hier keinerlei Zusammenhang!
Der override wird IMMER nur nach Ablauf der Zeit zurückgesetzt. Die Einstellung "bis zum nächsten profilpunkt" bezieht sich auf Änderungen, die vom Thermostat kommen (weil der Nutzer evtl. die Temperatur dort direkt hochdreht)

**Comment by rg-engineering** [comment]
Hat sich das erledigt? Kann ich das issue schliessen?

**Comment by easybeat** [comment]
Danke. Ja hat sich erledigt. Alles klar jetzt.

Und generell: ein sehr hilfreicher Adapter! 

Vielen Dank für die gute Arbeit. Gruss
