### ISSUE TITLE
Fenster offen und der manuelle Modus

### ISSUE THREAD

**Issue by Chuckwallas** [rg-engineering/ioBroker.heatingcontrol#217]
Hallo,
ich muss leider einmal fragen, wie genau das mit dem Fenster offen und dem Vermeiden des manuellen Modus funktioniert.
Ich nutze die Thermostate von Homematic und Aquara Sensoren. Ich hab die Temperatursturzfunktion in der Homematic Zentrale bereits deaktiviert, aber die Thermostate wechseln trotzdem noch in den manuellen Modus. 

Ich komme mit diesem Teil nicht recht klar: "You must enable option "Thermostat handles 'Window is Open'" and you can configure window sensors also in adapter. When window is opened the adapter waits for max. 3 seconds for new target temperature from thermostat. If it receives a new target temperature in that time it will be used as a reduced absolut temperature. Status will then be "auto window open". As soon as the window is closed the status goes back to auto and thermostat sets back the original target temperature Attention do not use Sensor Open Delay in that case. If you use it, the Window open event appears after target temperature received from thermostat. This ends up in manual state."

Wo kann ich im HeatingControl Adapter denn "Thermostat handels window is open" aktivieren? Die Sensoren kann ich im Adapter doch auch nur hinzufügen, aber nicht konfigurieren?
Wenn ich es richtig verstehe, dann darf ich die Öffnungsverzögerung nicht nutzen, da das ganze auch im manuellen Modus endet. Aber wie kann ich dann vermeiden, dass die Heizung bei jedem Öffnen der Balkontür direkt die Temperatur wechselt? 

Sorry, aber ich hab irgendwo einen Denkfehler. Vielen Dank schon mal vorab!

**Comment by rg-engineering** [comment]
![grafik](https://user-images.githubusercontent.com/8238668/107071475-07257880-67e5-11eb-8fb0-8b333ba1f0c2.png)

Mi dieser Option vermeidest du, dass der Adapter in den manual Mode wechselt, wenn das Thermostat selbständig ein Fenster offen erkennt und herunteregelt.
Wenn du aber möchtest, dass der Adapter Fenster offen behandeln soll, musst du als erstes dem Thermostat beibringen, das nicht zu tun... siehe https://github.com/rg-engineering/ioBroker.heatingcontrol/issues/202 (ganz unten)
Dann kannst du auch die Sensor-Verzögerung verwenden. Aber wichtig: das geht nur, wenn das Thermostat nicht selbständig Fenster offen behandelt...

**Comment by Chuckwallas** [comment]
Bei mir sieht das ganze so aus:

![image](https://user-images.githubusercontent.com/62941295/107075986-28896300-67eb-11eb-926d-b424d995661e.png)

Ich hab aber auch die letzte verfügbare Version im ioBroker installiert, hab ich da was falsch gemacht?
Die Einstellung hab ich im Homematic Thermostat schon gesetzt.

**Comment by Chuckwallas** [comment]
ich hab auch diese Funktion zum kopieren von Profilen nicht, ich glaub ich  hab eine falsche Version oder?

**Comment by rg-engineering** [comment]
nein. du bist auf stable (1.1.2?)
Die o.g. features gibt es erst ab der Version 2.x und die ist aber noch im beta-Stadium, aber verfügbar...

**Comment by Chuckwallas** [comment]
Ich hab eben schon gesehen, dass ich das über die Konsole installieren muss, via npm install iobroker.heatingcontrol aber ich bekomms noch nich hin, ich muss noch ein bisschen probieren, bekomm immer "ERR" Meldungen, aber ich bekomm das schon hin :P

**Comment by rg-engineering** [comment]
nein, du musst im iobroker Admin die Verwahrorte auf "beta" stellen. oder du installierst über die "Katze"
![grafik](https://user-images.githubusercontent.com/8238668/107090661-d18e8880-6800-11eb-9432-5731069e3e3e.png)

![grafik](https://user-images.githubusercontent.com/8238668/107090718-e9660c80-6800-11eb-91e9-5127d9e8104d.png)

**Comment by Chuckwallas** [comment]
Also ich hab quasi zwei Möglichkeiten, nur das ich es richtig verstanden habe:

1. Entweder ich nutze die Erkennung des Thermostats, dann muss ich aber die Option "Thermostat behandelt Fenster offen" auswählen, um zu vermeiden das das Thermostat in den Manu-Modus geht. Dann kann ich aber kein Delay nutzen.

2. Ich Deaktiviere die Erkennung des Thermostats und handle das Prozedere über den HeatingControl Adapter, und kann das Delay nutzen. Dann braucht ich aber auch "nur" die aktuelle 1.2 stable Version. 

Ich bevorzuge den zweiten Punkt. Ich möchte aber die Zeitpläne meiner Homematic Zentrale nutzen nutzen. Also habe ich bei den Thermostateinstellungen im Adapter Override "bis zum nächsten Profilpunkt" / "als neue Profileinstellung" gesetzt. Und im Adapter habe ich ein Profil mit einer Periode angelegt, die 23:59 auf 21 Grad setzt, da um Mitternacht ja mein Homematic programm wieder greift. 

Wenn ich das Fenster jetzt offen lasse, geht die Temperatur auf 12 Grad, wie gewünscht. Aber nach dem schließen bleibt das Thermostat im Auto-Modus bei 12 Grad und schaltet nicht zurück auf die Temperatur, die im Homematic Programm gerade hinterlegt ist. Irgendwie hab ich noch einen Denkfehler.

**Comment by rg-engineering** [comment]
> Ich möchte aber die Zeitpläne meiner Homematic Zentrale nutzen nutzen

und was soll dann der Adapter tun? Genau dafür ist doch der Adapter gemacht...

> Aber nach dem schließen bleibt das Thermostat im Auto-Modus bei 12 Grad und schaltet nicht zurück auf die Temperatur, die im Homematic Programm gerade hinterlegt ist. Irgendwie hab ich noch einen Denkfehler.

Wechselt der Raum von "auto" auf "auto WindowOpen" und dann wieder zurück auf "auto"? oder bleibt der Raum die ganze Zeit auf "auto"? Das sieht man im StatusLog des Raumes:

![grafik](https://user-images.githubusercontent.com/8238668/107277550-dba8c500-6a54-11eb-8997-8e52fe7263b6.png)

**Comment by Chuckwallas** [comment]
Ich wollt den Adapter eigentlich nur nutzen, um die xiaomi Sensoren mit dem Fenster nutzen zu können. Ich hab mich halt an die homematic Zentrale gewöhnt. Heißt das ich kann die alten Zeitpläne nicht nutzen? 

Der Adapter wechselt von Auto 20,5 grad, auf auto window open 12 grad und dann wieder auf Auto 12 Grad.

**Comment by Chuckwallas** [comment]
Wenn es von Vorteil ist, und zu weniger Komplikationen fuhrt, stell ich die Perioden mal um, dachte nur ich kann direkt die Zeitpläne weiter nutzen, da auch scripte auf der ccu laufen usw.

**Comment by rg-engineering** [comment]
Du musst auf jeden Fall den Thermostat-Modus ausschalten:

![grafik](https://user-images.githubusercontent.com/8238668/107402804-ae1b5480-6b04-11eb-8178-2c7200a61da6.png)

Andernfalls führt jede Änderung aufgrund der Profile auf der CCU zum manu-Mode...

Bzgl. des Verhaltens mit dem Fenster: Kannst du mir für den zeitbereich "Fentser auf" bis "Fenster wieder zu" ain debug log erstellen?

**Comment by Chuckwallas** [comment]
Hallo,
Wollte nur kurz sagen, das Ich noch nicht dazu kam. Kümmer mich die Tage drum und geb dir Antwort. Vg

**Comment by Chuckwallas** [comment]
Also, sorry das ich mich so lang nicht gezuckt hab. Ich hab jetzt einfach die Profile im Adapter angelegt und es funktioniert natürlich problemlos. Ich werde das denk ich so lassen.
Aber eine Verständnisfrage noch. Wenn ich jetzt manuell am Thermostat drehe, geht das Thermostat dann zum nächsten Profilpunkt vom Manu-Modus in den Auto-Modus zurück, wenn ich ganz normal "bis zum nächsten Profilpunkt" unter override auswähle?

**Comment by Chuckwallas** [comment]
Jetzt hab ich das Problem, dass meine Thermostat im Modus "Auto Absent" stehen und ich weiß nicht warum.
Es müsste doch die vom Heizprofil vorgegebene Temperatur nehmen. 

![image](https://user-images.githubusercontent.com/62941295/109814194-806e8a80-7c2e-11eb-9471-103c494f61cd.png)

**Comment by Chuckwallas** [comment]
Vielleicht mal eine andere Frage, mit der ich jetzt bisschen Probleme hab. 
Ich hab mir in meine lesezeichen zwei links gepackt, um per webrequest den datenpunkt urlaub abwesend zu schalten. 
Wenn ich allerdings Urlaub abwesend wieder auf false schalte, schaltet er den present punkt nicht automatisch wieder auf true. das führt dazu dass der adapter für jeden raum den status auto absent behält. Ich hab mir jetzt ein Makro geschrieben, was beim wechsel den jeweils anderen datenpunkt umschaltet. aber ist das so gedacht?

**Comment by rg-engineering** [comment]
ja, das ist so gedacht. "anwesend / present" ist unabhängig von "Urlaub abwesend / VacationAbsent". Wenn du VacationAbsent veränderst, wird present nicht verändert.
