### ISSUE TITLE
Friday is not Weekend :)

### ISSUE THREAD

**Issue by EdgarM73** [rg-engineering/ioBroker.heatingcontrol#218]
Hallo,

mir ist heute morgen aufgefallen, dass die falsche Zeitperiode grün markiert ist.
Heute ist der 5.2.2021, Freitag, im VIS sieht man allerdings die Wochenendeinstellung grün markiert. Könnte ein Problem mit dem Wochnetag sein.

Die installierte Version ist 2.1.0

![image](https://user-images.githubusercontent.com/4679488/106996980-44a4ea00-6782-11eb-9763-230969feb8fe.png)

grüße
E

**Comment by Pittini** [comment]
Du verwendest welche Adapterversion mit welcher VisProjekt Version?

**Comment by EdgarM73** [comment]
Adapter 2.1.0
vis 3.0.1

**Comment by EdgarM73** [comment]
Ich habe mal das aktuellste Pittini geladen ( 3.1.2 ) und jetzt ist es scheinbar Freitag, aber nach 21:00

![image](https://user-images.githubusercontent.com/4679488/107013170-4d091f00-679a-11eb-9e44-74ad04c62309.png)


Als nächstes lösche ich den gesamten Adapter und installiere neu.

Mal sehen

**Comment by EdgarM73** [comment]
Adapter löchen und neu erstellen hat funktioniert.

Habe ich etwa eine Migrationsanweisung übersehen?

grüße
E

**Comment by Pittini** [comment]
> Habe ich etwa eine Migrationsanweisung übersehen?

Vermutlich. Zumindest am Anfang wars einfach das falsche Vis was Du genommen hattest. Und in der readme steht eigentlich genau drin wie das läuft mit updates bzw. Neuinstallationen. Aber wenns jetzt läuft is ja alles gut und ich mach hier dicht.
