### ISSUE TITLE
 Integration DECT Thermostate

### ISSUE THREAD

**Issue by rg-engineering** [rg-engineering/ioBroker.heatingcontrol#22]
Hi,
ist es Möglich auch die Fritz! bzw. Comet DECT Thermostate zu integrieren?
Wäre super, Danke!

-> issue neu angelegt, da in dem ursprünglichen ein anderes Thema diskutiert wurde...

**Comment by Chaot1** [comment]
Da wäre ich auch sehr stark daran interessiert.

**Comment by rg-engineering** [comment]
workaround (=manuelle Konfiguration) mit 0.1.0 zur Verfügung gestellt...

**Comment by Chaot1** [comment]
Hat sich erledigt.
Mit manueller Konfiguration funktioniert das einwandfrei. Automatische Erkennung muss nicht sein.
