### ISSUE TITLE
Presence per room

### ISSUE THREAD

**Issue by kugelkopf123** [rg-engineering/ioBroker.heatingcontrol#220]
The possibility of controlling the presence of a person per room.

Possible scenarios: A person works irregularly in the home office and at the company. The presence at home is detected and the room is heated normally. If the person is working at the company, the "home office" room does not need to be heated. The other rooms, however, do.

One child is studying and has an irregular schedule of attendance. In the absence, the children's room does not need to be heated. 

This function already existed in the JavaScript from 2 years ago. It worked perfectly. I have missed this function since I switched to HeatingControl. I would monitor the presence/absence via the tr-64 adapter.

A room may have several people who require the room to be heated.
Accordingly, it would have to be checked whether all persons listed for a particular room are absent. If one person is still present, heating must continue. 

This could also be realised quite quickly with an external script, so that only one "presence/absence switch" would be necessary as a data point per room in HeatingControl.
It is necessary that a switch can be selected between modes: general absence (default) or absence per room.

**Comment by rg-engineering** [comment]
Probably you could use a feature which I'll introduced in version 2.2.

see https://github.com/rg-engineering/ioBroker.heatingcontrol/issues/110

**Comment by kugelkopf123** [comment]
Oh! Yes this could be interesting. But what precisely will you add? Individual Profils per room or just disable heating period for specific rooms? Perhaps it also could be possible to use the same code for the linked feature as for my question. With just the difference, that it change the individual absence button for each room in place of the heating period. 
:)

**Comment by rg-engineering** [comment]
no individual profils per room! that might be new feature request for later...
I just added possibility to send any room into state "no heating". Then options for that are used:

![grafik](https://user-images.githubusercontent.com/8238668/107858419-492d6a80-6e34-11eb-960d-1f5b926593a3.png)

**Comment by kugelkopf123** [comment]
I updated to 2.2.0 but cant find the Datapoint. I set it up to Fix Temp per Room. Still no Datapoint. where to find this? And am I right, that i can set a default Temp for this room by deactivate Heatingperiod for this room?

**Comment by rg-engineering** [comment]
DP is here:

![grafik](https://user-images.githubusercontent.com/8238668/107977591-a869b700-6fbb-11eb-8951-b9ebb5567c5b.png)

you can use a fix temperature for all rooms or a dedicated temperature per room...

**Comment by kugelkopf123** [comment]
Great! Thanks for that! =)
