### ISSUE TITLE
CurrentTimePeriod wird nicht geändert bei Urlaub anwesend

### ISSUE THREAD

**Issue by MichaelRoling1310** [rg-engineering/ioBroker.heatingcontrol#221]
Ich habe heute die Version 2.2.0 installiert, hierbei ist mir aufgefallen das die CurrentTimePeriod nicht geändert wird wenn ich Urlaubanwesent aktiviert habe.
Bei Feiertag heute funktioniert es so wie gewünscht.

Jetzt habe ich festgestellt das es doch funktioniert, aber erst wenn der nächste profilpunkt erreicht ist

Vielen Dank

**Comment by rg-engineering** [comment]
geschlossen weil kein weiteres feedback. Bitte neues issue öffnen, falls noch Probleme auftauchen...
