### ISSUE TITLE
Holiday reset problem

### ISSUE THREAD

**Issue by Pittini** [rg-engineering/ioBroker.heatingcontrol#222]
I've installed the newest Version. There are two strange behaviours.

1. Yesterday was Holiday (Aschermittwoch) and the Adapter switched correctly to the Holiday settings. But today it doesnt go back to normal day settings. You can see this in all Logs at the picture.

2. The second thing is, i've enabled the Offset Funktion for testing. Only in the Living Room. Please take a look at the Temp Values, they are really strange (too high). 

![2021-02-18 09_10_58-Window](https://user-images.githubusercontent.com/51408942/108341569-125fa780-71da-11eb-91f4-61649568dfca.png)

**Comment by rg-engineering** [comment]
For first issue: are you sure your DP went back to false? when? Do you still have the log from that time? In debug log I would expect a log like "Change Status PublicHolidyToday in". Codewise I do not see a difference between set of public holiday status and reset of public holiday status. Probably one thing: could it be that your DP was set with ack-bit set? Do you use "Feiertags-Adapter"?
For the second issue I would like to see a debug log if possible.

**Comment by Pittini** [comment]
> For first issue: are you sure your DP went back to false? 

Yes. You can see it also at the Image Card "Globals" > "Feiertag heute" is false.

> when? Do you still have the log from that time? 

Don't know. No.

> Do you use "Feiertags-Adapter"?
Yes

> For the second issue I would like to see a debug log if possible.
Sorry, not possible atm.

**Comment by rg-engineering** [comment]
geschlossen weil kein weiteres feedback. Bitte neues issue öffnen, falls noch Probleme auftauchen...
