### ISSUE TITLE
support different languages for vis

### ISSUE THREAD

**Issue by rg-engineering** [rg-engineering/ioBroker.heatingcontrol#225]
see 
https://github.com/Pittini/iobroker-heatingcontrol-vis/issues/17

might be possible in the same way as we do for admin - pages... but need to check it.
SystemLanguage is already used adapter-internally for date / time formatting... so at least that information is already available...

**Comment by rg-engineering** [comment]
first version implemented in 2.3 for text coming from adapter itself.
vis translation itself still open...

**Comment by rg-engineering** [comment]
@ericsboro for your information...

**Comment by ericsboro** [comment]
@rg-engineering many thanks!

**Comment by rg-engineering** [comment]
@ericsboro @Pittini  I added now different datapoints under heatingcontrol.0.vis.translations with translated text. So this DP can now be used in vis instead of static text.

![grafik](https://user-images.githubusercontent.com/8238668/111866025-bae46100-896a-11eb-952d-06785afb75d7.png)

For translated text there is a new file vis_words.js in lib-folder of adapter. This file can easily be changed to update translations. If changes are done please create a PR so that I can update it here...

**Comment by rg-engineering** [comment]
@ericsboro can we close that issue?

**Comment by ericsboro** [comment]
I believe yes, thanks a ton!
