### ISSUE TITLE
Offset nur bei Temperaturfühler update

### ISSUE THREAD

**Issue by ScumbagSteve** [rg-engineering/ioBroker.heatingcontrol#227]
Ich nutze einen externen Temperaturfühler und hatte nun das Problem, dass dieser für einige Stunden einmal nicht erreichbar war (passiert bei zigbee hin und wieder).

Nun wurde mein offset immer höher gedreht, wodurch die Temperatur im Raum dann immer höher wurde.

Eventuell könnte man eine Prüfung einbauen, dass der offset im Zusammenspiel mit dem externen thermometer nur dann geupdatet wird, wenn seit der letzten Prüfung auch der Datenpunkt zur Temperatur geupdatet wurde.
Somit würde der bestehende offset dann einfach unverändert bleiben, solange ein Gerät nicht erreichbar ist.

**Comment by rg-engineering** [comment]
siehe auch #259
