### ISSUE TITLE
zu viele nicht hilfreiche log Einträge vom typ "info"

### ISSUE THREAD

**Issue by passuff** [rg-engineering/ioBroker.heatingcontrol#229]
Für mein Empfinden ist die Anzahl der Logeinträge vom Adapter unerträglich hoch. Ich würde es begrüßen, wenn die Offsetwerte nicht angezeigt würden. Aktuell sehe ich mindestens zwei mal pro Minute Einträge wie:

TempOffset calc -8.599999999999994 / 51 = -0.25

Diese Information hat für mich (isoliert) keinerlei Mehrwert, da ich sie keinem Raum zuordnen kann.  Daher würde ich dazu tendieren entweder mehr Information oder Verschieben in Typ "Debug".

**Comment by rg-engineering** [comment]
mit 2.4.1 erledigt
