### ISSUE TITLE
Integration Anwesenheitsteuerung und iCal

### ISSUE THREAD

**Issue by CKMartens** [rg-engineering/ioBroker.heatingcontrol#23]
Für eine automatische Steuerung der Temperaturabsenkung i m Falle das niemand zuhause ist, wäre es wünschenswert wenn der State der Anwesentheiterkennung angegeben werden kann.

Auch für eine iCal-Steuerung z.B. als Overide der Temperatur bei Urlaub (um z.B. unter der Woche später die Heizung hoch zu fahren) wäre wünschenswert.

**Comment by rg-engineering** [comment]
solved with 0.3.6
