### ISSUE TITLE
Heizperiode zu Ende, trotzdem wird geheizt

### ISSUE THREAD

**Issue by MMeinhardt1** [rg-engineering/ioBroker.heatingcontrol#231]
Guten Morgen @rg-engineering,

bei mir ist die Heizperiode bis zum 15.04. eingestellt und trotzdem werden die Heizungsthermostate weiterhin angesteuert obwohl dieses Datum bereits überschritten ist.
Hat sonst noch wer dieses „Problem“?

Adapterversion ist die aktuellste.

Gruß Michael

**Comment by rg-engineering** [comment]
siehe https://forum.iobroker.net/topic/22579/test-adapter-heatingcontrol-v2-2-x/2240

**Comment by rg-engineering** [comment]
mit 2.3.2 erledigt

**Comment by MMeinhardt1** [comment]
Super, vielen Dank.
