### ISSUE TITLE
HeatingPeriodActive wird nicht aktualisiert

### ISSUE THREAD

**Issue by Siggi0904** [rg-engineering/ioBroker.heatingcontrol#236]
Hallo,

ich habe die Heizperiode auf 01.10. - 31.04. eingestellt.
Der Datenpunkt heatingcontrol.0.HeatingPeriodActive bleibt aber auf true.
Oder gibt es noch eine zusätzliche Einstellung, die HeatingPeriodActive überschreibt?

Des Weiteren die Frage, wie heatingcontrol.0.Profiles.1.Bad.absolute.AbsentDecrease einzustellen ist?
Wenn ich das richtig sehe gibt es den Datenpunkt AbsentDecrease je Raum und nicht als globale Einstellung.
Hängt AbsentDecrease von heatingcontrol.0.Present ab?

Danke im Voraus.

**Comment by rg-engineering** [comment]
> Der Datenpunkt heatingcontrol.0.HeatingPeriodActive bleibt aber auf true.

Welche Version verwendest du? Dafür gab es in der 3.0.5 einen bug fix: https://github.com/rg-engineering/ioBroker.heatingcontrol/issues/231

Zur anderen Frage: siehe https://github.com/rg-engineering/ioBroker.heatingcontrol#temperature-decrease--increase

**Comment by Siggi0904** [comment]
Hallo, ich bin auf der 2.2.0, da diese im stable die letzte Version ist.
Ich möchte ungern auf latest schalten. Es wäre nett, wenn du eine neue Version in den stable pushen könntest.
Wo gibt es denn eine 3.0.5? Das Changelog geht doch auch nur bis zur 2.3.2.

Wenn ich das bezüglich Temperaturabsenkung bei Abwesenheit richtig lese muss in jedem Raum
heatingcontrol.0.Profiles.1.Bad.absolute.AbsentDecrease mit der Zieltemperatur gesetzt sein.
Wenn man das nicht will, die Temperatur wieder auf 0°C setzen.
Stimmt meine Annahme?

**Comment by rg-engineering** [comment]
ich meinte die 2.3.2 vom 18.04.2021 (sorry). Die kommt wahrscheinlich nächste Woche in's stable...

Bzgl. Absenkung: richtig. Man muss pro Raum, in welchem man bei Abwesenheit absenken will, entweder die absolute Temperatur oder die relative auf den gewünschten Wert setzen. 0 bedeutet in beiden beiden Fällen, keine Absenkung.

**Comment by Siggi0904** [comment]
wo findet man denn die relative Temperatur?
Ich habe nur den Ordner "absolute".

Dann kann ich auch die kommende Version warten.
Wenn der Fehler bekannt und schon repariert ist, ist ja alles gut.

**Comment by rg-engineering** [comment]
> wo findet man denn die relative Temperatur?
> Ich habe nur den Ordner "absolute".
> 

Im admin auf relativ umschalten:

![grafik](https://user-images.githubusercontent.com/8238668/116812970-c45c0e00-ab51-11eb-8431-9dccc8ddb759.png)
