### ISSUE TITLE
Temperatursenkung bei geöffnetem Fenster

### ISSUE THREAD

**Issue by MikeHellracer** [rg-engineering/ioBroker.heatingcontrol#242]
seit einem Update des Adapterlassen sich bei den Fensterkontakten nur 2 Werte für offen und geschlossen angeben. Auch nach Auswahl von Zahl gehen nur noch 2 Werte.
	Meine Kontakte liefern jedoch 0 = geschlossen 1= gekippt und 2 = offen
	dies kann ich leider nicht angeben und das Senken der Temperatur bei geöffnetem Fenster funktioniert nciht mehr

> *created by ioBroker.info*

**Comment by rg-engineering** [comment]
es gab und gibt weiterhin die Unterscheidung offen und geschlossen. Das hat sich auch mit einem update nicht geändert.
Du kannst einfach auf bool stellen und bei geschlossen false und geöffnet true einstellen. 
![grafik](https://user-images.githubusercontent.com/8238668/119697742-d11e0a00-be50-11eb-99cd-7c1edc6a6f59.png)

Der check im Adapter ist folgendermassen implementiert:

`
if (newState != sensor.valueClosed) {
      windowIsOpen = true;
}
else {
       windowIsOpen = false;
}
`

newState = der Wert vom Sensor
sensor.valueClosed = Einstellung aus dem Admin für boolean und FensterGeschlossen

Mit anderen Worten, aus den Einstellungen wird nur "geschlossen / ValueClosed" verwendet und das ist ja bei dir 0 bzw. false...


Wenn das nicht hilft, benötige ich ein debug log für den Vorgang "Fenster öffnen"...

**Comment by rg-engineering** [comment]
@MikeHellracer ist das noch aktuell, oder können wir das hier schliessen?

**Comment by MikeHellracer** [comment]
Sorry, war ein "Fehler 60"
Er saß 60cm vor dem Bildschirm
-> konfigfehler von mir
Danke


rg-engineering ***@***.***> schrieb am Mi., 26. Mai 2021,
18:43:
