### ISSUE TITLE
WindowOpenImg is not defined

### ISSUE THREAD

**Issue by duczz** [rg-engineering/ioBroker.heatingcontrol#244]
V 2.4.0 - Fehler obwohl es hinterlegt ist

![image](https://user-images.githubusercontent.com/25475385/121517813-106f5d80-c9f0-11eb-80dd-b1852e252359.png)
![image](https://user-images.githubusercontent.com/25475385/121517838-17966b80-c9f0-11eb-8260-b44af3a80b5a.png)

**Comment by rg-engineering** [comment]
@duczz kannst du bitte auf debug log umschalten und dann das log nochmal posten?

**Comment by duczz** [comment]
`heatingcontrol.1	2021-06-13 08:35:25.600	info	(22967) start statemachine
heatingcontrol.1	2021-06-13 08:35:25.600	debug	(22967) SetVis done
heatingcontrol.1	2021-06-13 08:35:25.600	error	(22967) exception in SetVis [TypeError: Cannot read property 'val' of null]
heatingcontrol.1	2021-06-13 08:35:25.597	error	(22967) unknown profile typeundefined
heatingcontrol.1	2021-06-13 08:35:25.597	debug	(22967) SetVis called
heatingcontrol.1	2021-06-13 08:35:25.596	debug	(22967) Set trigger done
heatingcontrol.1	2021-06-13 08:35:25.596	error	(22967) unknown profile type undefined
heatingcontrol.1	2021-06-13 08:35:25.596	debug	(22967) Set trigger
heatingcontrol.1	2021-06-13 08:35:25.595	debug	(22967) SetTempDecreaseModeValueLists done
heatingcontrol.1	2021-06-13 08:35:25.546	debug	(22967) SetTempDecreaseModeValueLists called
heatingcontrol.1	2021-06-13 08:35:25.546	debug	(22967) SetProfileValueList done
heatingcontrol.1	2021-06-13 08:35:25.541	debug	(22967) SetProfileValueList 1 1
heatingcontrol.1	2021-06-13 08:35:25.514	debug	(22967) SetProfileValueList called 1
heatingcontrol.1	2021-06-13 08:35:25.513	debug	(22967) InitRoom done, choosen room is Wohnzimmer
heatingcontrol.1	2021-06-13 08:35:25.503	debug	(22967) InitRoom called
heatingcontrol.1	2021-06-13 08:35:25.502	error	(22967) exception in SetData [ReferenceError: WindowOpenImg is not defined]
heatingcontrol.1	2021-06-13 08:35:25.502	debug	(22967) set image path /vis.0/Penthouse/Meine_Icons/HeatingControl/fts_window_1w_open.svg
heatingcontrol.1	2021-06-13 08:35:25.502	info	(22967) 42 cron job(s) created
heatingcontrol.1	2021-06-13 08:35:25.502	debug	(22967) cron status = true next event: 30 Sep 2021 23:55:00`

![image](https://user-images.githubusercontent.com/25475385/121797773-ab4f7e00-cc22-11eb-8f35-c0be0808a430.png)

**Comment by rg-engineering** [comment]
@duczz hast du die 2.4.3 hier aus github schon mal versucht? Ich dachte, dass ich mit commit https://github.com/rg-engineering/ioBroker.heatingcontrol/commit/0edbdb49a7ae69191de2bdefd77b625561208a0c das Problem gelöst hätte?

**Comment by duczz** [comment]
Mein letzter versuch war die 2.4.1, ich bin nun leider auch etwas länger nicht mehr zuhause und kann es deswegen auch nicht zeitnah testen - sorry.
