### ISSUE TITLE
Weiterer Datenpunkt für HomeOffice

### ISSUE THREAD

**Issue by Berchemer** [rg-engineering/ioBroker.heatingcontrol#257]
In den Adaptereinstellungen würde ich einen weiteren Datenpunkt berücksichtigen wollen, welcher sich ähnlich verhalten könnte und vom Adapter gehandhabt wird, wie der für "Feiertag" oder "Urlaub zuhause", jedoch "HomeOffice" oder "TeleArbeit" oder wie auch immer sonst heißen könnte.

Ist eigentlich nur Kleinkram und daher sicherlich nicht die dringlichste Kategorie ;-)

**Comment by rg-engineering** [comment]
Mit den aktuellen Möglichkeiten lässt sich das nicht abbilden?

**Comment by Berchemer** [comment]
Ich meine schon, dass es ein Unterschied ist, ob meine Frau oder ich uns im Urlaub befinden oder im "Home-Office" oder Telearbeit sind. Ggf. habe ich jedoch in den Einstellungen etwas übersehen, was diesem Titel entspricht verwenden kann.

Es geht hauptsächlich darum, dass ich über den ical-Adapter automatisch bestimmte Termine für Urlaub, Krankheit usw. in ioBroker Objekte schreiben lasse und diese dann ggf. auch mit dem HeatingControl-Adapter nutzen möchte.
Und im Kalender ist HomeOffice oder Urlaub schon (mal) ein Unterschied ;-)

**Comment by rg-engineering** [comment]
ich würde das über verschiedene Profile lösen...
