### ISSUE TITLE
Kaminmodus und Javascript-Skript von Pittini

### ISSUE THREAD

**Issue by Michael-Sauer** [rg-engineering/ioBroker.heatingcontrol#258]
Habe in meiner Vis die Einstellungen für den Kaminmodus hinzugefügt. 
Jedoch werden bei der Temperatur Änderung diese nicht in den jeweiligen Räumen übernommen.

Unter den Objekten habe ich gesehen das der Datenpunkt heatingcontrol.0.vis.TempDecreaseValues.FireplaceModeDecrease
nachdem ändern rot bleibt und nicht in den gewählten Raum geschrieben wird.

Auch wird der datenpunkt nicht gelesen wenn ich einen anderen Raum wähle.

Ich denke das hier ein Fehler im JS ist.

**Comment by rg-engineering** [comment]
Du hast den Kaminmodus aktiviert?
![grafik](https://user-images.githubusercontent.com/8238668/134552483-a8988574-7d40-4427-93bb-2fd5faa2b66b.png)

Was sagt das log?

**Comment by Michael-Sauer** [comment]
Ja der Kaminmodus ist aktiviert.
Im Log wird nichts angezeigt.

**Comment by rg-engineering** [comment]
ein paar mehr Informationen benötige ich schon...

bitte mal auf debug log schalten, den Datenpunkt 
`heatingcontrol.0.Profiles.1.room.absolute.FireplaceModeDecrease`
oder
`heatingcontrol.0.Profiles.1.room.relative.FireplaceModeDecrease`
verändern, danach 
`heatingcontrol.0.FireplaceModeActive`
auf true schalten
und das ganze log posten.
Das sollte zunächst funktionieren. Wenn das geht, schauen wir uns das vis-Thema an..

**Comment by rg-engineering** [comment]
kannst du mal die 2.6.1 hier aus githaub testen?

**Comment by Michael-Sauer** [comment]
Geht. Danke.
