### ISSUE TITLE
Target temperature is object null

### ISSUE THREAD

**Issue by Hohenbostler** [rg-engineering/ioBroker.heatingcontrol#261]
Hi aus irgend einem unerklärlichem Grund spuckt der Adapter auf mal einen Fehler in Verbindung mit meinen Tado Thermostaten aus. 

Die Geräte sind natürlich richtig eingerichtet  Im grunde funktioniert es ja .
Ich muss dazu sagen ich habe den Adapter 3x installiert um die Räume einzeln steuern zu können. 

Leider kann ich gerade ein Bild uploaden darum als Link. 
https://ibb.co/NFs1QY2

**Comment by rg-engineering** [comment]
@Hohenbostler ist das noch aktuell oder können wir das schliessen?

**Comment by Hohenbostler** [comment]
Ich habe den Fehler zwar immer noch zwsischendurch weiß aber nicht woher er kommt.
