### ISSUE TITLE
Fenster „schließt“ nicht mehr

### ISSUE THREAD

**Issue by Rich990** [rg-engineering/ioBroker.heatingcontrol#265]
Hallo,
Ich habe heute auf die aktuelle stable Version geupdated. Jetzt habe ich festgestellt, dass die Thermostate ganz normal runtergehen sobald ich ein Fenster öffne. Allerdings wenn ich das Fenster dann wieder schließe bleibt die Temperatur um die eingestellten Grad abgesenkt. Egal welches Delay ich einstelle, die Temperatur bleibt abgesenkt. Weder am Thermostat drehen, noch in eine neue Periode kommen ändert etwas. Der Status bleibt auf „Auto Window Open“ und die Absenkung wird angewandt. Erst durch einen Adapter Neustart wird das Problem behoben.

**Comment by Rich990** [comment]
Ich mache das morgen nochmal und lade dann auch die folgenden. Minuten hoch

**Comment by Rich990** [comment]
ich habe es gestern und heute noch mehrfach probiert und es nicht mehr reproduzieren können. JEtzt läuft es wieder alles wie es soll. Das näcshte mal warte ich zwei Tage und starte das System mal neu bevor ich mich hier melde.
Trotzdem vielen Dank für die Hilfe!

**Comment by Hohenbostler** [comment]
Hi ohne ein Log zur hand zur haben habe ich aber das selbe Problem. Allerdings "glaube ich " wenn zwischen öffnen und Schließen des Fensters ein Profilwechsel dazwischen ist.

**Comment by rg-engineering** [comment]
@slimline33 , @Rich990 gibt es von euch noch etwas neues? Bei mir hier in der Simulation passt es (auch bei Profilwechsel)

**Comment by slimline33** [comment]
Hi @rg-engineering danke für den Reminder. Ich habe keine Profilwechsel bzw nutze ich nur eines im Moment. Mir ist es aufgefallen, sobald 2 Fenster in einem Raum sind, versagt die Fenstererkennung. 

Ich hab das auf dem Schirm und werde einen Log nachliefern!

**Comment by Rich990** [comment]
Sry für die späte Antwort, aber ich habe das Wochenende den Fehler weiter gesucht. Es lag tatsächlich an dem Sensor. Was da genau schief läuft kann ich zwar immer noch nicht beschreiben, denn der gesendete Status passt zu dem was ich haptisch tue, aber es kam immer wieder zu dem Verhalten. Dann habe ich den Sensor getauscht und schon hat es funktioniert. 
vielen Dank für die nützlichen Tipps und Hinweise!

**Comment by slimline33** [comment]
Also bei mir ist der Fehler leider immer noch vorhanden. Ich hatte zwar zwischenzeitlich auch einen dead Sensor, den habe ich aber jetzt nicht mehr in der HC hinterlegt. Die anderen Sensoren funktionieren auf jeden Fall (sehe ich am Pittini Script). Die ganzen Tage hatte ich keine Probleme mehr aber dann ausgerechnet heute wieder ein Fenster nicht geschlossen. Das passiert ständig in den Räumen wo zwei Fenstersensoren hinterlegt sind. Mein Debug Log sieht dann so aus wie der letzte. 

Evtl. könnte es auch an einem anderen Fenster liegen was noch als "geschlossen" erkannt wird, dann aber die weitere Fenstererkennung nicht mehr aktualisiert wird. 

Bitte haltet das Issue offen. Ich versuche es nochmal.

Gruß Christoph

**Comment by rg-engineering** [comment]
Vielleicht hilft ja auch die Datenaufzeichnung per history und Darstellung als flot..
Hier mal ein Beispiel aus meiner Dauer-Simulation:
![grafik](https://user-images.githubusercontent.com/8238668/140571055-d5ce40cb-4ffc-4629-9aa1-904080b20007.png)

**Comment by slimline33** [comment]
Puh. Ich denke ich werde die Erkennungszeit mal runterschrauben. Dann geht das einfacher für mich und ich könnte evtl. auch den Fehler leichter eingrenzen. Ich versuche nochmal mein Glück!

**Comment by rg-engineering** [comment]
@slimline33 gibt es hier neue Erkenntnisse oder kann ich das issue schliessen?

**Comment by slimline33** [comment]
Hehe ja jetzt wo du es sagst 😬 defekte Sensoren habe ich keine und es passiert nicht jedes mal. Aber immer bei den Räumen wo es zwei Fenster gibt.

Meine Lösung soweit : Ich starte die Instanz neu sobald das letzte Fenster geschlossen wurde.

**Comment by rg-engineering** [comment]
hast du mal versucht, die Daten per history aufzuzeichnen? was passiert, wenn du die delays auf wenige Sekunden reduzierst?

**Comment by Hohenbostler** [comment]
> Hehe ja jetzt wo du es sagst 😬 defekte Sensoren habe ich keine und es passiert nicht jedes mal. Aber immer bei den Räumen wo es zwei Fenster gibt.
> 
> Meine Lösung soweit : Ich starte die Instanz neu sobald das letzte Fenster geschlossen wurde.

Ich starte meine Instanzen stündlich neu damit geht es auch als Übergangslösung. Schön ist es aber nicht so richtig

**Comment by rg-engineering** [comment]
In #305 sieht es so aus, als ob die zyklische Statusinformation des Sensors den Timer killed. Ich baue den Adapter bzgl. der Timer nochmal um. Jeder Sensor bekommt nun seinen eigenen timer... und die zyklischen Statusupdates ignoriere ich...

**Comment by rg-engineering** [comment]
sollte mit 2.8.6 behoben sein...

**Comment by slimline33** [comment]
Sehr schön. Dann deaktiviere ich mal den Neustart und werde das beobachten! Vielen Dank
