### ISSUE TITLE
Version 2.6.2 triggert nicht auf Änderungen am Thermostat

### ISSUE THREAD

**Issue by Hohenbostler** [rg-engineering/ioBroker.heatingcontrol#268]
Hallo, 

ich nutze den Heatingcontrol Adapter in Verbidung mit Tado. Das System ist so eingestellt das wenn ich entweder in der Tado App oder am Thermostat die Temperatur änder der Adapter in den Override für eine Stunde gehen soll. IN dieser Version klappt das aber anscheinend nicht mehr sprich der neue Wert der vom Tado setting Datenpunkt kommt wird nicht übernommen als neuer Override.

**Comment by Hohenbostler** [comment]
Hallo ob ich von der 2.5 komme weiß ich nicht genau. Aber ja bin im stable unterwegs. 
So noch kurz was ich gemacht habe : 
Heatingadapter aus . auf Debug gestellt dann adapter gestartet.
Im Wohnzimmer 19,5 ° eingestellt . Dies wurde als Override auch erkannt.
1-2 Minuten später das Wohnzimmer auf 20,5° gestellt. Damit wurde der Override aber nicht überschrieben.

Anbei die log Datei
[heatingcontrol.log](https://github.com/rg-engineering/ioBroker.heatingcontrol/files/7381133/heatingcontrol.log)

**Comment by rg-engineering** [comment]
Habe das log hier gelöscht, da persönliche Daten beinhaltet waren... Lösche es auch bei mir, wenn ich es nicht mehr benötige...
