### ISSUE TITLE
Erweitertes Sensorhandling

### ISSUE THREAD

**Issue by mwolff65** [rg-engineering/ioBroker.heatingcontrol#270]
Ich benutze an einigen Fenstern einen Homematic IP Smart Home Fenstergriffsensor HmIP-SRH. Der kann 3 Zustände liefern. 0 = zu 1= offen und 3 = gekippt. Nun würde ich auch gerne den Gekippt Zustand anders handeln (Rolladen nur ein Stück öffnen) 
Es wäre schön, wenn das als Erweiterung dazu kommen könnte. 
Sonst Gute Arbeit und vielen Dank dafür!

**Comment by Pittini** [comment]
Das ist komplexer als man denkt (weil die Zahlen bei verschiedenen Geräten, verschiedene Bedeutungen haben. Und wo is bei Deinem Beispiel eigentlich die 2?) und für ne Heizungssteuerung auch gar nicht nötig imho. Abgesehen davon kannste doch mit dem originalen Datenpunkt arbeiten um Deine Rolladen zu fahren. Wennste, warum auch immer, das als Auswertung brauchst, könnte Dir das evtl. helfen: https://github.com/Pittini/iobroker-Fensterauswertung

**Comment by rg-engineering** [comment]
> In der Heizungssteuerung arbeitet das soweit korrekt, da scheinbar (zum Glück) auf nicht 0 (false) geprüft wird und damit wird auch bei Kippstellung 2 das Fenster als geöffnet gemeldet.  

das hatte ich ganz bewusst genau für diesen Fall so vorgesehen ;-)

> Nur schaltet es noch nicht wieder zurück wenn ich das Fenster schliesse

Wenn "Fenster auf" erkannt wurde, sollte eigentlich auch "Fenster zu" erkannnt werden. Vielleicht mal auf debug schalten, in dem log sieht man viel (ich kann da auch mal schauen)

Das issue hier können wir aber schliessen, oder?

**Comment by mwolff65** [comment]
Hallo Pittini,

ja, das issue kann geschlossen werden. Mit dem log schau ich noch mal, komme gerade nicht dazu .. :-[]


Liebe Grüße

Marcus 

Von: rg-engineering
Gesendet: Montag, 1. November 2021 19:18
An: rg-engineering/ioBroker.heatingcontrol
Cc: mwolff65; Author
Betreff: Re: [rg-engineering/ioBroker.heatingcontrol] ErweitertesSensorhandling (Issue #270)

In der Heizungssteuerung arbeitet das soweit korrekt, da scheinbar (zum Glück) auf nicht 0 (false) geprüft wird und damit wird auch bei Kippstellung 2 das Fenster als geöffnet gemeldet.
das hatte ich ganz bewusst genau für diesen Fall so vorgesehen ;-)
Nur schaltet es noch nicht wieder zurück wenn ich das Fenster schliesse
Wenn "Fenster auf" erkannt wurde, sollte eigentlich auch "Fenster zu" erkannnt werden. Vielleicht mal auf debug schalten, in dem log sieht man viel (ich kann da auch mal schauen)
Das issue hier können wir aber schliessen, oder?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
