### ISSUE TITLE
Temperatur lässt sich nicht manuell in den Objekten ändern

### ISSUE THREAD

**Issue by MiRo1310** [rg-engineering/ioBroker.heatingcontrol#271]
Temperatur lässt sich nicht manuell in den Objekten für HMIP Thermostate ändern. Wenn ich den HeatingControl Adapter stoppe geht es. (Admin Version 5.1.25, HMIP Version 1.13.1, HeatingControl 2.6.2, aber auch 2.4.3 habe ich getestet.)
Über die Vis geht es.
Es geht darum mit Alexa die Temperatur dann ein zu stellen.
Lg Michael

**Comment by rg-engineering** [comment]
Kannst du mal genau erklären, wo du manuell die Temperatur ändern möchtest? welcher Datenpunkt?

**Comment by MichaelRoling1310** [comment]
Hallo,

ja natürlich. Direkt im HMIP Adapter
hmip.0.devices.3014F711A000201A49A55C45.channels.1.setPointTemperature
und das bei jedem Thermostat
Danke

**Comment by rg-engineering** [comment]
das müsste ja dann ähnlich funktionieren, als wäre die Änderung am Thermostat direkt erfolgt. Wie sehen deine Einstellungen hier aus? 
![grafik](https://user-images.githubusercontent.com/8238668/140394553-c2d17922-a1a1-4d3e-b52b-8235d048c49d.png)

Was passiert, wenn du Änderungen auf dem o.g. Datenpunkt machst? Hast du dafür ein debug log?

**Comment by MichaelRoling1310** [comment]
![Screenshot (51)](https://user-images.githubusercontent.com/68854794/140463758-21b61c52-9c26-4fc0-8938-1fcb54eac4ea.png)
![Screenshot (49)](https://user-images.githubusercontent.com/68854794/140463831-0d4769d8-d204-4dde-be97-1ec132da0347.png)

**Comment by mkshb** [comment]
Moin,

selbes Problem mit der 2.7.2.
Sobald ich "Verwendung von Änderungen vom Thermostat" auf "als Override" einstelle lässt sich die Temperatur an den weder an den Aktoren noch an den Objekten ändern. Mit "bis zum nächsten Profilpunkt" geht es.

**Comment by rg-engineering** [comment]
@MichaelRoling1310 ein debug log vom HeatingControl-Adapter wäre ebenfalls hilfreich. Das log vom hmip sagt ja, dass die Zieltemperatur von 23°C nicht gesendet wird, weil es keine Änderung gab.
![grafik](https://user-images.githubusercontent.com/8238668/141171712-304aab7c-5118-4fa5-9f8c-657ccb4c9b34.png)

@mkshb  hast du ein debug log vom HeatingControl-Adapter für den Fall? 

Wird die Änderung vom Adapter wieder überschrieben oder lässt sich gar kein Wert eingeben? oder schreibt der hmip die Daten einfach nicht weiter (wie im o.g. log zu sehen)

**Comment by mkshb** [comment]
Moin, 

ich habe meinen Fehler mittlerweile gefunden und gelöst. 
Für die Nachwelt: Ich habe für den betreffenden Raum in den Geräteeinstellungen versehentlich ein zweites (nicht vorhandenes) Thermostat mit leeren Datenpunkten angelegt. Dadurch hat der Adapter die Overridetemperatur nicht setzen können.

**Comment by MichaelRoling1310** [comment]
![Screenshot (60)](https://user-images.githubusercontent.com/68854794/141495668-a4114776-c658-43c6-a749-54ec7c5c4365.png)

**Comment by rg-engineering** [comment]
@MichaelRoling1310 ein wenig mehr info würde nicht schaden... Was versuchst du hier zu tun?
Meine Interpretation:
* du setzt im Raum "Keller Michael"  die Temperatur auf 21°C
* der Adapter merkt das und wechselt in "manual, 21°C"
* dann setzt du nochmal auf 21°C
* hmip-Adapter merkt, das nichts zu tun ist und macht auch nichts
* dann setzt du auf 22°C
* der Wert wird geschrieben und auch der Adapter merkt das und setzt auf "manual, 22°C"

Aus meiner Sicht ist soweit kein Fehler erkennbar...

**Comment by MichaelRoling1310** [comment]
Ich kann nur sagen das wenn ich den Wert in hmip für das Thermostat ändere , die Änderung nicht an das Thermostat gesendet wird. 
Was für Infos können denn noch helfen?

**Comment by rg-engineering** [comment]
aus meiner Sicht macht der HeatingControl-Adapter alles richtig. Auf das Thermostat schreibt der [hmip](https://github.com/iobroker-community-adapters/ioBroker.hmip). Vielleicht dort mal ein issue aufmachen und nachfragen, welche Ursachen es gibt?

**Comment by MichaelRoling1310** [comment]
Grundsätzlich würde ich sagen das du recht hast, aber wenn ich den heatingcontrol Adapter deaktiviere funktioniert alles wie gewünscht.

**Comment by rg-engineering** [comment]
ist meine Annahme von oben bzgl. des logs richtig, oder hast du etwas anderes gemacht? stimmt das mit den Temperaturen? Was hast du konkret am Thermostat beobachtet? Welchen Wechsel von 19°C auf 21°C und dann auf 22°C gab es am Thermostat?

**Comment by MichaelRoling1310** [comment]
Am Thermostat passiert garnichts. Egal welcher Wert eingestellt wird.

**Comment by rg-engineering** [comment]
Aber die Temperaturen, die vom Adapter laut Profil angefahren werden sollen, werden zum Thermostat gesendet?

**Comment by MichaelRoling1310** [comment]
Ja genau die Temperaturen aus dem heatingcontrol Profil werden übermittelt. 
aber komischerweise auch Temperaturen die ich per vis auf diesen datenpunkt sende. 
Das Problem habe ich in der iobroker Facebook Gruppe gepostet. 
Mir ist das ganze aufgefallen, da ich bis vor einer gewissen Zeit noch per Alexa die Temperatur ändern konnte. Das geht aber auch nicht mehr.

**Comment by rg-engineering** [comment]
> Das Problem habe ich in der iobroker Facebook Gruppe gepostet.

hab's jetzt auch dort gefunden, aber viel feedback kam da auch nicht, aber vielleicht war da der Hinweis dabei: Änderungen am DP bestätigt mein Adapter, d.h. er setzt das ack-Flag. Wenn der hmip langsamer reagiert, und er auch nur auf unbestätigt reagiert, erklärt das das Problem. Wie wir das lösen, weiß ich nicht noch nicht, da der Adapter ja nicht weiß, woher die Änderungen kommen...

**Comment by rg-engineering** [comment]
in der 2.8.1 versuche ich mal, das ack zeitlich zu verzögern, so dass andere Adapter die chance haben, auf un-acked zu reagieren...

**Comment by rg-engineering** [comment]
sollte jetzt mit der 2.8.1 erledigt sein. Über ein Feedback wäre ich dankbar...

**Comment by MiRo1310** [comment]
@rg-engineering Vielen Dank für dein Bemühen. Aber leider ist es immer noch das gleiche wie vorher. 
Ich habe nochmals den heatingcontrol Adapter gestoppt. Dann geht es wieder.

**Comment by rg-engineering** [comment]
@MiRo1310 
 > Der HMIP hat garkeine Zeit um den Wert zu übermitteln?

kannst du eine Version von github installieren? Wenn ja, baue ich dir mal testweise eine Version, die das ack gar nciht setzt. Nur um zu sehen, ob es so funktionieren würde...

**Comment by rg-engineering** [comment]
sollte mit der 2.8.2 jetzt endgültig erledigt sein...
