### ISSUE TITLE
Änderungen nach Profilwechsel ( ? )  triggert nicht immer

### ISSUE THREAD

**Issue by Hohenbostler** [rg-engineering/ioBroker.heatingcontrol#272]
Hi zusammen. 

Ich hatte schon mal in einem anderen Bug gepostet doch ich mache dazu jetzt nochmal ein Ticket auf, evtl kannst du mir da auch weiter helfen da das Problem nicht immer auftritt. 

Kurz das was ich festelle. 

Ganz oft ( aber eben nicht immer ) kommt es eben vor das Fenster zu oder abgelaufene Timer nicht getriggert werden und entsprechend die Temperatur gar nicht geändert wird. 

Ich habe die Vermutung das es immer dann zu Problemen kommt wenn zwischen den Problemen Profiländerungen kommt. 

Achso das wichtigste. Wenn ich mit bekomme das irgendwas nicht geändert wurde starte ich einfach nur die Instanz neu und sofort wird es so eingestellt wie es sein soll.

Ich habe eigentlich ganz simpel nur 2 Profile. 

ab 5:30 Uhr 22°
ab 21:30 Uhr 19 °

Dazu noch Fenster offen erkennung und änderungen am Thermostat als Override für 1 Std. 

Jetzt wollte ich das heute morgen das versuchen einmal nach zustellen. Also die Instanz auf Debug

Uhrzeit 7:20 Uhr
Änderungen:
Profilzeit 2 auf 7:30 
Fenster auf
Profiländerung abgewartet Fenster geschlossen. 

Natürlich hat es dann funktioniert , aber evtl hast du eine Idee ob es dort zu Problemen kommen kann ?

Evtl noch wichtig -> Ich habe 3 Instanzen laufen damit ich die Räume entsprechend einzeln ansteuern kann.

**Comment by Hohenbostler** [comment]
Ok also anscheinend kommt es doch nicht mit dem Profil Wechsel. Das system springt einfach nicht wieder in den Automodus. Jetzt hat ich ein override der auf 60 min steht und selbst nach 2 Std steht der Modus noch auf override.

**Comment by rg-engineering** [comment]
hast du ein debug log von dem Vorgang?
Ich kann das Problem hier leider nicht nachvollziehen ...

**Comment by Hohenbostler** [comment]
> hast du ein debug log von dem Vorgang? Ich kann das Problem hier leider nicht nachvollziehen ...

Moin klar ich hoffe das ich so ausreichend. Override auf 3 minuten gestellt. 
[iobroker.log](https://github.com/rg-engineering/ioBroker.heatingcontrol/files/7494726/iobroker.log)

**Comment by rg-engineering** [comment]
ja, ich denke ich sehe das Problem im log:
dein Thermostat schickt alle 30 - 40 Sekunden den aktuellen Zielwert (also 25°C). das triggert jedesmal den Neu-Start vom Override ...

**Comment by Hohenbostler** [comment]
OK ja das kann gut sein. Aber wieso läuft denn trotzdem der Countdown auf 0

**Comment by rg-engineering** [comment]
der countdown ist in Minuten, also bei 59 Sek. zeigt er schon 0 an und dann wird er wieder neu gestartet...
und ja, du änderst zwar die Temperatur nicht, aber der Adapter bekommt ein update gesendet.
Ich muss also schauen, wie ich den Timer nicht neu starte, wenn keine Temperaturänderung gemeldet wurde und trotzdem die anderen Feature nicht beeinflusse... im code sehe ich, dass ich genau an der Stelle schon andere issues hatte...

**Comment by Hohenbostler** [comment]
OK aber das Problem bestand mit älteren Version doch nicht oder ? 
Kannst du nicht die Override temp irgendwie irgendwo mit abspeichern und den override nur neu starten wenn die beiden Werte sich unterscheiden ?

**Comment by rg-engineering** [comment]
so ähnlich wird die Lösung aussehen...

**Comment by rg-engineering** [comment]
wenn vom Thermostat dann noch die reduzierte Temperatur bei "Fenster offen" zurückkommt, muss ich diese Meldung ebenfalls ignorieren. Andernfalls nehme ich dann das als neue Override-Zieltemperatur und schalte nicht zurück, wenn das Fenster wieder zu ist...
Das führt aber dazu, dass man die Temperatur am Thermostat nicht mehr ändern kann, wenn das Fenster offen ist...

**Comment by Hohenbostler** [comment]
Für mich wäre das ok weil in meinen Augen immer das offene Fenster gewinnen muss.

**Comment by rg-engineering** [comment]
@Hohenbostler ist das noch aktuell? wenn ja, schau mal bitte, ob der Haken bei dir gesetzt ist. Wenn ja, bitte mal entfernen und nochmal prüfen... Danke.

![grafik](https://user-images.githubusercontent.com/8238668/147272405-4067dc73-4109-4ac1-9c17-b7de48eaf5c8.png)
