### ISSUE TITLE
Fenster Zustand funktioniert nicht  wenn 0 eingetragen wird in WindowOpenDecrease

### ISSUE THREAD

**Issue by mrstackit** [rg-engineering/ioBroker.heatingcontrol#276]
Hallo,

ich habe festgestellt wenn man 0°C in WindowOpenDecrease eingträgt das dann dieser Wert nicht gesetzt wird. Der Adapter ignoriert dann den Fensterzustand offen.

**Comment by rg-engineering** [comment]
absolut oder relativ?

**Comment by mrstackit** [comment]
Hallo, in absolut.

zu diesem Thema bin ich erst gekommen weil das Offset auch bei Fenster geöffnet angewendet wird. Dadurch geht die Einstellung nicht auf 4,5°C womit die HomeMatic Thermostate nicht auf Off gehen. Deswegen wollte ich 0 einstellen. Da der HomeMatic Adapater dann automatisch auf 4,5°C stellt und die Thermostate dann auf Off wären.

**Comment by rg-engineering** [comment]
wenn du das so machst, bekommst du das nächste Problem: wenn der Adapter vom Thermostat eine andere Zieltemperatur zurückbekommt, als selbst eingestellt, stellt er auf manual... weil er nicht unterscheiden kann, ob jemand am Thermostat gedreht hat, oder ob die Änderung irgendwoanders herkommt.
Die bessere Lösung wäre wohl, den Offset anders zu verwenden. Auf der anderen Seite sehe ich den Vorteil nicht, wenn das Thermostat auf off geht. Eine Zieltemperatur von z.Bsp. 7°C muss doch zum gleichen Ergebnis führen: das Thermostat schliesst das Ventil. Ob das Thermostat dann auf off steht oder eine niedrige Zieltemperatur verwendet, sollte doch egal sein...

**Comment by Sundancer78** [comment]
wo ist der Datenpunkt "WindowOpenDecrease" zu finden? ich find den einfach nicht.

**Comment by rg-engineering** [comment]
![grafik](https://user-images.githubusercontent.com/8238668/145716940-2196dcab-4ea9-4368-933a-c0b22f69ebeb.png)

**Comment by Sundancer78** [comment]
einen Ordner absolute gibt es bei mir nicht. 
![Screenshot_profiles_heating](https://user-images.githubusercontent.com/42901216/145729601-ccb2b0cb-e013-45b9-9cb0-25f7c3147409.png)

**Comment by rg-engineering** [comment]
dann bitte einschalten: 

![grafik](https://user-images.githubusercontent.com/8238668/145857179-fad32508-bbef-4b35-bddc-d46f3c9580fa.png)


(übrigens: das hat nichts mit dem hier behandelten issue zu tun, besser im iobroker-Forum solche Fragen stellen)

**Comment by rg-engineering** [comment]
@mrstackit Können wir das Thema hier schliessen?

**Comment by mrstackit** [comment]
Auch wenn ich es so akzeptiere das der Adapter das Offset bei Fenster auf mit berücksichtigt gibt es noch ein anderes Problem wenn die Thermostate nicht auf Off stehen. Sie erkennen dann irgendwann das Fenster auf und setzen auch einen manuellen Override. Ist es so viel Aufwand dem Adapter hinzuzufügen wenn Fenster auf verwerfe das Offset?

**Comment by rg-engineering** [comment]
Seit 2.8.1 wird der offset bei Fenster offen nicht mehr verwendet...

**Comment by mrstackit** [comment]
Vielen Dank. Das hatte ich im Change Log eben übersehen als ich geupdatet habe weil ich nur das von heute gelesen habe. Thema kann hier also zu. Hab dir eine Donation gesendet als dank dafür.
