### ISSUE TITLE
Temperature Override Remaining Time nach "Reset auf Auto"

### ISSUE THREAD

**Issue by mcod190** [rg-engineering/ioBroker.heatingcontrol#278]
Hallo,
wenn ein Temperatur Override frühzeitig beendet wird, über Temperatur 0 oder Zeit 00:00 wechselt der "State" wieder auf Auto. Nur die "Remaining Time" zählt weiterhin bis auf 0 runter. Ist die "Remaining Time" noch nicht auf 0 ändert sich die Zeit nicht, wenn ich die Zeit oder die Temperatur wieder geändert wurde, der Programmzustand ist weiterhin "ovverride"

**Comment by rg-engineering** [comment]
ist mit 2.8.1 erledigt...
