### ISSUE TITLE
Mehrere Datenpunkte für Urlaub etc.

### ISSUE THREAD

**Issue by Denkra** [rg-engineering/ioBroker.heatingcontrol#279]
Gibt es eine möglichkeit mehrere Datenpunkte einzutragen für zum beispiel Urlaub zu Hause? Hintergrund ist meine Frau und ich haben einen extra Kalender also jeder einen. Urlaub müsste dann einmal von ihrem und einmal von meinem Kalender ausgelesen werden damit nicht einer von beiden im kalten sitzt wenn er nach Hause kommt.

**Comment by Pittini** [comment]
Seh ich nich als Job für den Adapter, sonst kommt morgen wer mit 2 Kindern die auch nen extra Kalender haben... Einfache Lösung: Die x Kalendereinträge mit nem kleinen Skript zusammenfassen und nen Summendatenpunkt damit beschreiben. Und diesen dann dem Adapter als Anwesenheitsdatenpunkt reichen.

**Comment by rg-engineering** [comment]
@Denkra das werde ich nicht einbauen, mit der gleichen Begründung, wie @Pittini oben schon geschrieben hat.
