### ISSUE TITLE
Manuell eingefügte MAX! Thermostate werden sporadisch nicht gespeichert.

### ISSUE THREAD

**Issue by Denkra** [rg-engineering/ioBroker.heatingcontrol#28]
Da Max! Thermostate nicht automatisch erkannt werden, habe ich sie manuell eingefügt. Wenn es mal klappt dauert es nicht lange bis sie wieder gelöscht sind bzw werden gar nicht erst gespeichert.

**Comment by Denkra** [comment]
Da Max! Thermostate nicht automatisch erkannt werden, habe ich sie manuell eingefügt. Wenn es mal klappt dauert es nicht lange bis sie wieder gelöscht sind bzw werden gar nicht erst gespeichert.

**Comment by rg-engineering** [comment]
ist evtl. die Option "Löschen aller Geräte bei admin-Start" eingeschaltet? Dann bitte deaktivieren...
