### ISSUE TITLE
nicht gewollte Overrides zu bestimmten Zeiten

### ISSUE THREAD

**Issue by Rich990** [rg-engineering/ioBroker.heatingcontrol#281]
Guten Tag,
mir ist aufgefallen, dass sich jeden Tag zu zwei Uhrzeiten (7:00 und 17:00) in einem Raum die Heizung für eine Override Phase (30 Minuten) auf 21 Grad stellt. Zu den jeweiligen Zeiten war keiner im Raum bzw. habe ich sicher nicht am Thermostat gedreht. Das Ereignis kommt jeden Tag vor. 
Ich habe im Adapter 1 Profil mit 4 Perioden konfiguriert. Zu den Zeiten wechselt keine Periode in die nächste und 21 Grad ist auch keine Zieltemperatur.
Ich benutze Homatic Thermostate.
Ich hoffe das Logfile erklärt euch, woher dieses Verhalten kommt.

Vielen Dank für die Hilfe!
Richard

PS: ich konnte dem ganzen nciht das Label "question" geben, da es sicher kein Bug im Code ist sondern wieder ein Problem bei mir sein wird...
[büro.txt](https://github.com/rg-engineering/ioBroker.heatingcontrol/files/7683225/buro.txt)

**Comment by rg-engineering** [comment]
in beiden Fällen kommt vom hm-rpc.0.MEQ0796561.4.SET_TEMPERATURE die Zieltemperatur von 21°C.
Ich könnte mir vorstellen, dass das Thermostat selbst einem Zeitplan folgt... Steht das Thermostat auf manu oder auto? oder kommt der Zeitplan von der CCU?

**Comment by Rich990** [comment]
tatsächlcih stand das Thermostat auf "Auto" und in der CCU war noch ein Zeitplan hinterlegt... vielen Dank für die Hilfe!
