### ISSUE TITLE
"Raumstatus" zeigt falsche Isttemperatur

### ISSUE THREAD

**Issue by Haititei** [rg-engineering/ioBroker.heatingcontrol#283]
Die Kachel "Raumnstatus" zeigt in der Spalte "aktueller Wert" nicht die Temperatur des externen Sensors, sondern eines Thermostatventils an. In Räumen mit mehreren Heizkörperventilen, die auf die Steuerung durch den Wert des externen Themperatursensors angewiesen sind, ist dies Verhalten sehr verwirrend und führt zu langer und vergeblicher Fehlersuche, da nicht transparent gezeigt wird, woher der angezeigte Wert kommt.
Hier das Beispiel meines Schwimmbadraumes. Die Heizkörperventile befinden sich unter einer Bank bzw. in einem Schacht. Einen schlüssigen Wert für den Raum können sie somit nicht anzeigen.
![grafik](https://user-images.githubusercontent.com/96390121/146686896-84314248-4e4f-4704-8c83-681eab5da8e4.png)
Und hier die Anzeige der Raumkachel:
![grafik](https://user-images.githubusercontent.com/96390121/146686909-f0378f6a-6e29-410a-99aa-0b63980f6507.png)

**Comment by rg-engineering** [comment]
@Haititei folgender Vorschlag:
![grafik](https://user-images.githubusercontent.com/8238668/147263632-265ba980-3c8e-4dba-8963-242278495fa3.png)

ich zeige beide Werte an (intern und am zusätzlichen Sensor) und außerdem zeige ich noch den Offset an...

ohne zusätzliche Sensoren sieht das ganze dann wie bisher aus:

![grafik](https://user-images.githubusercontent.com/8238668/147263827-e3703182-b3db-4c15-aaac-0fa6c2a2f1cc.png)

**Comment by rg-engineering** [comment]
@Haititei sollte mit der 2.8.1 jetzt erledigt sein... Über feedback wäre ich dankbar...
