### ISSUE TITLE
Steuerung zusätzlicher Datenpunkte für Thermostate

### ISSUE THREAD

**Issue by mkshb** [rg-engineering/ioBroker.heatingcontrol#284]
Moin,

erstmal großes Lob für den Adapter. Es sind nahezu alle Szenarien bedacht und er läuft sehr zuverlässig. Danke!

**Describe wanted Enhancement !**  
Weitere Datenpunkte der Thermostate bei ausgeschalteter Heizperiode konfigurierbar machen. 

**Why should we put effort in it ?**  
Ich habe bei mir eine Nachtabsenkung realisiert, indem ich bei aktiviertem "Schlafstatus" des Hauses die Heizperiode abschalte. Damit erreiche ich, dass alle Thermostate auf 8°C gestellt werden. Bei sehr niedrigen Aussentemperaturen und offenem Fenster fällt die Raumtemperatur gern mal unter diesen wert und das Thermostat versucht dagen zu heizen. 
Meine Z-Wave Thermostate lassen sich leider nicht < 8°C regulieren. Daher wäre es gut mit dem Adapter einen anderen Datenpunkt (hier Heatmode = Off) steuern zu können.

Danke und weiterhin frohes Fest.

**Comment by duffbeer2000** [comment]
Die Raumtemperatur fällt unter 8°C? Dir ist schon klar das durch die einströmende kalte Luft (die im Winter oftmals unter 0*C ist)  die Heizungsrohre einfrieren lassen kann? Außerdem steigt die Schimmelgefahr immens an. Manchmal bin ich sprachlos. Auf die Erklärung bin ich echt gespannt.

**Comment by rg-engineering** [comment]
Unabhängig vom Hintergrund des feature-Wunsches bleibe ich dabei, dass ich den Adapter möglichst Hardware-unabhängig behalten will. Datenpunkte für spezielle Hardware (z.Bsp. Thermostate) möchte ich nicht in den Adapter einbauen, da das ganze sowieso schon viel zu kompliziert zu konfigurieren ist... Also wenn du so etwa so wirklich brauchst, dann bitte außerhalb des Adapters realisieren...
