### ISSUE TITLE
Abwesend / Urlaub abwesend

### ISSUE THREAD

**Issue by slimline33** [rg-engineering/ioBroker.heatingcontrol#285]
Hi,

Ich habe zwei unterschiedliche Temperaturen gesetzt für normale Abwesenheit und Urlaub abwesend.

Bei Abwesenheit setze ich 19°  und bei Urlaub setze ich 15°.

Beides wird auch aktiv mit den entsprechenden Datenpunkten, jedoch nimmt er immer die Abwesenheit als Temperatur Einstellung.

Im Moment bin ich auch im Urlaub und auch nicht da. Da ist mir das aufgefallen. Die Demonstration ist jetzt auch nur für einen Raum (BadOG) . In den anderen Räumen habe ich die Abwesenheit jetzt ignoriert und setze nur auf Urlaub abwesend. Daher bitte nicht beachten.

Gruß Christoph

![IMG_20211229_132048](https://user-images.githubusercontent.com/3323812/147661769-705ee793-9943-46bb-ad8d-11de50defda4.jpg)
![Screenshot_2021-12-29-13-21-21-437_com chrome beta](https://user-images.githubusercontent.com/3323812/147661774-2c50c4b6-3538-4075-ab62-86aca702963e.jpg)

**Comment by rg-engineering** [comment]
Das ist eine Frage der Priorität. Aktuell wird nach folgender Reihenfolge geprüft und sobald eine Bedingung erfüllt ist, gewinnt diese:
* Fenster offen
* Abwesenheit
* Urlaub abwesend
* Gäste
* Party
* Kaminmodus

Vielleicht ist es wirklich eine gute Idee, Abwesenheit und Urlaub abwesend zu tauschen ...

**Comment by slimline33** [comment]
Ja, weil wenn Urlaub abwesend, dann ist man ja auch nicht zuhause. Dafür gibt es ja den Urlaub zuhause Datenpunkt.

**Comment by slimline33** [comment]
Evtl würde es auch Sinn ergeben Gäste als Prio1 zu setzen. Oft hat man Gäste über Nacht zum Beispiel und man ist evtl tagsüber nicht anwesend wegen Arbeit o.ä.

Was natürlich am allerbesten wäre, wenn man die Prio für sich selber einstellen kann. Aber wenn man es weiß, dann weiß man auch worauf man achten muss.

Gruß Christoph

**Comment by rg-engineering** [comment]
mit 2.8.1 habe ich abwesend und UrlaubAbwesend getauscht. Alles andere lasse ich erst mal so. Eine Einstellung durch den user ist m.E.  nicht notwendig.

**Comment by slimline33** [comment]
Okey :) danke für die Mühe! Dann können wir das issue ja schließen!
