### ISSUE TITLE
json settings import does not work 

### ISSUE THREAD

**Issue by passuff** [rg-engineering/ioBroker.heatingcontrol#286]
json settings import does not work.
Platform       : linux
os             : linux
Architecture   : x64
CPUs           : 2
Speed          : 1699 MHz
Model          : Common KVM processor
RAM            : 7.7 GB
System uptime  : 8d. 06:53:26
Node.js        : v12.22.5
Disk size      : 30.4 GiB
Disk free      : 27.3 GiB
adapters count : 449
NPM            : v7.5.2

Adapter 2.80

**Comment by rg-engineering** [comment]
Habe es eben hier bei mir versucht, hier geht es:
![grafik](https://user-images.githubusercontent.com/8238668/147687425-fc16e805-85a8-401f-9564-3bacf297726b.png)


Ich brauche also mehr Informationen:  Fehlermeldungen, log, evtl. das Profil, welches nicht geladen werden kann, usw...

**Comment by rg-engineering** [comment]
@passuff hast du ein log oder kann ich das issue hier schliessen?

**Comment by passuff** [comment]
@rg-engineering  bei mir geht es nicht. 
Ich habe eine zweite Instanz erstellt und versucht die Settings der ersten zu importieren. Es gibt keine Fehlermeldung oder Bestätigung. Auch das log (debug level) bleibt komplett leer. Es gibt daher nichts was ich dir schicken könnte. Eventuell kannst du das nachstellen.

**Comment by rg-engineering** [comment]
kannst du mir die json schicken, die du versuchst zu importieren?

**Comment by rg-engineering** [comment]
ah, du versuchst hier zu importieren:
![grafik](https://user-images.githubusercontent.com/8238668/148422813-d503261d-3327-44d0-aa71-2f88c78e07bb.png)

ich dachte, du meinst die Profil-Konfiguraton hier:
![grafik](https://user-images.githubusercontent.com/8238668/148422934-9e03c4bf-9a4c-4b50-b41d-3f0ee316dc83.png)

**Comment by rg-engineering** [comment]
ja, das geht wirklich nicht, das kann ich nachvollziehen... bug fix kommt...

**Comment by rg-engineering** [comment]
mit der 2.8.3 sollte das wieder funktionieren...

**Comment by passuff** [comment]
@rg-engineering funktioniert nun einwandfrei. Danke Dir!
