### ISSUE TITLE
Logik des "TemperatureOvewrite" DP mit aktueller Zieltemperatur ändern

### ISSUE THREAD

**Issue by ScumbagSteve** [rg-engineering/ioBroker.heatingcontrol#287]
Ich möchte über VIS oder Homematic Termostate die aktuelle Zieltemperatur ändern ("Overwrite"). Für beide Anwendungen brauche ich dabei einen steuerbaren Datenpunkt, der mir die aktuelle Temperatur anzeigt und diese überschreiben lässt. Das geht aus meiner Sicht weder über die Datenpunkte des Thermostats, noch über die des heatingcontrol Adapters.

Die _reale_ Zieltemperatur muss ich nämlich erst mal berechnen.  Diese ist CurrentTarget + TemperatureOffset und findet sich weder im heatingcontrol, noch im Thermostat. (Oder stehe ich auf dem Schlauch?)

Bei einem manuellen Overwrite benötige ich dann immer zwei Datenpunkte:
1. meine selbst berechnete reale Zieltemperatur (zum Anzeigen auf dem Termostat)
2. Den Overwrite Datenpunkt (der mir die Temp. bis zur nächsten Profiländerung einstellt).
Leider funktioniert das Steuern mit zwei unterschiedlichen Datenpunkten nur sehr schwer.

Anbei mein Vorschlag:
### Ändern des TemperatureOverwrite DP: Es wird immer die aktuelle _reale_ Zieltemperatur angezeigt. Das Übeschreiben dieser Zieltemperatur soll analog der bisherigen Overwrite Funktion funktionieren. Das heißt:
1. Reale Zieltemperatur ist die Temperatur wie sie im Profil eingestellt ist (z.B. 22 Grad)
2.  Freundin ändert die 22 Grad z.B. über VIS auf 24 Grad
3. 24 Grad werden bis zur nächsten Profiländerung als aktuelles Ziel gesetzt (natürlich unter Berücksichtigung des Offsets)
4. Zum nächsten Profilzeitpunkt wird der Datenpunkt von vorher 24 Grad (Overwrite) wieder auf die jeweils gültige Profileinstellung zurückgesetzt

**Comment by rg-engineering** [comment]
Hier mal zwei screen shots aus meinem Testsystem:

Im ersten sieht man:
* Zieltemperatur laut Profil 21°C
* Offset 2°C
* Ziel, welches an's Thermostat geschickt wird (currentTarget): 23°C

![grafik](https://user-images.githubusercontent.com/8238668/148271203-aa602eb0-0fc9-493a-a361-e027d441e916.png)

Hier nochmal die 23°C "reale Zieltemperatur" (Thermostat1_Soll) auf die das Thermostat regelt (ja klar, hier javascript als Thermostat-Simulator ;-))
![grafik](https://user-images.githubusercontent.com/8238668/148271302-fe8fbbb1-1bd7-4d76-ac94-b09bccda269c.png)



Wenn du nun auf den Datenpunkt am Thermostat mit der Zieltemperatur einen Wert schreibst (per Vis oder alexa o.ä.) wird der zum Thermostat geschickt und im Adapter als override oder bis zum nächsten Profilpunkt verwendet (ja nach Einstellung bei dir)

Aus meiner Sicht hast du alles, was du dir wünschst, schon im Adapter verfügbar....

**Comment by ScumbagSteve** [comment]
Hey, danke für dein Feedback.
Aus meiner Sicht ist das was ich da habe nicht ganz sinnvoll.

Der eigentlich einzig "korrekte" Wert der erwähnten, sind ja die 21 °C aus dem Periods. Diese sind die tatsächliche Raum-Zieltemperatur.
Die befinden sich jedoch nicht in einem festen Datenpunkt, sondern es muss immer erst mal die gerade aktive Periode ermittelt werden. Die beiden erwähnten 23 °C sind ja insofern inkorrekt,  als dass der Raum ja nicht wirklich auf 23 °C geheizt werden soll. Der Wert 23 °C kommt ja nur durch den "Fehler" (Offset) der Temperaturmessung am Thermostat zustande. Reales Ziel sind ja die 21 °C. 

_Wenn du nun auf den Datenpunkt am Thermostat mit der Zieltemperatur einen Wert schreibst (per Vis oder alexa o.ä.) wird der zum Thermostat geschickt und im Adapter als override oder bis zum nächsten Profilpunkt verwendet (ja nach Einstellung bei dir)_

Du schlägst ja vor in die VIS also Thermostat1_Soll zu legen. Macht aus meiner Sicht dann aber aus den oben erwähnten Gründen keinen Sinn, da die dort gezeigten 23 °C ja nicht das aktuelle tatsächliche Ziel ist. Das Ziel ist eigentlich 21 °C Zimmertemperatur, die ich dann temporär z.B. auf 24 °C Zimmertemperatur ändern möchte. Wenn ich nun da 24 °C rein schreibe, sind es durch den messbedingten "Offset" (den der Adapter ja normal sonst berücksichtigen würde) ja nur "reale" 22 °C Zimmertemperatur, die dabei raus kommen. Ich müsste bei 24 °C gewünschter Temperatur ja dort 26 °C rein schreiben. 

Hoffe du verstehst worauf ich raus möchte.

**Comment by MrEdd123** [comment]
Ich hatte bis gestern das gleiche Problem das die angezeigte Solltemperatur ja nicht die wirkliche Solltemperatur ist, sondern durch Offset verändert ist. 

Ich habe es so gelöst.

![Screenshot 2022-01-07 212207](https://user-images.githubusercontent.com/30874279/148602530-f544944a-d8c6-4fbc-a36b-fbd8c07d0d33.jpg)

Ich lege ein Datenpunkt für die reale Zieltemperatur an " CurrentTarget_Summe_wert_kal"
Dann prüfe ich, ob der OffsetWert positiv oder negativ ist.
Ist er negativ, wird die Funktion wahr ausgeführt, das heißt zum errechneten Target wird der OffsetWert abgezogen.
Ist er positiv, wird die Funktion falsch ausgeführt, das heißt zum errechneten Target wird der OffsetWert addiert. 

Funktioniert !!!!!

**Comment by ScumbagSteve** [comment]
Stimmt, so würde es gehen. Allerdings löst das ja nur das Problem der Anzeige.
Ich möchte ja einen Overwrite Datenpunkt steuern können.

Dann müsste ich dort also diesen Wert anzeigen und einen anderen setzen. Ich bin mir nicht sicher, ob und wie das in der VIS geht.
Die obere Logik muss für jeden Raum angelegt werden. Mit Gebastel geht das, aber aus meiner Sicht ist das doch noch ein sehr nachvollziehbarer Use-Case, der nicht unbedingt nachträglich dazu gebastelt werden müsste.

Wir sind sicher nicht die Einzigen, die dafür Verwendung hätten.

**Comment by rg-engineering** [comment]
ich kann relativ einfach einen weiteren Datenpunkt "heatingcontrol.0.Rooms.TestRaum.CurrentTimePeriodTarget" (also parallel zu "heatingcontrol.0.Rooms.TestRaum.CurrentTimePeriodTime") anbieten. Der enthält dann die Temperatur laut Profil (und zwar immer, unabhängig vom offset oder irgendwelchen Absenkungen)
Wenn ich in den schon bestehenden DP "heatingcontrol.0.Rooms.TestRaum.TemperaturOverride" etwas anderes als 0 schreibe, erscheint z.Bsp. in der Pittini-Vis nicht mehr "inaktiv" sondern dieser Wert. Ob das alle user so haben wollen? Außerdem ist das interne Handling deutlich schwieriger, zu erkennen, wann override gewollt ist (Stichwort Absenkungen und Rückmeldungen vom Thermostat)

und bedenke, der override wird direkt, also ohne zusätzlichen offset an's Thermostat geschickt. Damit bin ich immer noch der Meinung, man sollte dafür einfach den DP direkt vom Thermostat mit einer Plus-Taste um jeweils 1 Grad erhöhen. Das ist dann das gleiche Verhalten, wie das direkte Ändern der Temperatur am Thermostat. Das ist wahrscheinlich auch das, was jeder macht, dem kalt ist: er oder sie dreht einfach etwas weiter hoch, völlig unabhängig von irgendwelchen Werten in der Anzeige...

**Comment by MrEdd123** [comment]
Das klingt alles sehr logisch, was Du da so ansprichst.
Bei mir ging es ja wirklich nur darum, die korrekte Solltemperatur angezeigt zu bekommen.
Ich habe jetzt noch ein Objekt ID als Auslöser hinzugefügt, sodass der DP mit dem korrekten Sollwert beim Drehen am Thermostat sowie beim Ändern von "current_heating_setpoint" über die VIS als auch beim Ändern  von "CurrentTarget" durch heatingcontrol berechnet wird.
![Screenshot 2022-01-08 192808](https://user-images.githubusercontent.com/30874279/148655802-da7e2425-2968-49de-ac4e-12d54a2f6446.jpg)

So funktioniert es für mich sehr gut.

PS: Danke für Deine super Leistung mit heatingcontrol kann dadurch leicht  von LIVISI mich trennen !!!

**Comment by ScumbagSteve** [comment]
> ich kann relativ einfach einen weiteren Datenpunkt "heatingcontrol.0.Rooms.TestRaum.CurrentTimePeriodTarget" (also parallel zu "heatingcontrol.0.Rooms.TestRaum.CurrentTimePeriodTime") anbieten. Der enthält dann die Temperatur laut Profil (und zwar immer, unabhängig vom offset oder irgendwelchen Absenkungen) 

Ja das klingt doch nach einem guten Kompromiss :)

**Comment by MrEdd123** [comment]
> > ich kann relativ einfach einen weiteren Datenpunkt "heatingcontrol.0.Rooms.TestRaum.CurrentTimePeriodTarget" (also parallel zu "heatingcontrol.0.Rooms.TestRaum.CurrentTimePeriodTime") anbieten. Der enthält dann die Temperatur laut Profil (und zwar immer, unabhängig vom offset oder irgendwelchen Absenkungen)
> 
> Ja das klingt doch nach einem guten Kompromiss :)

Würde dann auch der korrekte Sollwert angezeigt, wenn z.B. das Fenster auf ist?
Das ist das, was ich heute noch festgestellt habe das, bei dem DP Fenster AUF der Offset mit angezeigt wird.
In mein Script habe ich das noch mit eingebracht, sodass auch hier jetzt der richtige Sollwert angezeigt wird.

**Comment by rg-engineering** [comment]
> Würde dann auch der korrekte Sollwert angezeigt, wenn z.B. das Fenster auf ist?

in dem neuen Datenpunkt steht nur der Temperaturwert für die aktuelle Periode drin, ohne jegliche Anpassung. Bzgl. des offsets bei FensterOffen kommt es auf die verwendete Version an. In alten Versionen hatte ich den Offset bei FensterOffen (und anderen Absenkungen) mit drin, in den letzten wird bei FensterOffen der Offset ebenfalls nicht mehr verwendet. Das hat aber auf den hier angesprochenen neuen Datenpunkt keine Auswirkung, da der offset nicht mit enthalten ist...

**Comment by rg-engineering** [comment]
in V2.8.4 implementiert...
