### ISSUE TITLE
CurrentTarget wird nicht aktualisiert bei TemperatureOffset <> +-0.5°C

### ISSUE THREAD

**Issue by MrEdd123** [rg-engineering/ioBroker.heatingcontrol#289]
Ich habe festgestellt das bei "TemperatureOffset" Werten von 0.25°C und 0.75°C, egal ob + oder -, der "CurrentTarget" Wert nicht korrigiert wird.
Der von mir angelegte Datenpunk "CurrentTarget_Summe_Wert_kal" zeigt ja den tatsächlichen Wert der eingestellten Temperatur an, kann er dann aber nicht, da der "CurrentTarget" ja falsch ist. 

Hier bei -0.5 °C alles OK.
![Screenshot 2022-01-12 124234](https://user-images.githubusercontent.com/30874279/149175251-2e9548e3-225a-4820-8bbc-63e5461d4e5e.jpg)
Hier bei 0.75 °C keine Korrektur.
![Screenshot 2022-01-12 125218](https://user-images.githubusercontent.com/30874279/149175258-d821fbef-0180-48a5-839f-56695010ee0c.jpg)
Hier bei -1°C alles wieder OK.
![Screenshot 2022-01-12 085045](https://user-images.githubusercontent.com/30874279/149175272-ed9128c8-e979-4303-a077-0d2a04f760fc.jpg)
Hier bei -0.25°C wieder keine Korrektur.
![Screenshot 2022-01-12 170034](https://user-images.githubusercontent.com/30874279/149175965-726c0e73-c605-48a2-a7cb-d05648bdb4d0.jpg)

**Comment by rg-engineering** [comment]
kann das ganze ein Rundungsproblem sein? Die Zieltemperatur wird immer auf 0,5°C genau gerundet.

**Comment by MrEdd123** [comment]
> kann das ganze ein Rundungsproblem sein? Die Zieltemperatur wird immer auf 0,5°C genau gerundet.

Ich denke schon. Deine Formel zur Berechnung von CurentTarget kennt scheinbar nur Werte von +-0,5 oder +-1,0 °C.
Ich würde ja vorschlagen, den TemperaturOffset  auf 0,5 °C  Genauigkeit zu ändern, das sollte reichen.

**Comment by rg-engineering** [comment]
> Deine Formel zur Berechnung von CurrentTarget kennt scheinbar nur Werte von +-0,5 oder +-1,0 °C

Ich muss CurrentTarget auf 0,5°C runden, weil es sonst die Thermostate tun und dann kommt vom Thermostat etwas anderes zurück als gesetzt wurde und das führt dann wieder zu dem manual-Zustand. Ich runde jetzt den Offset auch auf 0,5°C...

**Comment by MrEdd123** [comment]
Kurze Rückmeldung von mir. Läuft jetzt wie es muss !!!!!! Danke !!!
