### ISSUE TITLE
Datenpunkt MODE anlegen

### ISSUE THREAD

**Issue by Chaot1** [rg-engineering/ioBroker.heatingcontrol#29]
Ist es möglich einen Datenpunkt Mode anzulegen mit dem der Modus des Thermostat dirkt gesteuert werden kann.
Bei den DECT Thermostaten ist das 
Mode 0 = AUTO
Mode 1 = AUS (geschlossen)
Mode 2 = ON (geöffnet)
Ich könnte das zwar auch über den DECT Adapter steuern, aber ich befürchte das der dann vom Heatingcontrol wieder überschrieben wird.

Gedacht ist das einfach das ich bei "Fenster auf" direkt auf Mode 1 gehen kann oder im tiefen Winter kurz einen Button drücke der für 30 Minuten Mode 2 auslöst und ich 30 Minuten später in die schöne warme Dusche komme. (sofern wir noch kalte Winter bekommen)

**Comment by rg-engineering** [comment]
Ich möchte eigentlich keine Geräte-spezifischen Anpassungen im Adapter haben. Solche Themen gehören m.E. eher in den jeweiligen Geräte-Adapter. Ich denke auch, dass o.g. Szenario durchaus mit den bestehenden Adaptern geandelt werden kann. Der HeatingControl-Adapter sollte den Mode am Thermostat nicht überschreiben, er setzt nur Ziel-Temperaturen. Ich würde erwarten, dass der Thermostat nur dann auf die Ziel-Temperatur regelt, wenn er im Auto-Mode ist. Wenn also Mode 1 oder 2 gesetzt wurde, dürfte das Setzen einer neuen Ziel-Temperatur keine Auswirkung haben...

**Comment by Chaot1** [comment]
Ja, da hast du Recht. Das machte den Adapter weniger universel.
Ich kann ja den Datenpunkt im ioBroker setzen.
Würde es Sinn machen den Mode zu prüfen und dann aus dem Adapter nicht zu schreiben? Oder sprengt das den Rahmen der Abfragen?

**Comment by rg-engineering** [comment]
keine weitere Aktivität notwendig...
