### ISSUE TITLE
Temp offset calculation skipped, time difference too long

### ISSUE THREAD

**Issue by fisch336** [rg-engineering/ioBroker.heatingcontrol#290]
Hallo,

bekomme dies in regelmässigen Abständen angezeigt. 
Woran kann es liegen?

Ein Thermostat ist eingestellt auf konsequent 18 Grad, zu allen Zeiten.

**Comment by rg-engineering** [comment]
Es wird geprüft, wann updates des externen Sensors und des Sensors vom Thermostat empfangen wurden. Wenn zwischen den Ereignissen zu viel Zeit vergangen ist, werden die Temperaturen nicht für die Mittelwert-Bildung verwendet.
Die maximale erlaubte Zeitdifferenz kann man einstellen:
![grafik](https://user-images.githubusercontent.com/8238668/149818940-9512f03b-81c6-4190-8e69-b9d1e08fbec6.png)
