### ISSUE TITLE
Bitte Doku prüfen, diese macht die Seite kaputt

### ISSUE THREAD

**Issue by Kokomiko** [rg-engineering/ioBroker.heatingcontrol#296]
Wenn man die Seite in der Adater-Dokumentation aufruft wird die gesamte Seite als leeres Blatt dargestellt, also auch das Menü, das ioBroker-Logo und die Adapterliste verschwinden:

https://www.iobroker.net/#de/adapters/adapterref/iobroker.heatingcontrol/README.md

Da dies bei anderen Adaptern nicht passiert, liegt die Vermutung nahe, dass die Heatingcontrol-Doku die entsprechenden Elemente enthält, die die Seite zerstören. :-)

**Comment by rg-engineering** [comment]
Die o.g. website ist nicht von mir und wird auch nicht von mir gepflegt. Die readme.md auf github ist funktional. Bitte an die Autoren der website wenden...

**Comment by Jey-Cee** [comment]
Die Seite zieht nur die Readme aus dem Repo und bindet sie ein. 
Tatsächlich ist da ein "Fehler" in der Readme, die Jahresangabe im Copyright: <2019-2021>
Die < > verursachen das Problem.

**Comment by rg-engineering** [comment]
ist jetzt in der 2.9.0 drin und kann getestet werden...
