### ISSUE TITLE
Problem mit Offset und Minimaltemperatur

### ISSUE THREAD

**Issue by Creekhail** [rg-engineering/ioBroker.heatingcontrol#297]
Beim Einsatz der Offsetfunktion kommt es bei meinen Thermostaten in Verbindung mit der Minimaltemperatur zu einem Problem.
Ich verwende auch die Fensteroffen-Funktion und wenn nun ein negatives Offset vorliegt, wird die Minimaltemperatur so weit herabgesetzt, dass meine Thermostate nicht mehr reagieren.
Das liegt natürlich hautptsächlich an den Thermostaten, da diese als Mindesttemperatur 5 Grad verlangen, darunter wird jeder Wert ignoriert der kleiner als 5 Grad ist.

Ich werde jetzt versuchen mit einem eigenen Skript diesen Umstand abzufangen und immer wenn versucht wird einen kleineren Wert einzufügen sofort wieder auf 5 Grad zurückzusetzen.
Aber trotzdem wäre es natürlich schön wenn das die heatingcontrol Steuerung bereits berücksichtigen könnte.
Das Ganze könnte aus meiner Sicht auf zwei verschiedene Arten gelöst werden: Entweder wird beim Berechnen der zu setzenden Minimaltemperatur ein Grenzwert berücksichtigt der auch mit Offset nicht unterschritten werden darf, oder es wird bei der Fensteroffen-Funktion nicht auf die Minimaltemperatur eingestellt sondern der Thermostat abgeschaltet.
Ich vermute aus verschiedenen Gründen dürfte die erste Methode jedoch am wenigsten Aufwand bedeuten und auch für viele Thermostate leichter umzusetzen sein.

**Comment by rg-engineering** [comment]
Ich habe in der 2.8.5 den check auf Minimal-Temperatur auf den Offset erweitert. d.h. falls Minimum inkl. Offset unterschritten werden soll, wird Minimum verwendet...
