### ISSUE TITLE
Erweiterte Log Einträge bei Stufe "Info"

### ISSUE THREAD

**Issue by MMeinhardt1** [rg-engineering/ioBroker.heatingcontrol#302]
Hi,

besteht die Möglichkeit eine Option ins Admin Menü zu integrieren mit der man "erweiterte" Info Ausgaben aktivieren kann wie z.B.,
- gesetzte Temperatur zur jeweiligen Zeit wenn diese vom Adapter gesendet wird
- gesetzte Temperatur bei manueller Änderung
- Fenster offen/geschlossen erkannt

Vielen Dank

**Comment by rg-engineering** [comment]
Vorschlag:

![grafik](https://user-images.githubusercontent.com/8238668/161611151-3ed71185-1c63-4621-895a-4d3975da8caa.png)

![grafik](https://user-images.githubusercontent.com/8238668/161611236-f48aaa0f-f71a-46b8-9111-aa47fb94c61e.png)

**Comment by MMeinhardt1** [comment]
Hi @rg-engineering,
das sieht doch sehr gut aus! Sag bescheid wenns implementiert ist.

Vielen Dank für Deine Mühen!

**Comment by rg-engineering** [comment]
ist jetzt in der 2.9.0 drin und kann getestet werden...
