### ISSUE TITLE
Lbar nicht automatisch einblenden

### ISSUE THREAD

**Issue by m1chel87** [rg-engineering/ioBroker.heatingcontrol#304]
Jedes mal wenn die Vis Seite neu geladen wird popt an der linken Seite die Menüleiste "lbar" auf.
Kann man das ändern, dass die nur noch durch klicken auf geht?

**Comment by rg-engineering** [comment]
der Adapter selbst stellt keine vis zur Verfügung. evtl. meinst du die [Pittini-vis](https://github.com/Pittini/iobroker-heatingcontrol-vis). Dann bitte das issue dort einstellen...
