### ISSUE TITLE
Feature Request: Burst Modus 

### ISSUE THREAD

**Issue by CKMartens** [rg-engineering/ioBroker.heatingcontrol#31]
Ist es möglich einen Burst Modus zu integrieren um, wenn in einem Raum ein DP für den Burst auf true gesetzt wird, die Thermostate in diesem Raum für eine bestimmte Zeit (15-30 Minuten) voll zu öffnen bzw auf die maximale Temperatur zu schalten?

Wäre gut um z. B. das Bad kurz aufzuheizen oder nach dem Lüften kurz aufzuwärmen bzw wenn die Frau mal wieder wegen Kälte motzt einfach mal hichzuheizen.

Danke für deine Mühe, 
Carsten

**Comment by rg-engineering** [comment]
mit der Möglichkeit des manuellen Setzens der Temperatur für eine gewisse Zeit sollte dieses Thema erledigt sein...
