### ISSUE TITLE
Overwrite über Handy mit Iogo App steuern

### ISSUE THREAD

**Issue by m1chel87** [rg-engineering/ioBroker.heatingcontrol#313]
Aktuell heizen wir die Zimmer der Jungs nur sporadisch, weil Sie meist nicht da sind oder wenn nur in einem Zimmer hocken...
Ich würde gerne die Overwrite Funktion zum Erhöhen den Raumtemperatur bei Bedarf nutzen. Da es mit dem Handy deutlich bequemer ist, habe ich die Role des Datenpunkts TemperaturOverwriteTime(vom Kinderzimmmer) auf level geändert. Sieht dann fertig so aus:
![grafik](https://user-images.githubusercontent.com/64650166/164476165-4597fd88-e6d1-4744-ab07-9cd680231b3d.png)
![grafik](https://user-images.githubusercontent.com/64650166/164477558-c6c52212-2784-487b-83a8-73ab846b1c4a.png)
Leider werden alle Roles der Datenpunkte nach Adapterneustart auf den ursprünglichen Wert gesetzt. Nun kann ich das ganze aber nicht mehr über das Handy steuern :(

Als zweites ist mir aufgefallen, dass die Overwrite-Zeit sich nach dem Einstellen nicht mehr ändern lässt. Einmal eingestellt läuft die Zeit runter und lässt sich nur durch Adapterneustart wieder ändern. Soll das so?

**Comment by rg-engineering** [comment]
De Rollen sind hier festgelegt. Habe mal versucht, mich daran anzupassen... kommt dann mit 2.9.2

Der Override lässt sich abrechen, indem man die Override-Temperatur auf 0 setzt, oder die override-Zeit auf 00:00 setzt.

**Comment by rg-engineering** [comment]
@m1chel87 passt das jetzt in 2.9.3 ?

**Comment by m1chel87** [comment]
> @m1chel87 passt das jetzt in 2.9.3 ?

Muss ich prüfen. Kann ich dir so nicht sagen. Ich schau's mir am Wochenende mit an.
