### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by duczz** [rg-engineering/ioBroker.heatingcontrol#316]
Ich nutze den Adapter für meine Klimaanlage, und hätte gerne einen Timer, der nach definierter Zeit die Anlage ausschalten, könnte man das mit einbauen?
Wäre ggf auch was fürs heizen

**Comment by Pittini** [comment]
Macht imo keinen Sinn in einem Heizungsadapter. Nichtsdestotrotz...findest hier nen allgemeinen Timer: https://github.com/Pittini/iobroker-Timer

**Comment by rg-engineering** [comment]
@Pittini wäre auch meine Reaktion gewesen. Den Timer kann man elegant extern anlegen und der Adapter lässt sich so wie gewünscht steuern...
