### ISSUE TITLE
Temp Bug?

### ISSUE THREAD

**Issue by duczz** [rg-engineering/ioBroker.heatingcontrol#317]
Es gibt folgende 2 Werte: heatingcontrol.1.Rooms.Schlafzimmer.CurrentTarget & heatingcontrol.1.Rooms.Schlafzimmer.CurrentTimePeriodTemperature

Sollten diese nicht gleich sein, da man unter rooms > Thermostate ja eig den VIs gesetzten Wert an das Thermostat übergeben müsste oder? Bei mir ändert sich dies aber nicht, somit stimmt der Wert am Thermostat auch nicht (Vom Thermostat zurück zum Adapter klappt aber)

Desweiteren ist mir folgendes aufgefallen, welches über mehrere Instanzen hinweg geht, angemeckert wird .0, .1 reagiert ebenfalls:
![image](https://user-images.githubusercontent.com/25475385/179156465-b2216293-f5de-425b-81ce-f7ecfd8758db.png)

**Comment by rg-engineering** [comment]
CurrentTarget ist der Wert, der an's Thermostat gesendet wird (inkl. offsets usw). CurrentTimePeriodTemperature ist der Wert ohne die offsets...

Die anderen Fragen verstehe ich leier nicht...

BTW. in deinem log ist die Heizperiode aus, deshalb wird wahrscheinlich nichts an das Thermostat gesendet...
