### ISSUE TITLE
Urlaub manuell eintragen

### ISSUE THREAD

**Issue by Aushilfsarnie** [rg-engineering/ioBroker.heatingcontrol#319]
Hallo!
vielen Dank für den tollen Adapter!
Es wäre schön, wenn es die Möglichkeit gäbe, den Start bzw. vor allem das Ende eines Urlaubs direkt einzutragen (ohne die Nutzung eines Kalenders).

**Comment by rg-engineering** [comment]
Aber das geht doch:
![grafik](https://user-images.githubusercontent.com/8238668/183469275-512a81e0-9a67-49b2-b9b7-197a5490657a.png)

**Comment by Aushilfsarnie** [comment]
und wo trage ich das Datum ein bis wann der Urlaub geht? Danke

**Comment by rg-engineering** [comment]
Hier kannst du UrlaubAbwesend beliebig ein- und ausschalten. 
Wenn du das ganze per Datum haben willst, dann führt kein Weg an einem Kalender vorbei...

**Comment by Aushilfsarnie** [comment]
Ok, danke! Ich dachte, es wäre vielleicht analog zur Homematic/raspbeeryMatic Oberfläche möglich, irgendwo ein Datum einzutragen, wann der Urlaub(smodus) endet. Das wäre toll.

**Comment by rg-engineering** [comment]
aber dafür gibt es doch in iobroker mehrere Möglichkeiten per Adapter... z.Bsp. iCal oder Kalender Zeitplan
Das muss dann nicht jeder Adapter selbst integrieren...
