### ISSUE TITLE
Benachrichtigung Telegram - Auswahl Empfänger

### ISSUE THREAD

**Issue by aruttkamp** [rg-engineering/ioBroker.heatingcontrol#323]
Das Auswahlfeld für Telegram Empfänger hat keine Funktion.
Ich kann keinen Empfänger wählen. 
![Snag_4cdeb1ba](https://user-images.githubusercontent.com/1271404/193143311-0532354e-7acd-4f26-9ddb-1de1ea52cb84.png)

**Comment by rg-engineering** [comment]
@aruttkamp  Kannst du das bitte testen? sollte mit der 2.9.3 hier in github behoben sein...

**Comment by aruttkamp** [comment]
Sehr gerne. 
Beim 1. Aufruf stand im Feld "Telegram Receiver" nur "All Receiver" - Eine Auswahl war nicht möglich. 
Ich habe dann links bei "telegram instance" auf "Keine" gewechselt und zurück auf "telegram.0". 
Es wurden dann 3 mal "All Reciver" angezeigt. nach einem weiteren Mal nun 5.
Eingerichtet sind in Telegram 3 Receiver
![image](https://user-images.githubusercontent.com/1271404/196767238-2f7a1815-964e-48ae-a788-f7aff72eaa8e.png)

**Comment by rg-engineering** [comment]
okay, doppelte Einträge sind verhindert, aber um die user einzutragen, würde ich trotzdem ein consolen log benötigen...

**Comment by rg-engineering** [comment]
habe das log hier gelöscht und lösche es auch bei mir, wenn ich es nicht mehr benötige...

**Comment by aruttkamp** [comment]
TOP - Ein Versand von MEssages - an alle user - erfolgt übrigens mit der 2.9.3

**Comment by rg-engineering** [comment]
kannst du nochmal probieren? ich kann es leider hier nicht vernünftig testen...

**Comment by aruttkamp** [comment]
Gerne, aber erst gleich. Hab Vorstandssitzung

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by aruttkamp** [comment]
Ich vermisse diesen Eintrag im LOG 
>>adapter.log.debug('telegram-instance: ' + inst)
Den müsste ich doch "eigentlich" sehen , oder irre ich mich ?

**Comment by rg-engineering** [comment]
Kannst du bitte mit STRG-Umschalt-I die Konsole deines browsers (firefox, chrome) öffnen?
Wenn du dann den admin vom HeatingControl öffnest, solltest du dort sehen, was gesendet wurde...

Bei mir sieht das so aus:
![grafik](https://user-images.githubusercontent.com/8238668/197042479-85c35a67-ac12-47e0-8f0a-9d1902fe42a1.png)

Bei dir sollten die user-Daten dort auftauchen

**Comment by aruttkamp** [comment]
Sieht bei mir ähnlich aus…

***@***.***

Wenn ich unten dann telegram.0 wähle kommt das hier :
***@***.***

***@***.***



Von: rg-engineering ***@***.***>
Gesendet: Donnerstag, 20. Oktober 2022 21:42
An: rg-engineering/ioBroker.heatingcontrol ***@***.***>
Cc: Andreas Ruttkamp ***@***.***>; Mention ***@***.***>
Betreff: Re: [rg-engineering/ioBroker.heatingcontrol] Benachrichtigung Telegram - Auswahl Empfänger (Issue #323)


Kannst du bitte mit STRG-Umschalt-I die Konsole deines browsers (firefox, chrome) öffnen?
Wenn du dann den admin vom HeatingControl öffnest, solltest du dort sehen, was gesendet wurde...

Bei mir sieht das so aus:
[grafik]<https://user-images.githubusercontent.com/8238668/197042479-85c35a67-ac12-47e0-8f0a-9d1902fe42a1.png>

Bei dir sollten die user-Daten dort auftauchen

**Comment by rg-engineering** [comment]
Hab Telegram nun doch bei mir installiert zum testen. Es sieht nun so aus:

![grafik](https://user-images.githubusercontent.com/8238668/197226129-d11f13c6-9c18-44e0-a5c1-b245bef4b5b0.png)

**Comment by aruttkamp** [comment]
Jepp ! Jetzt passt es ! Es erscheinen alle User und nur der gewählte bekommt die Nachricht ! 
Bug ist also behoben ! 
Vielen Dank !
