### ISSUE TITLE
Hysterese eigene On - Off Werte setzen

### ISSUE THREAD

**Issue by Trafficlight319** [rg-engineering/ioBroker.heatingcontrol#324]
Hallo,

ist es möglich eine eigene Hysterese zu erstellen ggf. die Funktion Vollständig abzuschalten? Vielleicht ein dritter Regler typ "Hysterese" diese dann komplett selbst definiert werden kann bzw. Wann Ein-und Ausschaltgrenzen sind. 

Ich habe das Problem das meine Infrarot Heizung den Raum nicht über 23°C schafft aufzuheizen. Sobald ich das Thermostat auf 22°C stelle muss die Heizung >23°C kommen um abzuschalten. Gerne würde ich eine Grenze definieren von +/- 0,5°C oder On/Off direkt bei 22°C.

**Comment by rg-engineering** [comment]
> Vielleicht ein dritter Regler typ "Hysterese" diese dann komplett selbst definiert werden kann bzw. Wann Ein-und Ausschaltgrenzen sind.

Man kann doch jetzt schon die Hysterese einstellen:

![grafik](https://user-images.githubusercontent.com/8238668/196022235-5e6b0f04-89a9-4c56-bbdf-a4eeaba07b43.png)

Was fehlt noch?

**Comment by Trafficlight319** [comment]
Funktioniert leider nicht so wie gewünscht. Selbst wenn ich 0,5 eingebe schaltet er nicht immer bei einer differenz von 0,5.

**Comment by rg-engineering** [comment]
ja, dann sollten wir herausfinden, warum es nicht richtig funktioniert.
Kannst du einen debug-log von dem Vorgang erzeugen und mir zukommen lassen?

**Comment by Trafficlight319** [comment]
Hallo rg-engineering,

wenn du mir sagen kannst wie ich ein debug-log dir zusenden kann, werde ich das tun.

**Comment by rg-engineering** [comment]
schicke es an webmaster@rg-engineering.eu danke

**Comment by Trafficlight319** [comment]
Ganz dummer Fehler von mir. Bei der aktuellen IST Temperatur ist der flasche Sensor ausgewählt. Sorry 

Es funktioniert so wie es sein soll :)
