### ISSUE TITLE
Mehrere Fenstersensoren

### ISSUE THREAD

**Issue by Eistee82** [rg-engineering/ioBroker.heatingcontrol#327]
**Describe the bug**  
Wenn ich in einem Raum mehrere Fensterkontakte habe und nacheinander beide Fenster öffne und dann das erste geöffnete wieder schließe wird mir in der Visu angezeigt das alle Fenster geschlossen sind. Die Reihenfolge welches Fenster ich zuerst öffne macht dabei keinen Unterschied. Es wird außerdem auch nur ein offenes Fenster angezeigt obwohl z.B. 2 Fenster im Raum geöffnet sind.

**Versions:**  
 - Adapter version: 2.9.2
 - JS-Controller version: 4.0.23
 - Node version: v16.17.1
 - Operating system: debian

**Comment by rg-engineering** [comment]
Kannst du von dem Vorgang ( Fenster 1 öffnen, Fenster 2 öffnen, Fenster 1 schliessen, ...) ein debug log mitschreiben und mir zukommen lassen?
>Es wird außerdem auch nur ein offenes Fenster angezeigt obwohl z.B. 2 Fenster im Raum geöffnet sind

Wo würdest du diese Anzeige erwarten? Eigentlich wird doch nur angezeigt, dass irgendein Fenster offen ist, unabhängig von der Anzahl...

**Comment by Eistee82** [comment]
Hier würde ich die Anzahl insgesamt erwarten. Es sind im Wohnzimmer 2 Fenster geöffnet und in den anderen Zimmern jeweils nur eins. Macht in Summe 4 offene Fenster:
![image](https://user-images.githubusercontent.com/1881217/196051216-ca463039-cca1-4c6a-9824-e50fa7de5e5c.png)

Hier noch das LOG:
https://gist.githubusercontent.com/Eistee82/1d84b5b159a5bcf5edaa631f9fb0f6f9/raw/d095579397088a98bfcc05187740f23153831a21/gistfile1.txt

- Raum Wohnzimmer (insgesamt 4 Fensterkontakte)
- Fenster (mqtt.0.zigbee2mqtt.ez.Fenster.rechts.contact) geöffnet
- Raumstatus von Wohnzimmer wechselt auf Fenster offen
- Fenster (mqtt.0.zigbee2mqtt.ez.Fenster.links.contact) geöffnet
- Raumstatus unverändert (2 Fenster im Wohnzimmer geöffnet)
- Fenster (mqtt.0.zigbee2mqtt.ez.Fenster.rechts.contact) geschlossen
- Raumstatus von Wohnzimmer wechselt auf Fenster geschlossen (Es ist aber noch ein Fenster offen)
- Fenster (mqtt.0.zigbee2mqtt.ez.Fenster.links.contact) geschlossen
- Raumstatus bleibt auf alle Fenster geschlossen

**Comment by rg-engineering** [comment]
ich habe eine Idee, bin mir nur nicht sicher...
Versuche mal ein kleines WindowOpenDelay  und WindowCloseDelay zu konfiguriern und probiere nochmal. Wenn es so funktioniert, weiß ich wo ich suchen muss...

**Comment by Eistee82** [comment]
OK Habe mal für öffnen und für schließen 5sek Verzögerung eingestellt. Folgendes habe ich festgestellt:

Versuch 1:
- 1. Fenster öffnen
- 2. Fenster 2sec später öffnen (Raumstatus noch Fenster geschlossen)
- Raumstatus Fenster offen 5sec nachdem das erste Fenster geöffnet wurde
- 1. Fenster schließen
- Raumstatus bleibt auf Fenster offen
- 2. Fenster schließen
- Raumstatus geht 5sec nach dem 2. Fenster auf Fenster geschlossen

Versuch 2:
- 1. Fenster öffnen
- Raumstatus Fenster offen 5sec nachdem das erste Fenster geöffnet wurde
- 2. Fenster öffnen (Raumstatus schon auf offen)
- 1. Fenster schließen
- Raumstatus geht auf Fenster geschlossen obwohl Fenster 2 noch offen ist.
- 2. Fenster schließen
- Raumstatus bleibt auf Fenster geschlossen

Fazit: Wenn der Raumstatus auf Fenster offen steht und dann ein 2. Fenster geöffnet wird funktioniert es nicht. Wenn der Raumstatus noch auf Fenster geschlossen steht und ein 2. Fenster geöffnet wird dann funktioniert auch das Fenster schließen wie es soll.

**Comment by rg-engineering** [comment]
kannst du die 2.9.3 hier aus github mal probieren? Diesmal wieder ohne delay. Ich habe hier zwar getestet, aber sicher bin ich nicht...
