### ISSUE TITLE
exception in UpdateVisState

### ISSUE THREAD

**Issue by Quarkmax** [rg-engineering/ioBroker.heatingcontrol#331]
**Describe the bug**  
Ich bekomme im Log immer  nach Neustart des Adapters ein: _exception in UpdateVisState [TypeError: Cannot read properties of undefined (reading 'status')]_ . Ich nutze die Ansicht in Pittinis VIS MoSu, also jeder Tag gleich. Der Adapter selbst funktioniert soweit. Ich finde leider nichts, was nicht definiert wäre. 
Bei der Ausgabe der Änderung (LOG oder Pushover) erscheint auch beispielhaft für Wohnzimmer: _Wohnzimmer set thermostat undefined to 21_

**Versions:**  
Adapter version: 2.9.2
JS-Controller version: 4.0.23
Node version: v16.17.1
Operating system: ubuntu

**Comment by rg-engineering** [comment]
das passiert nur beim start des Adapters, später nicht mehr?

**Comment by Quarkmax** [comment]
Ja, nur beim Start/Restart. Die undefinierte Temperaturänderung jedesmal bei Temperaturänderungen (manuell und automatisch zu den Schaltzeiten)

**Comment by rg-engineering** [comment]
sollte mit der 2.9.3 hier in github behoben sein...

**Comment by Quarkmax** [comment]
Fehler _exception in UpdateVisState_  taucht nicht mehr auf. Soll ich für _Wohnzimmer set thermostat undefined to 21_ ein neues Issue aufmachen, oder bist du da dran?

**Comment by rg-engineering** [comment]
dafür brauchst du kein issue aufmachen, das mache ich mit...

**Comment by Quarkmax** [comment]
Dankeschön 😊
