### ISSUE TITLE
Telegram Benachrichtigung

### ISSUE THREAD

**Issue by lindi200000** [rg-engineering/ioBroker.heatingcontrol#336]
Hallo,
in der Version 2.9.3 wird bei den Telegram Benachrichtigungen die Objekt-ID Zieltemperatur immer angezeigt. Damit man es besser lesen kann, währe aber der "Thermostat Name" besser.

Also statt:
HeatingControl:
Büro set thermostat  hm-rpc.1.000AxxxxxxxxxCC.1.SET_POINT_TEMPERATURE to 19

Neu:
Büro set thermostat  Heizung Büro to 19

Nice to have währe auch noch, das sich die Benachrichtigung an die Sprache vom IOB anpasst. 
So in etwa:
Büro Thermostat "Heizung Büro" wurde auf 19 geändert.

![image](https://user-images.githubusercontent.com/16406425/202918695-48d3817b-774d-4904-8cc5-c1f5f505a3d7.png)

VG
Lindi

**Comment by rg-engineering** [comment]
sollte mit 2.10.1 erledigt sein

**Comment by rg-engineering** [comment]
Zeichensatz passt wohl noch nicht immer...

**Comment by rg-engineering** [comment]
ist erledigt mit 2.10.4
