### ISSUE TITLE
Fehler bei Thermostateinstellung

### ISSUE THREAD

**Issue by FrankSuFra** [rg-engineering/ioBroker.heatingcontrol#337]
Version 2.9.3

Wenn ich in den Haupteinstellung follgendes einstelle:

![Bug1](https://user-images.githubusercontent.com/119103502/204080652-699fa90b-a0a5-4e4e-a079-a9f7165def02.jpg)

Bekomme ich folgende Fehlermeldung:

` State  "heatingcontrol.0.Profiles.1.Wohnraum.Sat.Periods.27.Temperature" has  no existing object, this might lead to an error in future versions`

Es wirdd auch die Temperatur nicht an die anderen Thermostate übertragen (geändert wurde Esszimmer):

![Bug2](https://user-images.githubusercontent.com/119103502/204080762-621010e8-2bd5-489d-bdb4-3dcbd4e6b1cf.jpg)

**Comment by rg-engineering** [comment]
Kannst du davon ein debug-log erzeugen? Nur mit der Fehlermeldung komme ich hier nicht weiter...

**Comment by FrankSuFra** [comment]
Kann ich dir das per eMail zusenden?
Ist zu lang für hier...

**Comment by FrankSuFra** [comment]
[Log.zip](https://github.com/rg-engineering/ioBroker.heatingcontrol/files/10096078/Log.zip)
okay... zip geht :)

**Comment by rg-engineering** [comment]
Ich sehe das Problem, die Berechnung des aktuellen Profil-Abschnittes für Samstag funktioniert hier nicht. Das ändere ich in der nächsten Version (2.10).

> Es wirdd auch die Temperatur nicht an die anderen Thermostate übertragen (geändert wurde Esszimmer):

Du hast hier einen Raum (Wohnraum) mit mehreren Thermostaten? Laut log kommt die Änderung vom Thermostat im "Wohnraum"...

**Comment by FrankSuFra** [comment]
Ja, im Raum "Wohnraum" gibt es 3 Thermostate.
Wohnzimmer, Esszimmer, Küche.
Ist aber ein großer zusammenhängender Raum.

**Comment by rg-engineering** [comment]
Mit der aktuellen Version 2.10.0 hier in github sollte das Problem behoben sein. Über feedback wäre ich dankbar...

**Comment by rg-engineering** [comment]
In my case "relative":
![grafik](https://user-images.githubusercontent.com/8238668/205508457-e329d920-36e2-412e-83b7-d2c14686600c.png)

**Comment by rg-engineering** [comment]
Du kannst von github installieren:

![grafik](https://user-images.githubusercontent.com/8238668/205699711-5695e25b-6a75-408d-b39f-038b69b6cd1c.png)
