### ISSUE TITLE
No windows Open Temperature

### ISSUE THREAD

**Issue by Haenk93** [rg-engineering/ioBroker.heatingcontrol#341]
I have No Data point for target temp if window is opened. 
when i open windows it says opened true but no change of Temperature

**Comment by rg-engineering** [comment]
Have you configured relative or absolute lowering?

![grafik](https://user-images.githubusercontent.com/8238668/205507113-91f00e63-945f-4ca7-a1a2-39b8ec4bbbfd.png)

**Comment by Haenk93** [comment]
Hi yes is on absolut. Where should the Data point be?

**Comment by rg-engineering** [comment]
in my case "relative":
![grafik](https://user-images.githubusercontent.com/8238668/205508488-dff26234-85ff-4098-aa65-7b8b2c27b9c2.png)

**Comment by Haenk93** [comment]
Mit relativ gehts

**Comment by rg-engineering** [comment]
es geht auch mit absolut ...
