### ISSUE TITLE
Aqara E1 mit ext Aqara Temp Sensoren. Temperaturen falsch

### ISSUE THREAD

**Issue by Haenk93** [rg-engineering/ioBroker.heatingcontrol#342]
Habe im Adapter Thermostat und externen Temp Sensor verlinkt.
Die Temperatur des Thermostats wird aber weiterhin über die Local Temp gesteuert nicht über den externen Sensor.
Sprich es wird viel zu warm.

Habe zum Testen einen Offset eingetragen aber dieser bewirkt nichts

**Comment by rg-engineering** [comment]
> Habe im Adapter Thermostat und externen Temp Sensor verlinkt.

Das ist keine Verlinkung! Die Ist-Temperatur des externen Sensors wird nicht zum Thermostat übertragen, das ist technisch nicht machbar. Stattdessen wird die Differenz des internen Temperatursensors am Thermostat mit dem externen Temperatursensor gebildet. Diese Differenz wird über einen Zeitraum gemittelt und als Offset der Solltemperatur hinzuaddiert. Wenn der externe Sensor regelmässig eine höhere Temperatur als der interne Sensor misst, wird die Solltemperatur um diesen Offset verringert...

Eine Offset manuell einzutragen hilft nicht wirklich, da der offset ständig neu berechnet wird.

Wenn du debug-Mode einstellst, siehst du die Details der Berechnung. Das ganze wurde mehrfach im [Forum ](https://forum.iobroker.net/topic/22579/test-adapter-heatingcontrol-v2-9-x)diskutiert und auch hier als [issue ](https://github.com/rg-engineering/ioBroker.heatingcontrol/issues/182)besprochen
