### ISSUE TITLE
CurrentTimePeriod passt nicht zum Wochentag

### ISSUE THREAD

**Issue by janwilke** [rg-engineering/ioBroker.heatingcontrol#343]
Hallo zusammen,

ich nutze v2.9.3 vom Adapter und bin eigentlich sehr zufrieden.
Nun habe ich festgestellt, dass der Wert für heatingcontrol.0.vis.RoomValues.CurrentTimePeriod nicht mit der VIS übereinstimmt.
Scheinbar gibt es ja pro Tag 5 Datenwerte:
Mo 1-5, Die 6-10, Mi 11-15, Do 16-20, Fr 21-25, Sa 26-30, Su 31-35
Ich bekomme aber als Wert heute (Dienstag) statt 8 die 33 ausgegeben, was dazu führt, dass wie am Sonntag geheizt wird.
Gibt es dazu irgendwo einen Datenpunkt, dass die Zählung anpasst?

Danke und viele Grüße

**Comment by rg-engineering** [comment]
In meinem Fall passt es aber:
![grafik](https://user-images.githubusercontent.com/8238668/205992907-f0a24b45-5cf6-42bf-8ccc-9d5c3a15e117.png)

Ich nutze
![grafik](https://user-images.githubusercontent.com/8238668/205993022-5f852d39-af2f-4fe5-bb2c-dac926566cac.png)


Bitte beachte den Unterschied zu
`heatingcontrol.0.vis.RoomValues`

Alles darunter wird nur aktualisiert, wenn 
`heatingcontrol.0.vis.ChoosenRoom`
geändert wird.


Was bedeutet eigentlich 
> für heatingcontrol.0.vis.RoomValues.CurrentTimePeriod nicht mit der VIS übereinstimmt

Nutzt du die Pittini-Vis? Dafür sind die Datenpunkte unterhalb heatingcontrol.0.vis. gedacht...

**Comment by janwilke** [comment]
Moin, 

danke für deine Info und nachschauen, dann passt es mit meiner Erwartungshaltung überein.

Komischerweise stimmt es heute auch wieder - Slot 1, Period 11.
Sehr merkwürdig. Schicke mir nun die beiden Werte mal per Telegram zu Prüfung die nächste Woche über.

Zu deiner Frage: Ich benutze die VIS von Pittini und habe nur einen Raum hinterlegt. Schaue auch unter den 0.VIS.xxx Datenpunkten.

Danke und Grüße!!

**Comment by janwilke** [comment]
Fehler kann nicht mehr nachgestellt werden.
