### ISSUE TITLE
Status ist nicht korrekt, wenn Fenster geöffnet und wieder geschlossen wird und Änderung vom Thermostat kommt

### ISSUE THREAD

**Issue by rg-engineering** [rg-engineering/ioBroker.heatingcontrol#347]
Zweites Problem welches ich habe ist, dass sobald ein Fenster geöffnet wird, springt der Status "State" im Raum auf "auto WindowOpen". Wenn das Fenster geschlossen wird, dann ist dieser wieder auf "auto".
Ändert man dann aber manuell die Temperatur des Thermostats wird dieser state-Wert wieder auf "auto WindowOpen" gesetzt anstatt auf "manuel"
Habe das Problem in allen Räumen wo ich die HM-Thermostate mit den Fenstersensoren und den Wandthermostaten verwende.

Ja, auch wenn ich am Thermostat selbst die Temperatur ändere, wird der State-Datenpunkt auf "auto WindowOpen" geändert.
Das komische ist, es wird nur dieser State-Datenpunkt geändert. Der Datenpunkt "WindowIsOpen" bleibt auf false, was ja auch korrekt ist.

Wenn ich den Adapter neu starte, dann passt wieder alles. Bis wieder ein Fenster geöffnet wird.

**Comment by rg-engineering** [comment]
sollte mit 2.10.1 erledigt sein

**Comment by rg-engineering** [comment]
Kannst du mir ein log bzgl. der HmIP-eTRV-2 machen? Da ist anscheinend das timing anders, wann die Thermostate ihre geänderte Soll-Temperatur zurück senden.

Die Kodierung von °C ändere ich, das hängt mit einem anderen Ticket zusammen. Dort geht es darum, die Benachrichtigunegn z.Bsp. über Telegram in der richtige Sprache zu senden. Da muss ich die Kodierung noch auf UTF8 ändern...

**Comment by ManfredHi** [comment]
Ok, hab das jetzt wieder mit nur einem Thermostat durchgespielt. Alle anderen Thermostate habe ich in HC inaktiv gesetzt.
Anbei das debug-logfile.

[2022-12-10-heatingcontrol-debug.log](https://github.com/rg-engineering/ioBroker.heatingcontrol/files/10200582/2022-12-10-heatingcontrol-debug.log)

**Comment by ManfredHi** [comment]
Mir ist noch aufgefallen, dass bei den HmIP-eTRV-2 Thermostaten beim Fenster öffnen eine Sekunde vorher der Wert auf die Fenster-Offen-Temperatur (bei mir 12°) gestellt wird. Dadurch wird der Status "manuell" gesetzt, danach kommt ein "manuel WindowOpen" und beim schließen wird sie dann wieder auf "manuel" und diese 12° eingestellt. Der Fehler dürfte also am Beginn beim Fenster Öffnen liegen.

Hier das log aus der Pittini-View:
![image](https://user-images.githubusercontent.com/103682996/206893631-dd0cd28f-36dd-4c98-a7e0-74d079ae755c.png)

**Comment by rg-engineering** [comment]
das macht die Sache nicht einfacher... Im Moment gehe ich davon aus, dass die Info "Fenster ist offen" vom Sensor direkt schneller im Adapter ankommt, als die abgesenkte Temperatur vom Thermostat. Wenn das in dem Falle hier anders ist, funktioniert das so nicht mehr...

**Comment by ManfredHi** [comment]
Ist es normal, dass beim öffnen der Fenster generell vorher der Status auf geöffnet gesetzt wird mit der alten Temperatur und dann gleich anschließend auf die richtige Temperatur. Bei einem Thermostat ist das z.B. beim öffnen des fenster von "auto WindowOpen" auf "manuel WindowOpen" gegangen.

![image](https://user-images.githubusercontent.com/103682996/206914365-6b92d774-7196-4085-b26c-f11c6d813079.png)

**Comment by rg-engineering** [comment]
Der Ablauf im Zusammenhang mit "Thermostat behandelt Fenster offen" ist folgender:
* Fenster geht auf
* Fenstersensor meldet "ist offen" an den Adapter
* Adapter setzt Status "WindowOpen"
* für die nächsten 10 Sekunden werden alle Änderungen der Zieltemperatur, welche vom Thermostat kommen, als Absenkung aufgrund Fenster offen betrachtet. Die Temperatur wird entsprechend übernommen, Status bleibt aber auf "auto"
* danach eintreffenden Änderungen der Zieltemperatur vom Thermostat werden als manueller Eingriff gewertet. somit wird auch der Status von "auto" auf "manual" geändert
Das ist genau das, was wir bei dir hier in den logs sehen....

**Comment by ManfredHi** [comment]
Ok, aber warum verhält sich dann der Heizkörper im Schlafzimmer anders, als die in den Kinderzimmern? Im Schlafzimmer hat er zuerst von auto auf manual gesetzt und das ist ja nicht richt.

**Comment by rg-engineering** [comment]
weil die reduzierte Temperatur erst nach 11 Sekunden vom Thermostat am Adapter angekommen ist...

**Comment by ManfredHi** [comment]
Wenn ich im Schlafzimmer das FEnster öffne, ist der Heizkörper innerhalb einer Sekunde auf die 12°C eingestellt. Aber es dauert jedesmal zwischen 11 und 13 Sekunden bis das im iobroker ankommt.
Hab jetzt mal den Thermostat zurückgesetzt. Muss aber jetzt warten weil der Duty Cycle auf 99 ist.

**Comment by ManfredHi** [comment]
Hab jetzt diesen Thermostat zurückgesetzt und neu Verbunden. Keine Änderung. Es dauert jedesmal exakt 13 Sekunden bis die Rückmeldung an ioBroker kommt (obwohl der Thermostat sofort die verringerte Temperatur anzeigt).
Wäre es möglich, dass man das Zeitinterval, wie lange HC warten soll, in der Configuration selbst einstellen kann? Dann wäre man etwas flexibler.

**Comment by rg-engineering** [comment]
entweder verlängere ich es auf 20 Sek mache es einstellbar.
Schon komisch, dass sich da bisher noch niemand dazu gemeldet hat...

**Comment by ManfredHi** [comment]
ja ich weiß auch nicht, bin durch zufall draufgekommen, dass die temperatur nach dem öffnen nicht richtig zurückgestellt wird.
am besten wäre es einen standardwert (von mir aus 10 sek.) vorzugeben und den aber einstellbar machen, damit man das im fall der fälle selbst abändern kann.

**Comment by ManfredHi** [comment]
hab jetzt testweise mal den wert in der database.js in Zeile 482 auf 15000 erhöht. Damit hat es auch auf diesem Heizkörper der immer Probleme macht, funktioniert. 15 Sekunden ist zwar lang. Wenn das in den Geräten für jeden Thermostat einstellbar wäre, wäre das optimal.

**Comment by rg-engineering** [comment]
>Wenn das in den Geräten für jeden Thermostat einstellbar wäre

das geht nicht. es ist ja nur ein Timer pro Raum, und umbauen damit wir einen Timer pro Thermostat bekommen, macht wohl keinen Sinn? Ich würde die Zeit pro Raum einstellbar machen, oder noch einfacher global für alle Räume...

**Comment by ManfredHi** [comment]
> Ich würde die Zeit pro Raum einstellbar machen, oder noch einfacher global für alle Räume

Dann bitte die Möglichkeit pro Raum. Das würde helfen, da ich sowieso nur einen Thermostat pro Raum habe. Generell eine so lange Zeit ist doch auch nicht sinnvoll, den es gibt Thermostate wo das sogar unter 10 Sekunden ist.

**Comment by rg-engineering** [comment]
sollte nun erledigt sein.
