### ISSUE TITLE
!!ChangeStatus not implemented yet MinimumTemperature

### ISSUE THREAD

**Issue by rg-engineering** [rg-engineering/ioBroker.heatingcontrol#348]
Wenn ich den entsprechenden datenpunkt der Minimaltemperatur über ein Script setze, erscheinen die folgenden Fehler im Logfile:

`2022-12-10 22:53:30.280 - error: heatingcontrol.0 (994672) !!ChangeStatus not implemented yet MinimumTemperature Windfang value 4.5`

**Comment by SuperNils** [comment]
Gleiches gilt für den Datenpunkt TemperatureIfNoHeatingPeriod. Wäre cool wenn das auch gefixt wird

**Comment by rg-engineering** [comment]
Beide Werte werden intern bereits verwendet, die Fehlermeldung ist also nicht nötig und kann ignoriert werden.
In 2.10.2 wird die Fehlermeldung entfernt...

**Comment by rg-engineering** [comment]
ist erledigt mit 2.10.3
