### ISSUE TITLE
2. Instanz kann keine Geräte hinzufügen 

### ISSUE THREAD

**Issue by zahnheinrich** [rg-engineering/ioBroker.heatingcontrol#356]
In einer zweiten Instanz können in der Haupteinstellung keine neuen Geäte hinzugefügt werden. Beim Druck auf das "+" Zeichen geschieht nichts.
Getestet unter mehreren Browsern, alle Adapter uptodate.

**Comment by rg-engineering** [comment]
solved with 2.10.5
