### ISSUE TITLE
Add Notifications to Discord 

### ISSUE THREAD

**Issue by bloodstar** [rg-engineering/ioBroker.heatingcontrol#359]
Being able to send notifications to Telegram was a nice step, but I feel that Discord with multiple channels and more sophisticated bots are a better solution.
Any chance that this will be implemented?

**Comment by rg-engineering** [comment]
@bloodstar I have experimentally implemented discord. would you try it out?

**Comment by bloodstar** [comment]
@rg-engineering yes sure! Thanks for the effort.
Heating period is over, but I will check it out. 

1. Can I just use the latest build v2.11.0?
2. Any settings needed in the Discord adapter?
3. Can I use any User Tag and leave "Waiting before send" empty?

**Comment by rg-engineering** [comment]
-     Can I just use the latest build v2.11.0?
yes, just use latest version here in github
-     Any settings needed in the Discord adapter?
no
-     Can I use any User Tag and leave "Waiting before send" empty?
you can use any user tag, but this is what I want to test. "Waiting before send" I would set to 15 sec, don't leave it blank.

**Comment by bloodstar** [comment]
Hi, sorry for the delay. Just came back from vacation.
Took me a moment to figure out that you are using direct messages. But this seems to work fine. 

I am not sure about two things:

1. What is the point of the "Waiting before send" delay. 
If I change a value, and change it again before the wait timer is over, I will still get notifications for both events. Shouldn't it work as a debounce function? 
2. Can I send a message to a Discord channel, and not just to a User?

**Comment by rg-engineering** [comment]
>     What is the point of the "Waiting before send" delay.

yes, like you expect. need to check again

>     Can I send a message to a Discord channel, and not just to a User?

not yet, need to implement it

**Comment by rg-engineering** [comment]
@bloodstar can we close the issue here?
