### ISSUE TITLE
Vermeidung hoher DutyCyle durch senden bei Temperatur Änderung

### ISSUE THREAD

**Issue by AlexanderSch90** [rg-engineering/ioBroker.heatingcontrol#36]
Es scheint, als würde die Temperatur bei jedem Event an alle Thermostate gesendet werden, auch wenn sich die Temperatur gar nicht ändert. Ich habe zu mindestens oft einen hohen senden wert und die Befehle werden deshalb sehr zeit verzögert gesendet. Beispiel: Fenster auf = Erst nach ein paar Minuten wird die Temperatur geändert...

Ich denke man sollte die Last möglichst gering halten und deshalb nur dann "steuern" wenn es auch wirklich eine Änderung gab.

**Comment by DutchmanNL** [comment]
ist mir auch aufgefallen, ich sehe 2 scenarios : 

- mehrere Thermostate werden gleichzeitig geaendert
sollte im Homematic adapter gellest werden das diese hintereinander abgearbeitet werden wen das allgemein zu Problemen feuert.

- bereits stehende werte werden nochmal geschrieben
Der adapter sollte nur einen wert setzen wen der zu setzende wert anders ist als der jetzige wert.
Das kan man realisieren durch erste de wert ab zu fragen und vergleichen, da per ASYC/AWAIT

**Comment by rg-engineering** [comment]
> bereits stehende werte werden nochmal geschrieben

ja, aber das sollte ja dann auch für die auslösende Quelle des events gelten. Was hier passiert ist doch, dass ein Fenstersensor jede Minute sagt "ich bin noch zu". Das führt dann im Adapter dazu, dass wieder die gleiche Zieltemperatur geschrieben wird. Wenn der Sensor nur Änderungen senden würde, würde die gesamte Systemlast reduziert....

**Comment by Seraphis411** [comment]
> > bereits stehende werte werden nochmal geschrieben
> 
> ja, aber das sollte ja dann auch für die auslösende Quelle des events gelten. Was hier passiert ist doch, dass ein Fenstersensor jede Minute sagt "ich bin noch zu". Das führt dann im Adapter dazu, dass wieder die gleiche Zieltemperatur geschrieben wird. Wenn der Sensor nur Änderungen senden würde, würde die gesamte Systemlast reduziert....

Aber außer diesem fall werden die Werte auch alle neu geschrieben (laut log neu berechnet), wenn ein Sensor geöffnet wird, der nur zu einem der Räume gehört, also nur einen Teil der Thermostate betrifft. Genauso wenn bei einem der Räume durch eine definierte Uhrzeit eine neue Temperatur gesetzt wird, dann werden auch alle anderen Räume neu geschrieben.

**Comment by DutchmanNL** [comment]
hmm der code knallt immer alle Situationen durch, effizienter waehren nur di getroffenen Geräte

**Comment by Denkra** [comment]
Das Problem habe ich bei mir aber auch. Teilweise können Temperaturen gar nicht geschrieben werden da der Duty-Cycle erreicht ist. Ich habe im Schlafzimmer fast immer das Fenster offen und er schreibt aber wirklich jede Minute ALLE Werte neu. Ist klar das die Thermostate dann irgendwann aussteigen.

**Comment by AlexanderSch90** [comment]
> Das Problem habe ich bei mir aber auch. Teilweise können Temperaturen gar nicht geschrieben werden da der Duty-Cycle erreicht ist. Ich habe im Schlafzimmer fast immer das Fenster offen und er schreibt aber wirklich jede Minute ALLE Werte neu. Ist klar das die Thermostate dann irgendwann aussteigen.
> 
> P.S.: Gerade gesehen das er generell jede Minute die States sendet auch wenn alle Fenster zu sind also er wirklich strikt nach Heizplan geht und keine Faktoren zutreffen die für eine manuelle änderung der Temperatur sorgen.

Das dies jede Minute passiert, kann ich nicht bestätigen. Ich vermute das liegt bei dir daran, dass du einen "Trigger-Datenpunkt" wie z.B. "Pfad zum Feiertag - Adapter oder einem anderen Datenpunkt" verwendest, welche jede Minute aktualisiert wird. Heatingcontrol wird bei jeder Aktualisierung die Werte neu senden, auch wenn es gar keine Änderung gab. Genau das ist ja das was im Adapter umgeschrieben werden muss...
