### ISSUE TITLE
Allgemeine Probleme

### ISSUE THREAD

**Issue by duczz** [rg-engineering/ioBroker.heatingcontrol#360]
Hallo,

seit längerem such ich nach einer richtig Erklärung bezüglich des Offsets, bzw. des externen Temperatursensors.

Woran erkenn ich ob der Offset zwischen Thermostattemperatur und Temperatursensors wirklich berücksichtigt wird.
Ich seh am Thermostat keine Änderung, auch der Offset ist immer auf 0

**Comment by rg-engineering** [comment]
siehe
https://github.com/rg-engineering/ioBroker.heatingcontrol/issues/182
Das war das Original-issue, nachdem das Feature implementiert wurde...

Im debug-log sieht man, was berechnet wird...

**Comment by duczz** [comment]
Der Offset geht default auf Kommastellen (z.b. 1.5), kann man es so hinterlegen, das er dies nur macht wenn es so auch in den Settings hinterlegt ist und ansonsten volle Schritte geht, sprich dann auf 2 aufrundet?

**Comment by duczz** [comment]
Des Weiteren scheint der Offset nicht zwischen Minus-Temp und Plus-Temp zu unterscheiden.
Der Raum müsste derzeit 19 Grad haben, am regler hat er aber 23, der Offset steht aber auf +3,5 Grad, überseh ich was?

![image](https://user-images.githubusercontent.com/25475385/217739051-75aa9a50-c186-4881-98a7-884baf91371b.png)
