### ISSUE TITLE
Fehlermeldung in telegram 

### ISSUE THREAD

**Issue by Klaus101265** [rg-engineering/ioBroker.heatingcontrol#362]
Ich bekomme vom HeatingControl Adapter in telegram immer folgende Meldung:

HeatingControl:
extended Actor Handling: Thermostat Wintergarten1.SET_POINT_TEMPERATURE hm-rpc.0.XXXXXXXXX.1.SET_POINT_TEMPERATURE no success after trial 6 because  ack not set! {"val":13,"ack":false,"ts":YYYYYYYYYYY"q":0,"from":"system.adapter.heatingcontrol.0","user":"system.user.admin","lc":ZZZZZZZZZZ}

Was bedeutet das?

**Comment by rg-engineering** [comment]
Hintergrund siehe https://github.com/rg-engineering/ioBroker.heatingcontrol/issues/306

Man kann den check aber auch abschalten:

![grafik](https://user-images.githubusercontent.com/8238668/220418014-200262f7-c9ab-4c70-b1fb-25dd78829cf5.png)
