### ISSUE TITLE
Auffälligkeiten - Unit fehlt bei TemperatureOverride und Falschanzeige bei CurrentTimePeriod

### ISSUE THREAD

**Issue by nukleuz80** [rg-engineering/ioBroker.heatingcontrol#363]
**Describe the bug**  
1. Unit °C --> fehlt bei: heatingcontrol.0.Rooms.XXXXXX.TemperaturOverride
2. Zeigt 8 bei Periode 3 --> heatingcontrol.0.Rooms.Bad.CurrentTimePeriod

**To Reproduce**  
1. Gehe zu den o.g. Objekten eines Raums

**Expected behavior**  
1. Erwartet hätte ich die Unit °C
2. Hier erwarte ich eine 3 NICHT 8

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/43496030/220115127-2aaca8c4-90f4-4083-9528-837e620db690.png)

**Versions:**  
 - Adapter version: 2.10.6
 - JS-Controller version: 4.0.26
 - Node version: 16.19.0
 - Operating system: Debian 9

Danke vorab und bitte weiter so! :)

**Comment by rg-engineering** [comment]
unit in Override ist als Fehler akzeptiert.

CurrentTimePeriod ist richtig, das ist etwas anderes als ActiveTimeSlot! CurrentTimePeriod ist die aktuelle Periode in der Woche, also bei 5 pro Tag ist es der dritte Slot am Dienstag wenn man "jeden Tag separat" eingestellt hat. Bei dir ist es wahrscheinlich der dritte slot am Sonntag (wegen public holiday)

**Comment by nukleuz80** [comment]
Ok, danke für Aufklärung und die tolle Arbeit. 

Bin gerade dabei alles in Lovelace zu visualisieren...
