### ISSUE TITLE
Fehlender Datenpunkt

### ISSUE THREAD

**Issue by Pittini** [rg-engineering/ioBroker.heatingcontrol#37]
In den globalen Settings gibt es Datenpunkte für Urlaub anwesend und Urlaub abwesend. In den Profilsettings finde ich aber nur einen Datenpunkt für Urlaub abwesend. (=VacationAbsent Decrease). 
Grundsätzlich finde ich jedoch allgemein dass die Benennung der Datenpunkte  "unglücklich" ist und evtl. überdacht werden könnte. Beispiel: UrlaubAbwesend in den Globalen Settings heißt: VacationAbsent, Urlaub anwesend heißt: HolydayPresent, das ist verwirrend.
Gleiche seltsamkeit bei dem ProfilOrdnern: Su-So. Wofür steht hier das Su? Sollte das nicht ein Sa sein?

**Comment by rg-engineering** [comment]
@Pittini reicht die Beschreibung in der readme hier aus?
