### ISSUE TITLE
Integration Fenstersensor funktioniert nicht.

### ISSUE THREAD

**Issue by DaPeace** [rg-engineering/ioBroker.heatingcontrol#380]
Ich hab hier ein NSPanel als Thermostat (Temperatursensor + Relay) und einen Shelly DW als Fenstersensor. Der Fenstersensor ist im Raum hinterlegt. Bei den Objekten ist auch ersichtlich das das WindowIsOpen den Status wechselt allerdings ändert sich am Relay nichts wenn man das Fenster öffnet. Was muß man denn dafür noch alles tun das er die Heizung dann ausschaltet? Geht das dann nur im Automatik-Modus oder auch bei Manuell? Grüsse, Jan

**Comment by rg-engineering** [comment]
Das ganze geht über eine Temperaturabsenkung. Wenn das Fenster öffnet, muss eine Absenkung (relativ oder absolut) konfiguriert werden. Wenn dann die Ist-Temperatur über der abgesenkten Soll-Temperatur liegt, schaltet der Aktor aus.
