### ISSUE TITLE
Integration tado Thermostate

### ISSUE THREAD

**Issue by rg-engineering** [rg-engineering/ioBroker.heatingcontrol#4]
see forum
https://forum.iobroker.net/topic/22579/adapter-heatingcontrol/10

**Comment by CKMartens** [comment]
First tado-integration in the adapter testet. See forum: [https://forum.iobroker.net/topic/22579/adapter-heatingcontrol/40](https://forum.iobroker.net/topic/22579/adapter-heatingcontrol/40)

**Comment by CKMartens** [comment]
A question. Is it posible to act direkt trough tado API instead of trough the homebridge-adapter with the homebridge-plugin?
[The Tado API v2](http://blog.scphillips.com/posts/2017/01/the-tado-api-v2/)

**Comment by rg-engineering** [comment]
I do not intend to do that. The plan is to use existing hardware interfaces (like max !, homematic, ...), otherwise I have to implement all kinds of interfaces. Is there a restriction on the Homebridge adapter? Then it might be necessary to implement a Tado adapter ...

**Comment by CKMartens** [comment]
Ok thanks for you comment.

I am happy if you implant the function of tado via ham. Thanks for your work and time

**Comment by rg-engineering** [comment]
workaround (=manuelle Konfiguration) mit 0.1.0 zur Verfügung gestellt...

**Comment by CKMartens** [comment]
Die Steuerung von den tado Thermostaten funktioniert einwandfrei. Danke für deine Arbeit
