### ISSUE TITLE
States umlegen

### ISSUE THREAD

**Issue by Denkra** [rg-engineering/ioBroker.heatingcontrol#41]
Kann man nicht die States für "Absenkung abwesend", "Fenster offen absenkung", "Manuelle Temperaturänderung und die Zeit dazu" als Globale Parameter machen? Die Werte sind ja in jeder PEriode gleich aber man muss dann nicht jede einzelne Periode durchgehen um das einzustellen.

**Comment by rg-engineering** [comment]
solved with 0.3.6
