### ISSUE TITLE
Fehlauswertung Fenstersensoren

### ISSUE THREAD

**Issue by Pittini** [rg-engineering/ioBroker.heatingcontrol#42]
Ich habe in mehreren Zimmern Doppelfenster und somit auch 2 Kontakte. Diese lassen sich ja auch problemlos anlegen, zeigen aber ein eigenartiges Verhalten. Mach ich ein Fenster auf, erfolgt korrekte Absenkung, mach ichs wieder zu auch korrekte Solltemperatur. Mach ich jedoch beide Flügel auf, erfolgt wieder erstmal korrekte Absenkung. Mach ich jetzt von den beiden offenen eins zu, wird wieder auf Solltemp gestellt obwohl der 2te Flügel noch offen ist.

**Comment by rg-engineering** [comment]
mit V0.3.1 erledigt
