### ISSUE TITLE
Thermostate können nicht angelegt werden

### ISSUE THREAD

**Issue by Ahrenfelde** [rg-engineering/ioBroker.heatingcontrol#43]
Hallo,

leider kann ich mit der 3.0.0 aus github installiert keine Thermostate anlegen. Wenn ich OK drücke und danach wieder das Fenster öffne ist es wieder leer.
So kann ich den Adapter nicht benutzen.

Im Log bekomme ich folgendes:

> 

  |   |   |  
-- | -- | -- | --
heatingcontrol.0 | 2019-10-26 07:16:27.786 | error | (19745) exception in  main [TypeError: Cannot read property 'isActive' of null]

<

Hinweis: iobroker listet die version 2.3 als letze Aktuelle mit dem latest Verwahrungsort, die Version hat bei mir überhaupt nicht funktioniert, konnte noch nicht einmal das Fenster zur Thermostatinstallation öffnen.

Grüße
Jan

**Comment by rg-engineering** [comment]
Bitte ein komplettes log hier posten. Danke.
Im NPM (und das ist die Quelle, die iobroker verwendet) liegt noch die 0.2.3, die 0.3.0 bereite ich hier im github vor, ist aber noch nicht released...

**Comment by Ahrenfelde** [comment]
moin,

jetzt habe ich es hinbekommen. Habe noch mal einen extra Upload gemacht. Nun wird getestet :)

Grüße
Jan
