### ISSUE TITLE
Zusätzlicher Datenpunkt MinimalTemperatur

### ISSUE THREAD

**Issue by zahnheinrich** [rg-engineering/ioBroker.heatingcontrol#47]
Ich würde mir einen zusätzlichen Datenpunkt "MinimalTemperatur" wünschen, gerne global:
Zur Zeit kann ich nur Temperaturbeträge angeben, um die bei Abwesenheit/Urlaub abgesenkt wird.
Ich fahre unterschiedliche Temperaturen über den Tag verteilt. Diese Staffelung bleibt bei einer Absenkung um einen fixen Betrag erhalten, was für eine generelle Absenkung auf z.B. 18° im Urlaub/Ferienwohnung nicht gewünscht ist.
Gäbe es nun eine MinimalTemperatur von z.B. 18°, könnte ich die Absenkung für den Urlaubszeitraum dann z.B auf 10° einstellen. Wegen der Unterschwelle von 18° würden alle gestaffelten Temperaturen auf diesen gleichen Wert abgesenkt.

**Comment by rg-engineering** [comment]
solved with 0.3.6; absolute lowering is implemented...
