### ISSUE TITLE
Integration einer künstlichen Boost-Funktion

### ISSUE THREAD

**Issue by niiccooo1** [rg-engineering/ioBroker.heatingcontrol#487]
**Describe wanted Enhancement !**  
Die Funktion, nach Anpassung der Temperatur gemäß Periode, das Thermostat für eine gewisse Zeit auf maximale Temperatur zu stellen um den Raum schneller aufzuheizen.

**Why should we put effort in it ?**  
Einige Hersteller smarter Thermostate bieten diese Funktion bereits, die von innogy leider nicht. 
Einige große Räumen heizen sich nicht so schnell wie gewünscht. Daher sollten die Thermostate für eine gewisse Zeit voll aufgedreht werden.

**Comment by Pittini** [comment]
Würde ich mit der override Funktion abbilden. x Minuten auf 30 Grad gestellt, reißts das Thermostat auch voll auf.

**Comment by niiccooo1** [comment]
Müsste ich aber händisch machen. 
Automatisch wäre es smarter. Der Adapter kennt ja auch die Raumtemperatur. Der Boost könnte auch vorzeitig beendet werden, wenn die Ist Temp nahe der Soll Temo ist.

**Comment by cat1510** [comment]
Ich sehe hier leider nicht den Bedarf.
Heatingcontrol schaltet den Actuator ja nur ein.
Das Ganze würde nur greifen, wenn man Kontrolle über die Heizung hat.
Dann sehe ich es aber so, dass es zur Heizungssteuerung gehört.
Heatingcontrol = Heizungssteuerung, is mir schon klar…
Aber Heizungen sind halt was anderes als der Kessel wa?

Vielleicht musst du deine Umgebung noch mal ein bisschen genauer beschreiben, damit man den Bedarf besser erkennen kann. Shelly TRV hat auch Boost Funktion zum Beispiel, kommt aber gar nicht zum Einsatz, wenn man heating Control benutzt.

So long,

CAT

**Comment by niiccooo1** [comment]
Hallo Zusammen, 
Ich habe Probeweise über ein paar Tage eine „Boost Funktion“ simuliert. Scheint so das meine Thermostate den Raum auch nicht schneller aufheizen wenn ich den Soll auf 30 C als auf 21 C stelle.
