### ISSUE TITLE
Fehler im Log nach Neustart

### ISSUE THREAD

**Issue by MMeinhardt1** [rg-engineering/ioBroker.heatingcontrol#489]
Hi,

ich bekomme folgende Fehlermeldungen im Log nach einem Neustart.

2023-11-19 12:48:46.604 - error: heatingcontrol.0 (24504) ChangeStatusCmdList is longer then 60 entries, no new entry allowed -> skipped Dachboden Thermostats_Current [object Object]
2023-11-19 12:48:46.608 - error: heatingcontrol.0 (24504) ChangeStatusCmdList is longer then 60 entries, no new entry allowed -> skipped Lilly Thermostats_Current [object Object]

Von diesen beiden Einträgen erhalte ich jeweils ca. 150 mal das gleiche und danach ist Schluss, der Adapter ist ohne Einschränkung nutzbar.

Adapter V2.11.1
JS-Controller V5.0.16
Node.js V18.17.1

Beste Grüße
Michael

**Comment by rg-engineering** [comment]
passiert das nur bei Neustart, oder auch im Lauf? 
Das Problem scheint zu sein, dass zu viele Statusmeldungen im Adapter ankommen. Normalerweise bearbeitet der Adapter eine Statusmeldung nach der anderen. Damit keine verloren geht, baue ich eine Liste auf, die gefüllt wird, wenn während der Bearbeitung einer Meldung weitere eintreffen. Damit das ganze aber nicht überläuft, habe ich ein Limit für die Länge der Liste eingebaut. Dieses Limit schlägt hier zu ...

**Comment by rg-engineering** [comment]
in 2.12.0 steht das Limit nun auf 100...

**Comment by MMeinhardt1** [comment]
Hi,

ich habe auf 2.12.1 aktualisiert und jetzt sind keine Fehler mehr im Log.

Vielen Dank und ein schönes Wochenende

**Comment by MMeinhardt1** [comment]
Hi,
habe gerade auf 2.12.2 upgedated und es erscheinen wieder haufenweise Fehlermeldungen wie diese hier,
ChangeStatusCmdList is longer then 100 entries, no new entry allowed -> skipped Calvin Thermostats_Current {"val":20,"ack":true,"ts":1703759144459,"q":0,"from":"system.adapter.zigbee2mqtt.0","lc":1703759144459}

Vielen Dank

**Comment by MMeinhardt1** [comment]
Hi,
ich habe heute nach einem Neustart meines Zigbee2mqtt Adapters wieder eine Menge Fehlermeldungen im Log gehabt.
Liegt das Problem hier oder beim Z2M Adapter?

2024-01-23 20:26:39.667 - error: heatingcontrol.0 (1484) ChangeStatusCmdList is longer then 100 entries, no new entry allowed -> skipped Wohnzimmer Thermostats_Current {"val":21.4,"ack":true,"ts":1706037998806,"q":0,"from":"system.adapter.zigbee2mqtt.0","lc":1706037998806}


Vielen Dank

**Comment by rg-engineering** [comment]
Das Problem ist die Anzahl der Meldungen / Statuswechsel, die in einer sehr kurzen Zeit im Adapter eintreffen. Ich kann natürlich das Limit hier im Adapter weiter vergrößern, irgendwann dauert aber das Abarbeiten dieser vielen Meldungen so lange, dass der Adapter nicht mehr richtig funktioniert. Ich würde also mal schauen, warum (und vor allem welche) Meldungen so häufig auftauchen...

**Comment by c1328** [comment]
Ich hatte im Log auch diese Fehlermeldungen und habe mich auf die Suche begeben. Am Ende war es eine blöde Kombination von "Tuya Cloud Sync" und "Tuya IoT Sync", die dazu geführt hat, siehe -> https://github.com/Apollon77/ioBroker.tuya/issues/567

Seitdem ich das "Cloud Poll Interval" auf größer 120s habe, sind auch die Fehlermeldungen des Heatingcontrol Adapters weg.

**Comment by rg-engineering** [comment]
@MMeinhardt1 können wir das hier schliessen?

**Comment by MMeinhardt1** [comment]
Hi,

ich habe zwar noch keine Zeit gehabt den Fehlermeldungen auf die Schliche zu kommen.
Da andere User diese Fehlermeldungen ebenfalls bekommen haben und die Fehler nicht an Heating Control lag, denke ich wir sollten hier schließen. 
Ich melde mich mal zurück wenn ich Zeit gefunden habe woher die Meldungen kommen. 

Vielen Dank
