### ISSUE TITLE
Zimmerstatus zeigt als aktuelle Temperatur die des Heizkörperthermostats an und NICHT die des Raumsensors

### ISSUE THREAD

**Issue by ThorstenDtk** [rg-engineering/ioBroker.heatingcontrol#493]
Leider zeigt der Zimmerstatus in der Spalte 'aktuell' die aktuelle Temperatur des Heizkörperthermostate an statt die des Raumsensors. Zweck des Sensors/Wandthermostats ist es aber doch 'reale' Messwerte zu haben da die Temperaturmessung am Heizkörperthermostat ungenau (i.d.R. zu hoch) ist. Beispiel:

![grafik](https://github.com/rg-engineering/ioBroker.heatingcontrol/assets/35042154/3a1b0f9b-e057-4f86-a30b-11d65b99b9b7)
 Die Solltemperatur im Studio liegt bei 20 Grad, die am Raumsensor ebenfalls. Perfekt. Die Temparatur am Regler (Heizkörperthermostat) ist deutlich höher. Was OK ist weil ja die Temperatur am Raumsensor relevant ist.

Leider wird im Zimmerstatus jedoch als aktuelle Temperatur die des Thermostats und NICHT die des Raumsensors angezeigt:

![grafik](https://github.com/rg-engineering/ioBroker.heatingcontrol/assets/35042154/8622868b-4dee-4222-89c2-20f3982bbfc8)

Deshalb scheint es als sei die Temperatur zu hoch. Was jedoch nicht der Fall ist. cardHzngRooms stellt den Inhalt von

![grafik](https://github.com/rg-engineering/ioBroker.heatingcontrol/assets/35042154/ca9f1911-3bab-46a9-8c85-0a4a30cdf056)

dar. Und laut https://forum.iobroker.net/topic/22579/test-adapter-heatingcontrol-v2-12-x/2472 ist das 'hardcoded'.

Deshalb wäre es gut wenn entweder die Temperatur des Raumsensors angezeigt würde oder das konfigurierbar wäre.

**Comment by rg-engineering** [comment]
eigentlich sollte es so aussehen:
![grafik](https://github.com/rg-engineering/ioBroker.heatingcontrol/assets/8238668/bac8f107-7f07-4406-918f-87b75a016b7c)

**Comment by ThorstenDtk** [comment]
Naja, das Aussehen ist nebensächlich.  Wie schon gesagt ist das Problem, daß die Temperatur am Regler und nicht am Raumsensor angezeigt wird.

**Comment by rg-engineering** [comment]
nochmal: im o.g. screenshot aus der aktuellen Version des Adapters werden beide Temperaturen angezeigt und zusätzlich der Offset. Dafür muss natürlich die Offset-Funktion aktiviert sein...

**Comment by ThorstenDtk** [comment]
OK, verstehe jetzt was Du meinst. Auf welcher Version bist Du denn? Ich war auf 2.12.1, die ist lt. ioBroker (stable) aktuell. Laut GitHub ist die akutelle Version 2.12.2. Die habe ich über die URL installiert. Trotzdem hat sich nichts geändert. heatingcontrol.0.vis.RoomStatesHtmlTable wird ja wohl von HeatingControl selbst und nicht der Visualisierung von Pittini generiert. Und darin sind genau die 5 Spalten

![image](https://github.com/rg-engineering/ioBroker.heatingcontrol/assets/35042154/c5ee5512-cbf2-4b61-a6c5-ab4e94d5c069)

die ich sehe:

![image](https://github.com/rg-engineering/ioBroker.heatingcontrol/assets/35042154/95784538-77da-446e-a443-6d95c391a9ea)

Läßt sich irgendwo konfigurieren welche Spalten der Adapter in RoomStatesHtmlTable schreibt?

**Comment by rg-engineering** [comment]
hast du das hier aktiv?
![grafik](https://github.com/rg-engineering/ioBroker.heatingcontrol/assets/8238668/3d0d2ad2-94ca-4776-9127-8b98dfe64f02)

**Comment by ThorstenDtk** [comment]
Nein, das ist die Lösung. Besten Dank!
