### ISSUE TITLE
HILFE!!! Die Anleitung bringt mich nicht weiter als Erstnutzer

### ISSUE THREAD

**Issue by copperfield74** [rg-engineering/ioBroker.heatingcontrol#507]
Hallo liebe Kollegen,

ich habe gerade meine Bosch HKT 2 bekommen und wollte gerne das Paket HEATINGCONTROL nutzen.
Aber irgendwie komme ich nicht mit den Manuals zurecht. Ich verstehe z.B. nicht, wie ich mein Thermostat absenken kann, wenn das Fenster öffnet. Sowohl Thermostat als auch Fensterkontakt wurden eingepflegt, und ich bekomme Benachrichtigungen per Pushover wenn der Status sich ändert. Ich finde in den Objekten kein "WindowOpenDecrease" wie es in der Anleitung steht. Keine Ahnung was in den Einstellungen aktiviert werden muss, damit dieser Punkt erscheint? Gibt es nicht einen Guide für DUMMIES? ;-)
Oder irgendwo Beispiele wie man einfache Aufgaben konfiguriert?
HILFE!!!!

Danke für euer Verständnis.

Grüße
Chester

**Comment by copperfield74** [comment]
Okay, den Punkt "WindowOpenDecrease" habe ich jetzt gefunden. Die Anleitung scheint da einen falschen Pfad anzuzeigen. Kein Wunder das ich es nicht gefunden habe. :-(
Jetzt versuche ich eine Einstellung zu finden, wo ich eine Verzögerung einstellen kann, bevor die Temperatur abgesenkt wird, wenn man nur kurz lüftet.
Ich hoffe, dass ich nicht der EInzige bin, der damit Probleme hat.

**Comment by rg-engineering** [comment]
![grafik](https://github.com/rg-engineering/ioBroker.heatingcontrol/assets/8238668/224d37a9-e3c8-4388-b3b7-c0be9bc9f944)

siehe https://forum.iobroker.net/topic/22579/test-adapter-heatingcontrol-v2-12-x

**Comment by copperfield74** [comment]
Vielen Dank für den Link! Werde ich mir gleich zu Gemüte führen.
Auch wenn ich noch nicht 10% durchdrungen habe, was die App kann, vielen Dank für deine Arbeit.
Es wäre toll, wenn vielleicht nochmal jemand das Manual so anpassen könnte, dass nur minimale Erfahrungen nötig sind es zu verstehen. Im Augenblick habe ich das Gefühl, dass es für Anwender geschrieben ist, die schon tief in der Materie stecken.
Ich werde mir jetzt auf jeden Fall mal den Link anschauen, danke Dir!

**Comment by copperfield74** [comment]
Ich habe das Problem, dass die Erkennung von WINDOW OPEN nur in einem Raum geht. Die anderen Räume reagieren nicht auf offene Fenster. Habe mehrfach überprüft, ob ich die richtigen Objekte ausgewählt habe für das Thermoastat und die Fenstersensoren, aber leider reagiert nur ein Raum auf den Status Fenster geöffnet. Habe ich etwas übersehen? Fenstersensoren ist natürlich im Hauptmenü aktiviert.

**Comment by copperfield74** [comment]
Ich werde hier noch ganz bekloppt! :-)
Habe aus Spass mal eine Heizperiode eingestellt, weil ich sehen wollte ob der Status NO HEATING dann verschwindet.
Der Status is verschwunden, allerdings auf AUTO ABSENT. Das deaktivieren der Heizperiode hat den Status leider nicht zurückgestellt und es steht noch weiterhin AUTO ABSENT drin. Kann man das konfigurieren? Soll das so?

**Comment by rg-engineering** [comment]
"Absent" heist abwesend und ja, das kann man konfigurieren.

Nutzt du die vis von [Pittini](https://github.com/Pittini/iobroker-heatingcontrol-vis)? das würde einiges einfacher machen, weil man sieht, was einstellbar ist...
