### ISSUE TITLE
Nicht gewollter Übertrag aller Temperaturen

### ISSUE THREAD

**Issue by NicotheBob** [rg-engineering/ioBroker.heatingcontrol#51]
Bei mir kommt es vor, dass alle Soll-Temperaturen an die Heizkörperthermostate (HKT) neu fr das aktuelle Zeitfenster übermittelt werden, obwohl sich nur für ein HKT die Temperatur ändert. 

Beispiel: Ich habe nur einen Raum, der ab 14Uhr langsam hochgefahren werden soll. Um 14Uhr wurde für alle Räume die Soll-Temperatur übermittelt, obwohl ich für zwei Räume die Temperatur manuell angepasst habe, da ich ungeplant zu Hause war. Aus meiner Sicht sollte nur für den betroffenen Raum die Temp-Anpassung bei einem neuen Zeitfenster erfolgen.

Sonst noch jmd das Problem oder wie wird das sonst so gesehen?

**Comment by rg-engineering** [comment]
wenn du den TemperaturOverride aus dem Adapter zur manuellen Anpassung nimmst, sollten diese Werte nicht verändert werden, solange der override gültig ist. 
Wenn man aber direkt am Thermostat Einstellungen vornimmt, werden diese regelmässig (z.Bsp. bei Änderung einer Periode in einem anderen Raum) überschrieben. Im Forum gab es mal die Anfrage, diese Änderung als TemperaturOverride zu nutzen. Das ist aber nicht implementiert...

**Comment by NicotheBob** [comment]
Hi Rene,

Danke für die Rückmeldung und bisher klasse Arbeit. Der Adapter ist schon vielversprechend.

Fände klasse, wenn manuelle Änderungen direkt am HKT bspw. per TempOverride berücksichtigt werden und bei einem Umstellintervall zu einem anderen Raum nicht alle manuellen Anpassungen überschireben werden...erst wieder mit dem nächsten Umstellzeitpunkt zu dem Raum.

Viele Grüße
Nico

**Comment by AlexanderSch90** [comment]
Hey zusammen,

ich wäre auch für genau so eine Implementierung. Wir haben bei uns KEIN Vis-Tablet etc. und wollen die Anpassung an den Thermostaten direkt gerne dafür nutzen, dass genau der eingestellte Wert ab sofort in dem aktuell gültigen "CurrentTimePeriod" gilt. Beispiel:

Eine Einstellung am Thermostat der Küche an einem Mittwoch um 8.14 Uhr (innerhalb der Time Periode =1 (8-12 Uhr)) soll den Datenpunkt "heatingcontrol.0.Profiles.0.OG Küche.Mo-Fr.Periods.1.Temperature" dauerhaft anpassen. 

Wäre cool, wenn du also eine Erweiterung anstreben könntest. Gerne auch so, dass man pro Raum wählen kann, ob es eine TemperaturOverride sein soll oder eine dauerhafte Änderung. Dann wäre mit dieser Erweiterung allen Bedürfnissen gerecht geworden. Oder soll ich nen eigenen "Issue" dafür aufmachen?

 Vielen Dank für deine Arbeit!

**Comment by rg-engineering** [comment]
Übernahme der Änderungen vom Thermostat ist implementiert, deshalb schliesse ich dieses issue...
