### ISSUE TITLE
Mode in Thermostat Alias

### ISSUE THREAD

**Issue by Bjplms** [rg-engineering/ioBroker.heatingcontrol#523]
Hallo zusammen,
ich möchte gernen den State(Mode) des Thermostats aus der Heatingcontrol in einem Themostat Alias verwenden allerdings kann ich die Zustände im Alias nicht ändern und mit der Konvertierungs option komme ich auch nicht vorran.
Hat das zufällig schon einer umgesetzt oder kann mir einen Tipp geben ?

Besten Dank

**Comment by rg-engineering** [comment]
ist m.E. kein Thema für den Adapter, deshalb schliesse ich das hier...
