### ISSUE TITLE
Temperatur Override verschieben

### ISSUE THREAD

**Issue by Denkra** [rg-engineering/ioBroker.heatingcontrol#56]
Eine Sache habe ich noch damit ich den Adapter benutzen kann. Der Temperatur Override für Feiertage etc. müssen immernoch für jedes Profil eingestellt werden. Wenn das jetzt auch noch mit in die Räume kommt das man die Temperaturen einstellt und nicht nur "ob" es aktiv ist dann muss man es nicht für jedes Profil einzeln einstellen. So wie es jetzt ist kann man es sehr schlecht für eine VIS umsetzen da wenn man 3 Profile hat, man auch 3 Datenpunkte ändern muss.

**Comment by Pittini** [comment]
> Wenn das jetzt auch noch mit in die Räume kommt das man die Temperaturen einstellt und nicht nur "ob" es aktiv ist dann muss man es nicht für jedes Profil einzeln einstellen. 

Die Absenktemps sind doch Raumbezogen. OB es aktiv ist, ist global und das ist so korrekt. Zur Vereinfachung könnte man aber hier nen sync machen, siehe meinen Vorschlag im Forum.

**Comment by rg-engineering** [comment]
keine weitere Aktivität nötig...
