### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by foxriver76** [rg-engineering/ioBroker.heatingcontrol#560]
Please Release a new Version with current GitHub Content or even better allow the Adapter Core Dependency to get automatically Updated in the Same Major Release by specifying it with `^3.1.4` instead of a fixed version. This prevents from such scenarios in the future.

**Comment by foxriver76** [comment]
And Please also do this for your other adapters, as this seems to be a common pattern between your packages.

**Comment by rg-engineering** [comment]
solved with 2.12.6
