### ISSUE TITLE
Please adapt ALL dependencies

### ISSUE THREAD

**Issue by mcm1957** [rg-engineering/ioBroker.heatingcontrol#561]
This adapter currently used fixed dependency versions. Please change them to use semantic versioning (^1.2.3 instead of 1.2.3).
Normally there is no need to fix to a specific version in general In most cases this produces more troubles than benefits. In addition this config consumes more diskspace as npm cannot optimze installations. 99% of adapters use semantic versioning.

Currently this adapter fails at js-controller 6 because of this usage - and even worst it causes the complete ioBroker installation to fail at some installations.

Of course its ok to specify a fixed version if there is a special reason. But this is usually an exceptional situation.

**Comment by rg-engineering** [comment]
solved with 2.12.6
