### ISSUE TITLE
Option "wie am Vortag" einbauen

### ISSUE THREAD

**Issue by rg-engineering** [rg-engineering/ioBroker.heatingcontrol#58]
In der CCU und Raspberrymatic gibt es die Option beim Temperaturprofil einen Haken bei "wie am Vortag" zu setzen. Das verringert den Zeitaufwand beim Anlegen der Profile. Es wäre super, wenn Du das in Zukunft auch einbauen könntest

**Comment by Pittini** [comment]
War so auch im alten Heizungsscript drin. Is nicht verkehrt, andererseits, wieviele Profile stellt man den wie oft ein?

**Comment by rg-engineering** [comment]
Das würde ja nur greifen, wenn man Profil-Type "jeden Tag" eingestellt hat. Wenn man dann aber "wie am Vortag" aktiv hat, läuft es eher auf Profil "Mo-Fr / Sa-So" oder "Mo-So" hinaus...
Im alten Heizungsscript gab es m.E. nur "jeden Tag" und die Option "wie am Vortag"

**Comment by rg-engineering** [comment]
keine weitere Aktivität nötig
