### ISSUE TITLE
Fenster auf-verzögerung einbauen?

### ISSUE THREAD

**Issue by guergen1** [rg-engineering/ioBroker.heatingcontrol#60]
Hallo, 
wie sieht das mit dem Vorschlag aus, eine Verzögerungszeit für die Fensterkontakte einbauen zu können?
Das Problem ist, dass mein Sensor an der Balkontür die "offen Meldung" direkt herausgibt und das Ventil sofort schliesst, obwohl ich nur kurz durch die Tür gehe.
Schöner wäre es, wenn ich dort eine Verzögerung von, ich sage mal, 2-5 Sek eingeben könnte, dann bin ich draussen und das Ventil wäre von dem Vorfall gar nicht betroffen.

**Comment by rg-engineering** [comment]
mit 0.3.9 erledigt
