### ISSUE TITLE
Temperaturabsenkung/anhebung einstellungen

### ISSUE THREAD

**Issue by Denkra** [rg-engineering/ioBroker.heatingcontrol#61]
Finde es ja gut wie sich der Adapter entwickelt hat aber wo kann ich einstellen wieweit die Temperatur abgesenkt werden soll wenn ein Fenster offen ist oder wie weit sie angehoben werden soll wenn Besuch da ist?

**Comment by rg-engineering** [comment]
erst mal im admin einstellen, ob relativ oder absolut abgesenkt werden soll:
![grafik](https://user-images.githubusercontent.com/8238668/70859760-dadfd600-1f18-11ea-93fe-4f3d7ca2442a.png)

dann gibt es pro Raum diese Datenpunkte (für relativ und absolut in separaten Ordnern,
hier im Beispiel für relativ):
![grafik](https://user-images.githubusercontent.com/8238668/70859784-14184600-1f19-11ea-93df-568c13f9cf19.png)

**Comment by Denkra** [comment]
Ah cool super. Kann man das da nicht auch machen das man es Global für alle Profile macht? Ich meine so muss ich wenn ich 3 Profile habe und das ganze über die Vis mache auch 3 Datenpunkte ansteuern. Das ist über die VIS nicht wirklich machbar außer ich lasse im Hintergrund noch ein Script laufen was dann ja auch nicht Sinn der Sache ist.

**Comment by rg-engineering** [comment]
für die drei Profile hast du doch auch unterschiedliche Datenpunkte. Ich finde die aktuelle Lösung flexibler...

**Comment by Denkra** [comment]
Naja ich meine es sind ja Globale Parameter. Warum sollte sich in den verschiedenen Profilen die Absenktemperatur ändern also ich meine Warum soll wenn ich das Fenster auf mache und Frühschicht habe anders sein wie wenn ich Spätschicht habe?

**Comment by Denkra** [comment]
Genau mit diesen Einstellungen wie es jetzt ist muss ich dann zusätzlich noch ein Script im Hintergrund laufen lassen was ich eigentlich vermeiden wollte.

**Comment by Pittini** [comment]
> Ich meine so muss ich wenn ich 3 Profile habe und das ganze über die Vis mache auch 3 Datenpunkte ansteuern. Das ist über die VIS nicht wirklich machbar außer ich lasse im Hintergrund noch ein Script laufen was dann ja auch nicht Sinn der Sache ist.

Dem widerspreche ich. Das ist im Vis durchaus darstell- und mach-bar, siehe meine Vorlage. Muss man halt mit Sichtbarkeit arbeiten und verschiedene Blöcke übereinander legen.

**Comment by rg-engineering** [comment]
keine weitere Aktivität...
