### ISSUE TITLE
Override wird nicht übernommen

### ISSUE THREAD

**Issue by tobi-82** [rg-engineering/ioBroker.heatingcontrol#616]
beim erneuten setzten des Overrides mit der gleichen (vorherigen) Temperatur, wird diese nicht mehr übernommen.
Wird z.B. die Override- Temperatur von 23° gesetzt, bleibt diese für die eingestellte Zeit aktiv. Wird dann die gleiche Temperatur 
z.B. am nächsten Tag wieder gesetzt, so ändert sich der Override nicht mehr. Hier muss dann z.B. eine andere Temperatur z.B. 23,5°
gesetzt werden.

**Comment by cat1510** [comment]
Ich glaube das haengt auch mit meinem entdeckten Problem zusammen.

**Comment by rg-engineering** [comment]
@tobi-82 genau so st es derzeit implementiert. Man muss die Zeit oder die Temperatur ändern. Nur so triggert man den Override. Das ist aber absichtlich so, da es anscheinend Situation gibt, wo das System selbst gleiche Werte hintereinander sendet. Das hat damals einen "Dauer-Override" verursacht...

@cat1510  In "deinem" Problem war der Fehler, dass die RemainingOverrideTime zu schnell heruntergezählt wurde.
