### ISSUE TITLE
Override timings funktionieren nicht.

### ISSUE THREAD

**Issue by cat1510** [rg-engineering/ioBroker.heatingcontrol#617]
Hi,

erstmal - ich nutze den HeatingControl Adapter schon seit 4 Jahren.
Wie immer super Arbeit!!! <3

iobroker alles aktuell NodeJS20 und so.

Es gibt das ein Timer Problem glaube ich.
Short: Ein laufender Timer fuer eine OverrideTime wird nicht zurueckgesetzt oder erweitert, wenn man die OverrideTemp oder OverrideTime neusetzt.

Long Story:
Kann man es reproduzieren? Ja -habe ich auf 3 unterschiedlichen Systemen.
Wenn man OverrideTime auf zum Beispiel 00:03 (3Minuten) setzt und wartet bis Remaining Time nur noch 1min hat.
Dann setzt man die Zeit selbst auf 00:00 - alles reset, (sieht so aus).
Setzt sie wieder auf 00:03 und eine OverrideTemperatur.
Dann kann man zusehen, wie die 3Minuten in 30Sekunden vergehen...

Habe mal noch schnell ein Video gemacht. Geht nur 3min aber ich habe 2x 5min Override Time... ;)

https://cloud.plrez.de/f/39708d23ea9a41ae83b3/?dl=1

**Comment by rg-engineering** [comment]
see #272

**Comment by rg-engineering** [comment]
@cat1510  Ich denke, ich weiß, was du meinst:

![grafik](https://github.com/user-attachments/assets/197accbc-584c-40bf-b559-7f77d8a6c8ad)

In dem Fall ist TemperaturOverrideRemainingTime schon null, obwohl Status Override noch gesetzt ist. Auch der CurrentTarget steht noch auf der OverrideTemperature. Ist also nur ein Problem der Zeitanzeige...

**Comment by cat1510** [comment]
Hi,

habe das gerade getestet.
Extend Override hat nicht funktioniert, check ich heute abend aber nochmal in Ruhe.
Prozedur:
- set override time to 00:04
- set override temperature to 23 degrees
- wait a minute to see remain time decreases
- set new override temperature

expected behavoir: remain time jumps back to 4min
tried: manual_reset does not stop the timer either.

issue #617 is fixed.
Verhaelt sich 'ganz normal' :)
Egal wie oft man den override neustartet oder abbricht.

Danke fuer die Arbeit!
