### ISSUE TITLE
zusätzlicher Datenpunkt für Raumnutzer "noch im Bett"

### ISSUE THREAD

**Issue by truegreyhound** [rg-engineering/ioBroker.heatingcontrol#63]
Eine meiner nächsten Erweiterungen in meinem Skript wäre ein Parameter für die Unterdrückung der Änderung der Temperatur im Profile am Morgen. Es kommt doch mal  vor, das wir oder die Kids (über 18) nach einer Party nicht wie gewohnt aufstehen wollen/können und dann jagt die Heizung die Temperatur hoch und es gibt Hitzestau und schlechte Laune.
Am Abend, wenn wir bei Extremtemperaturen nicht bei offenem Fenster schlafen, könnte dieser Status bei vorzeitiger Bettruhe eine vorzeitige Absenkung der Temperatur steuern. Nach dem kurzen Lüften würde die Heizung in diesem Fall ja wieder richtig hochfahren.

**Comment by Pittini** [comment]
Die Idee ist nicht verkehrt, aber wenn, dann als FeatureRequest für die Zukunft. Das macht nämlich ein fettes Faß auf, sprich sowas wie ne Userverwaltung. Mama und Papa haben verschiedene Schlafzimmer weil der Papa schnarcht. Die 5 Kids haben auch jeweils ein Zimmer und Oma nochmal eins. Jeder will dann andere Temps usw. Sicher machbar, aber ich finde wir sollten den Adapter erstmal stable kriegen bevor sowas angedacht wird.
Und dann würde das auch nicht nur das Schlafzimmer betreffen sondern bei mir hier auch das Büro meiner Frau, das muß auch ned geheizt werden wenn se noch im Bett ist usw.

**Comment by rg-engineering** [comment]
Ich sehe es ähnlich wit @Pittini : Im Moment möchte ich den Adapter erst mal stable bekommen. Dann muss ich schauen, dass der Adapter von den usern noch bedienbar bleibt.
