### ISSUE TITLE
HM-Sec-SCo wird nicht erkannt

### ISSUE THREAD

**Issue by lindi200000** [rg-engineering/ioBroker.heatingcontrol#68]
Hallo,
ich möchte gern den 1. Raum bei mir im Heating Controller einfügen.
Das Thermostat HmIP-eTRV-2 wird auch ordnungsgemäß erkannt.
Leider wird aber der HM-Sec-SCo Fenstersensor nicht erkannt.
IOBroker hat den Fenstersensor drin und im HM Adapter wird auch immer der richtige Status angezeigt.
Gibt es eine Idee wieso der Heatingcontrol Adpater diesen nicht erkennt?
Der Sensor ist auch ordnungsgemäß als Sensor im entsprechenden Raum hinterlegt.
Sensor | OID
Fenster Büro.STATE | hm-rpc.0.OEQ1556885.1.STATE

Installierte heatingcontrol version ist die 0.3.14

Wie kann man das ganze am besten zum laufen bekommen?

VG
Lindi

**Comment by lindi200000** [comment]
Man sollte auch die Sensoren im Admin aktivieren .....

**Comment by rg-engineering** [comment]
manuell konfigurieren funktioniert ebenfalls...
