### ISSUE TITLE
Zieltemperatur wenn Heizperiode aus

### ISSUE THREAD

**Issue by lindi200000** [rg-engineering/ioBroker.heatingcontrol#69]
Hallo,
ich würde es super finden, das man eine Temperatur pro Raum einstellen kann, wenn keine Heizperiode an ist.
So kann man den Heizungen sagen, das sie aus sind bzw. das nur 5 Grad sein sollen.
Praktisch, wenn die Zentralheizung noch läuft, man selber aber nicht mehr in der Wohnung heizen will.

**Comment by rg-engineering** [comment]
ist mit 0.3.17 implementiert...
