### ISSUE TITLE
Integration Max! (völlständig)

### ISSUE THREAD

**Issue by AlexanderSch90** [rg-engineering/ioBroker.heatingcontrol#7]
Ich nicht nicht den Adapter Max! Cube sondern den Adapter maxcul. Im Log kommt deshalb der Hinweis: heatingcontrol.0	2019-07-18 13:58:10.139	warn	unknown path to thermostats maxcul.0.

Kannst du den Pfad maxcul.0. für Thermostate "erlauben"?

Danke!

Vergleiche: https://forum.iobroker.net/topic/22579/adapter-heatingcontrol/42

**Comment by rg-engineering** [comment]
workaround (=manuelle Konfiguration) mit 0.1.0 zur Verfügung gestellt...
