### ISSUE TITLE
WindowsIsOpen sollte oberste Priorität haben

### ISSUE THREAD

**Issue by lindi200000** [rg-engineering/ioBroker.heatingcontrol#72]
Hallo,
Ich habe festgestellt, das TemperatureOverride eine höhere Priorität hat, als WindowIsOpen.
Das bedeutet im Endeffekt, ich mach es mir im Zimmer kuschlig warm und lüfte dann. In dem Moment bleibt die Heizung auf kuschlig warm und senkt sich nicht ab. Somit heize ich im Grunde für die Außenwelt.
Die Prio hier sollte wirklich geändert werden.
Wenn TemperaturOverride ist an und das Fenster wird aufgemacht, dann stelle die Absenktemperatur für WindowIsOpen ein.
Aktuell lässt er wie geschrieben die Override Temperatur.

VG
Lindi

**Comment by rg-engineering** [comment]
ist in 0.3.16 enthalten und kann getestet werden
