### ISSUE TITLE
Heizungen gehen nicht aus bei Heizperiode "false"

### ISSUE THREAD

**Issue by Denkra** [rg-engineering/ioBroker.heatingcontrol#75]
Ich weiß nicht ob es ein Einstellungsfehler ist aber wenn ich die Heizperiode auf "false" setze, gehen die Heizungen nicht aus. Im Adapter ist eingestellt, das wenn keine Heizperiode vorliegt, die Stellantriebe Aus sein sollen. Andersrum funktioniert es. Setze ich den datenpunkt auf "false", mache die Heizungen manuell aus und setze Heizperiode aktiv auf "true" gehen alle Heizungen an.

**Comment by rg-engineering** [comment]
nimm mal die letzte Version hier aus github. In den debug-logs sollte dann "switch off all actors" erscheinen.

**Comment by Denkra** [comment]
So bin irgendwie drüber weg gekommen aber letztens ist es mir wieder eingefallen da es draußen warm war und die Heizung eigentlich aus gehen sollte. Das einzige was im Log steht ist 


heatingcontrol.0 | 2020-02-18 14:19:10.320 | info | (5567) calculating new target temperatures

Danach kommt absolut gar nichts mehr bis ich es wieder einschalte.

**Comment by rg-engineering** [comment]
okay, zeig mir mal bitte deine Konfiguration (evtl. im Admin über Konfiguration speichern) oder als screen shots.
Du nutzt die Regelung der Aktoren direkt aus dem Adapter, oder schalten deine Thermostate die Aktoren?

**Comment by Denkra** [comment]
[http://prntscr.com/r6s3ol](url)

Hoffe das geht mit dem Link. Also bei mir ist das so.... Adapter, Maxcube, Thermostate. Wie gesagt beim einschalten funktioniert es ja wenn ich alle Thermostate aus habe und die Heizperiode auf true stelle. Dann geht er alles durch und schaltet auch alle ein dann nur beim aus schalten dann halt nicht.

**Comment by rg-engineering** [comment]
@Denkra der link geht irgendwie in's leere... wir können auch in's forum wechseln, wenn es da einfacher ist...

**Comment by rg-engineering** [comment]
@Denkra kannst du mal die aktuelle Version von hier versuchen? Du musst den Mode auf der Profile-Seite im admin des Adapters vorher einstellen

**Comment by Denkra** [comment]
@rg-engineering ah perfekt. Mit dem neuen Update funktioniert es. Vielen Dank
