### ISSUE TITLE
Zusätzliche readonly Datenpunkte zur Vis Steuerung/Kontrolle

### ISSUE THREAD

**Issue by Pittini** [rg-engineering/ioBroker.heatingcontrol#76]
1. Neuen Channel unter heatingcontrol.x anlegen namens "Info"
2. In den neuen Channel readonly folgende Datenpunkte erstellen:
	Der Einfachheit halber und um "Nachforderungen" meinerseits zu vermeiden: Alles aus Adapteradmin > Profil, also 7 Datenpunkte
3. Einen Datenpunkt "ActiveTimeSlot" unter HeatingControl.0.Rooms.xxx für die Kombination aus Profiltyp und Periode als Zahl um zweifelsfrei den aktiven Zeitraum zu bestimmen. Also ein fortlaufender Zähler für einen kompletten Wochenzyklus.
Bei Profiltyp:
Montag-Sonntag - 			Pt=1 * Anzahl der Perioden - entspricht dem jetzigen DP CurrentTimePeriod
Montag-Freitag + Samstag-Sonntag - 	Pt=2 * Anzahl der Perioden - Zählt Mo-Fr von 1-Anzahl der Perioden / Sa+So von AnzahlPerioden+1 - 2*Anzahl der Perioden
jeden Tag getrennt - 			Pt=7 * Anzahl der Perioden - Zählt additiv pro Tag von 1-Anzahl der Perioden

Bei angenommenen 5 Perioden würden sich folgende Zahlenreihen ergeben:
					        
Montag-Sonntag - 			(täglich)1, 2, 3, 4, 5
					                        	    
Montag-Freitag + Samstag-Sonntag - 	(Mo-Fr)1, 2, 3, 4, 5 - ( Sa+So)6, 7, 8, 9, 10

jeden Tag getrennt - 			(Mo)1, 2, 3, 4, 5 - (Di)6, 7, 8, 9, 10 - (Mi)11, 12, 13, 14, 15 - (Do)16, 17, 18, 19, 20 - (Fr)21, 22, 23 ,24 ,25 - (Sa)26, 27, 28, 29, 30 - (So)31, 32, 33, 34, 35

Ich denke dass Du diese Info Programmintern ohnehin drin hast, bzw einfach nur 2 Schleifenzähler addieren müsstest. Ich brauche diese Info um im Vis dann anzuzeigen welcher Zeit/Temp Bereich grade aktiv ist (siehe Beispielbild). CurrentTimePeriod zeigt mir aber nur an wo man im aktuellen Tag grad ist, aber ich weis (ohne extra Script) ja nicht welcher Tag grad ist. Hoffe ich hab mich verständlich ausgedrückt.

**Comment by rg-engineering** [comment]
@Pittini schau mal, ob dir das so passt. Änderung ist aber derzeit nur hier in github...

**Comment by Pittini** [comment]
Hi, vielen Dank. Die Datenpunkte an sich passen, aber:
1. "info" wird inkl. Datenpunkten angelegt aber nicht befüllt
2. "ActiveTimeSlot" ist vorhanden, wird befüllt, aber imho nicht korrekt. Ich hab Mo-Fr/Sa-So eingestellt bei mir. Current Period zeigt grade 2 an, "Active Timeslot" aber 3, sollte bis inkl. Freitag eigentlich das gleiche sein wie CurrentPeriod.
Die anderen Varianten werd ich noch (auch über mehrere Tage) verfolgen, aber die beiden Punkte sind mir jetzt sofort aufgefallen. 
lg

**Comment by rg-engineering** [comment]
okay, danke für's feedback. Hatte eigentich die letzten Tage bei mir beobachtet und war zufrieden. Anscheinend doch etwas übersehen...

**Comment by rg-engineering** [comment]
@Pittini  zu 1)
bei mir sieht das so aus:
![grafik](https://user-images.githubusercontent.com/8238668/75605149-74626100-5ae0-11ea-8b1e-746a711e52d4.png)
bekommst du irgendwelche Fehlermeldungen im log?

**Comment by Pittini** [comment]
@rg-engineering 
Und bei mir sieht das so aus:
![2020-02-29 11_06_22-Window](https://user-images.githubusercontent.com/51408942/75605525-dbcde000-5ae3-11ea-9e35-fe73e4a7e266.png)

Logfehler kommen keine, ein kompletter restart sieht so aus:
`

heatingcontrol.0 | 2020-02-29 11:07:02.740 | info | (5064) room Schlafzimmer_C setting new target 20.5
-- | -- | -- | --
heatingcontrol.0 | 2020-02-29 11:07:02.471 | info | (5064) room Wohnzimmer Thermostat HM-CC-RT-DN PEQ1315641 target is 16
heatingcontrol.0 | 2020-02-29 11:07:02.471 | info | (5064) room Wohnzimmer setting new target 16
heatingcontrol.0 | 2020-02-29 11:07:02.407 | info | (5064) calculating new target temperatures
heatingcontrol.0 | 2020-02-29 11:07:02.406 | info | (5064) external states checked, done
heatingcontrol.0 | 2020-02-29 11:07:02.356 | info | (5064) setting Present to true
heatingcontrol.0 | 2020-02-29 11:07:02.216 | info | (5064) setting PublicHolidyToday to false
heatingcontrol.0 | 2020-02-29 11:07:02.215 | info | (5064) checking all external states
heatingcontrol.0 | 2020-02-29 11:07:01.882 | info | (5064) Wohnzimmer window open on Is opened
heatingcontrol.0 | 2020-02-29 11:06:59.299 | info | (5064) starting. Version 0.3.17 in /opt/iobroker/node_modules/iobroker.heatingcontrol, node: v10.18.1
heatingcontrol.0 | 2020-02-29 11:06:55.770 | info | (19746) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
heatingcontrol.0 | 2020-02-29 11:06:55.769 | info | (19746) terminating
heatingcontrol.0 | 2020-02-29 11:06:55.768 | info | (19746) cleaned everything up...
heatingcontrol.0 | 2020-02-29 11:06:55.767 | info | (19746) Got terminate signal TERMINATE_YOURSELF
heatingcontrol.0 | 2020-02-29 11:02:56.208 | info | (19746) room Buero Thermostat HM-CC-RT-DN PEQ1312591 target is 20
heatingcontrol.0 | 2020-02-29 11:02:56.208 | info | (19746) room Buero setting new target 20
heatingcontrol.0 | 2020-02-29 11:02:56.112 | info | (19746) calculating new target temperatures
heatingcontrol.0 | 2020-02-29 10:57:24.980 | info | (19746) room Buero Thermostat HM-CC-RT-DN PEQ1312591 target is 15
heatingcontrol.0 | 2020-02-29 10:57:24.980 | info | (19746) room Buero setting new target 15
heatingcontrol.0 | 2020-02-29 10:57:24.924 | info | (19746) calculating new target temperatures
heatingcontrol.0 | 2020-02-29 10:57:09.875 | info | (19746) Buero window open on Is opened
heatingcontrol.0 | 2020-02-29 10:54:58.347 | info | (19746) room Buero Thermostat HM-CC-RT-DN PEQ1312591 target is 20
heatingcontrol.0 | 2020-02-29 10:54:58.347 | info | (19746) room Buero setting new target 20
heatingcontrol.0 | 2020-02-29 10:54:58.083 | info | (19746) room Kueche Thermostat HM-CC-RT-DN PEQ1632518 target is 19
heatingcontrol.0 | 2020-02-29 10:54:58.083 | info | (19746) room Kueche setting new target 19
heatingcontrol.0 | 2020-02-29 10:54:57.815 | info | (19746) room Flur_EG Thermostat HM-CC-RT-DN PEQ1632504 target is 20
heatingcontrol.0 | 2020-02-29 10:54:57.815 | info | (19746) room Flur_EG setting new target 20
heatingcontrol.0 | 2020-02-29 10:54:57.567 | info | (19746) room Dachboden Thermostat HM-CC-RT-DN PEQ1312432 target is 6
heatingcontrol.0 | 2020-02-29 10:54:57.567 | info | (19746) room Dachboden setting new target 6
heatingcontrol.0 | 2020-02-29 10:54:57.299 | info | (19746) room Toilette Thermostat HM-CC-RT-DN PEQ1312429 target is 19
heatingcontrol.0 | 2020-02-29 10:54:57.299 | info | (19746) room Toilette setting new target 19
heatingcontrol.0 | 2020-02-29 10:54:56.994 | info | (19746) room Werkstatt Thermostat HM-CC-RT-DN PEQ1632514 target is 18
heatingcontrol.0 | 2020-02-29 10:54:56.994 | info | (19746) room Werkstatt setting new target 18
heatingcontrol.0 | 2020-02-29 10:54:56.768 | info | (19746) room Bad Thermostat HM-CC-RT-DN PEQ1315632 target is 21
heatingcontrol.0 | 2020-02-29 10:54:56.768 | info | (19746) room Bad setting new target 21
heatingcontrol.0 | 2020-02-29 10:54:56.526 | info | (19746) room Schlafzimmer_C Thermostat HM-CC-RT-DN PEQ1315550 target is 20.5
heatingcontrol.0 | 2020-02-29 10:54:56.526 | info | (19746) room Schlafzimmer_C setting new target 20.5
heatingcontrol.0 | 2020-02-29 10:54:56.201 | info | (19746) room Wohnzimmer Thermostat HM-CC-RT-DN PEQ1315641 target is 16
heatingcontrol.0 | 2020-02-29 10:54:56.201 | info | (19746) room Wohnzimmer setting new target 16
heatingcontrol.0 | 2020-02-29 10:54:56.148 | info | (19746) calculating new target temperatures
heatingcontrol.0 | 2020-02-29 10:54:45.148 | info | (19746) room Buero Thermostat HM-CC-RT-DN PEQ1312591 target is 20
heatingcontrol.0 | 2020-02-29 10:54:45.148 | info | (19746) room Buero setting new target 20
heatingcontrol.0 | 2020-02-29 10:54:44.863 | info | (19746) room Kueche Thermostat HM-CC-RT-DN PEQ1632518 target is 19
heatingcontrol.0 | 2020-02-29 10:54:44.863 | info | (19746) room Kueche setting new target 19
heatingcontrol.0 | 2020-02-29 10:54:44.583 | info | (19746) room Flur_EG Thermostat HM-CC-RT-DN PEQ1632504 target is 20
heatingcontrol.0 | 2020-02-29 10:54:44.582 | info | (19746) room Flur_EG setting new target 20
heatingcontrol.0 | 2020-02-29 10:54:44.352 | info | (19746) room Dachboden Thermostat HM-CC-RT-DN PEQ1312432 target is 6
heatingcontrol.0 | 2020-02-29 10:54:44.352 | info | (19746) room Dachboden setting new target 6
heatingcontrol.0 | 2020-02-29 10:54:44.080 | info | (19746) room Toilette Thermostat HM-CC-RT-DN PEQ1312429 target is 19
heatingcontrol.0 | 2020-02-29 10:54:44.080 | info | (19746) room Toilette setting new target 19
heatingcontrol.0 | 2020-02-29 10:54:43.811 | info | (19746) room Werkstatt Thermostat HM-CC-RT-DN PEQ1632514 target is 18
heatingcontrol.0 | 2020-02-29 10:54:43.811 | info | (19746) room Werkstatt setting new target 18
heatingcontrol.0 | 2020-02-29 10:54:43.544 | info | (19746) room Bad Thermostat HM-CC-RT-DN PEQ1315632 target is 21
heatingcontrol.0 | 2020-02-29 10:54:43.543 | info | (19746) room Bad setting new target 21
heatingcontrol.0 | 2020-02-29 10:54:43.259 | info | (19746) room Schlafzimmer_C Thermostat HM-CC-RT-DN PEQ1315550 target is 20.5
heatingcontrol.0 | 2020-02-29 10:54:43.259 | info | (19746) room Schlafzimmer_C setting new target 20.5
heatingcontrol.0 | 2020-02-29 10:54:43.004 | info | (19746) room Wohnzimmer Thermostat HM-CC-RT-DN PEQ1315641 target is 16
heatingcontrol.0 | 2020-02-29 10:54:43.004 | info | (19746) room Wohnzimmer setting new target 16
heatingcontrol.0 | 2020-02-29 10:54:42.949 | info | (19746) calculating new target temperatures
heatingcontrol.0 | 2020-02-29 10:34:55.022 | info | (19746) room Wohnzimmer Thermostat HM-CC-RT-DN PEQ1315641 target is 16
heatingcontrol.0 | 2020-02-29 10:34:55.022 | info | (19746) room Wohnzimmer setting new target 16
heatingcontrol.0 | 2020-02-29 10:34:54.484 | info | (19746) calculating new target temperatures
heatingcontrol.0 | 2020-02-29 10:34:39.439 | info | (19746) Wohnzimmer window open on Is opened
heatingcontrol.0 | 2020-02-29 08:00:03.155 | info | (19746) room Buero Thermostat HM-CC-RT-DN PEQ1312591 target is 20
heatingcontrol.0 | 2020-02-29 08:00:03.155 | info | (19746) room Buero setting new target 20
heatingcontrol.0 | 2020-02-29 08:00:02.447 | info | (19746) room Kueche Thermostat HM-CC-RT-DN PEQ1632518 target is 19
heatingcontrol.0 | 2020-02-29 08:00:02.447 | info | (19746) room Kueche setting new target 19
heatingcontrol.0 | 2020-02-29 08:00:02.181 | info | (19746) room Flur_EG Thermostat HM-CC-RT-DN PEQ1632504 target is 20
heatingcontrol.0 | 2020-02-29 08:00:02.181 | info | (19746) room Flur_EG setting new target 20
heatingcontrol.0 | 2020-02-29 08:00:01.894 | info | (19746) room Dachboden Thermostat HM-CC-RT-DN PEQ1312432 target is 6
heatingcontrol.0 | 2020-02-29 08:00:01.894 | info | (19746) room Dachboden setting new target 6
heatingcontrol.0 | 2020-02-29 08:00:01.443 | info | (19746) room Toilette Thermostat HM-CC-RT-DN PEQ1312429 target is 19
heatingcontrol.0 | 2020-02-29 08:00:01.443 | info | (19746) room Toilette setting new target 19
heatingcontrol.0 | 2020-02-29 08:00:01.113 | info | (19746) room Werkstatt Thermostat HM-CC-RT-DN PEQ1632514 target is 18
heatingcontrol.0 | 2020-02-29 08:00:01.113 | info | (19746) room Werkstatt setting new target 18
heatingcontrol.0 | 2020-02-29 08:00:00.817 | info | (19746) room Bad Thermostat HM-CC-RT-DN PEQ1315632 target is 21
heatingcontrol.0 | 2020-02-29 08:00:00.817 | info | (19746) room Bad setting new target 21
heatingcontrol.0 | 2020-02-29 08:00:00.373 | info | (19746) room Schlafzimmer_C Thermostat HM-CC-RT-DN PEQ1315550 target is 20.5
heatingcontrol.0 | 2020-02-29 08:00:00.372 | info | (19746) room Schlafzimmer_C setting new target 20.5
heatingcontrol.0 | 2020-02-29 08:00:00.079 | info | (19746) room Wohnzimmer Thermostat HM-CC-RT-DN PEQ1315641 target is 21
heatingcontrol.0 | 2020-02-29 08:00:00.079 | info | (19746) room Wohnzimmer setting new target 21
heatingcontrol.0 | 2020-02-29 08:00:00.011 | info | (19746) calculating new target temperatures

`

**Comment by Pittini** [comment]
Bitte nicht hauen, wenn möglich, solange Du eh noch da dran bist, geht noch ein Datenpunkt unter Info mit Liste der verwendeten Räume? Büdde ;)

**Comment by Pittini** [comment]
PS: Ganz überlesen, ja der aktive Timeslot stimmt aktuell (11:24) auch bei mir, werd weiter beobachten.

**Comment by rg-engineering** [comment]
hab den Fehler mit dem update der DP in info gefixt. Bitte den ganzen Ordner info nochmal löschen, adapter aktualisieren und neu starten...

**Comment by rg-engineering** [comment]
UsedRooms sind jetzt auch mit drin...

**Comment by Pittini** [comment]
Jap, Rooms DP is drin, aber immer noch keine Daten leider.
![2020-02-29 11_37_49-Window](https://user-images.githubusercontent.com/51408942/75605942-19346c80-5ae8-11ea-90f5-44b23229d052.png)

**Comment by rg-engineering** [comment]
hattest du die DP im info vorher alle gelöscht?

**Comment by Pittini** [comment]
> hattest du die DP im info vorher alle gelöscht?

Ja klar, Adapter gestoppt, Info gelöscht, upgedatet, neugestartet. Sicherheitshalber um eigene Dämlichkeit auszuschliessen sogar 2mal

**Comment by Pittini** [comment]
Auch keine Änderung durch iobroker neustart mit vorherigem löschen des Infoordners.

**Comment by rg-engineering** [comment]
vielleicht auch den Ordner Info löschen? und dann mal den DP selbst prüfen. Der Fehler war, dass der type auf "info" anstatt "state" stand
![grafik](https://user-images.githubusercontent.com/8238668/75606153-3ff3a280-5aea-11ea-8555-3422adb314b6.png)

**Comment by Pittini** [comment]
Ich hatte ohnehin immer den ganzen info Ordner gelöscht. Und state is drin:
![2020-02-29 11_55_45-Window](https://user-images.githubusercontent.com/51408942/75606184-8812c500-5aea-11ea-8d72-6cc01d720db2.png)

**Comment by Pittini** [comment]
Und aus unerfindlichen Gründen sind jetzt, einfach so während ich deppert meine Monitor angestarrt hab, die Daten aufgetaucht.

**Comment by Pittini** [comment]
Aber der Aktive Timeslot sollte jetzt eigentlich 7 sein, ist aber 8. Kann da ein Fehler sein dass iwo mit 0 statt 1 oder umgekehrt in ner Schleife begonnen wird?
![2020-02-29 12_05_16-Window](https://user-images.githubusercontent.com/51408942/75606352-0b80e600-5aec-11ea-94a0-6118413c49a1.png)

**Comment by rg-engineering** [comment]
Da passt was nicht, bei mir ist jetzt auch 8, aber es ist nur eine Periode später als vor 12:00Uhr und da war 6

**Comment by rg-engineering** [comment]
So, bug fix sollte das Problem jetzt beheben.
Beispiel:
Bei Profiltype Mo-Fr / Sa-So und 5 Perioden zählt ActiveTimeSlot jetzt von 0 bis 4 an den Tagen Mo-Fr und am Sa / So jeweils von 5 bis 9

**Comment by Pittini** [comment]
Danke Dir. Schaut gut aus jetzt, muss aber noch die anderen Varianten testen.

**Comment by Pittini** [comment]
Kurze Verständnisfrage, warum ist das ein Bool und warum kann man trotzdem ne Zahl eingeben?

![2020-03-02 19_49_29-objects - ioBroker](https://user-images.githubusercontent.com/51408942/75707528-4c7d2400-5cbf-11ea-99d1-503bea3948c6.png)

**Comment by rg-engineering** [comment]
ich lege die DP eigentlich so an:
type: 'state',
        common: {
            name: 'period from',
            type: 'date',
            role: 'profile',
            unit: '',
            read: true,
            write: true
        },
und bei mir sieht das so aus:

![grafik](https://user-images.githubusercontent.com/8238668/75710437-dd0a3300-5cc4-11ea-8463-0ba269798f96.png)

**Comment by Pittini** [comment]
Das is ne spannende Sache. Ruf ich das mit dem Bleistift aus der Objektliste auf, isses wie bei Dir. Klicke ich jetzt in dem Fenster auf "Raw", erscheint die Bool Variante. Könnte fast nen Bug im Admin sein, weil Erklärung habe ich keine dafür.

**Comment by Pittini** [comment]
Hab grad mal sehen wollen wie der DP heißt der für reine Feiertage gesetzt wird. Also hab ich mal den Haken raus bei "Feiertag wie Sonntag". Jetzt hätte ich erwartet dass bei Profiles.x.room. ein neuer DP auftaucht, aber da passiert gar nix. Kannste das mal bitte prüfen.

**Comment by Pittini** [comment]
Bitte bei UsedRooms das Semikolon nach dem letzten Eintrag entfernen.

**Comment by rg-engineering** [comment]
Es gibt keinen DP für Feiertag. Entweder wird der Feiertag wie ein normaler Tag (also ohne Sonderbehandlung) oder wie ein Sonntag behandelt

und ja, das Semikolon nehme ich raus...

**Comment by rg-engineering** [comment]
@Pittini  das Semikolon ist bei 0.3.18 raus...

**Comment by Pittini** [comment]
Danke, damit ist hier alles erledigt und ich mach dicht.
