### ISSUE TITLE
Profile anpassen möglich?

### ISSUE THREAD

**Issue by guergen1** [rg-engineering/ioBroker.heatingcontrol#78]
Im Moment ist es ja so, dass es Mo-So, Mo-Fr&Sa-So und jeden Tag getrennt gibt. Es wäre gut, wenn man noch einen Profiltyp Mo-Do einbauen könnte, da es sicherlich Leute gibt( mich eingeschlossen) die Freitags kürzer arbeiten müssen

**Comment by Pittini** [comment]
Und der Kneipenbesitzer hat Montag Ruhetag und der Arzt Mittwoch frei... Man kanns nicht allen Recht machen, dafür gibts ja die Option Mo-So.

**Comment by rg-engineering** [comment]
nein, den Profiltype werde ich nicht supporten... Ich schliesse das issue hier...
