### ISSUE TITLE
Integration Fensterkontakte Zigbee

### ISSUE THREAD

**Issue by AlexanderSch90** [rg-engineering/ioBroker.heatingcontrol#8]
Kannst du den Pfad zigbee.0. für Aktoren auch "erlauben"?

Danke!

Siehe: https://forum.iobroker.net/topic/22579/adapter-heatingcontrol/42

**Comment by rg-engineering** [comment]
workaround (=manuelle Konfiguration) mit 0.1.0 zur Verfügung gestellt...
