### ISSUE TITLE
Unsinnige Angaben im Adapter Admin möglich

### ISSUE THREAD

**Issue by Pittini** [rg-engineering/ioBroker.heatingcontrol#81]
Da ich grad bzgl. der Vis Erstellung oft im Adapteradmin Werte ändern muss zum testen, ist mir aufgefallen dass man bei "Anzahl der Profile" und "Anzahl der Perioden" sinnfreie Angaben wie -1 machen kann. Sollte man evtl. in Hinblick auf Support einschränken, weil wenn man was falsch einstellen kann, wirds irgendwann auch jemand tun.

**Comment by rg-engineering** [comment]
ist mit 0.3.17 erledigt
