### ISSUE TITLE
Zuordnung der Räume zu Rollen/Raum/Funktion

### ISSUE THREAD

**Issue by Gsiberger2** [rg-engineering/ioBroker.heatingcontrol#82]
Momentan ist es nur möglich den Datenpunkten Rollen/Raum/Funktion zuzuordnen.
Es wäre schön, wäre dies bereits bei den Knotenpunkten der Räume unter Profiles und Rooms möglich und dann an die darunterliegenden Knotenpunkte/Datenojekte vererbt wird.

**Comment by rg-engineering** [comment]
kannst du das bite etwas genauer erklären?

**Comment by Gsiberger2** [comment]
Bei zB HM kann bei den Objekten auf oberster Ebene das Gerätes der Raum ausgewählt werden und verebt sich auf die darunterliegenden Datenpunkte:
![image](https://user-images.githubusercontent.com/61651011/75631218-533d6580-5bf1-11ea-89e7-35826839dfcf.png)

Bei heatingcontrol muss bei jedem einzelnen Datenpunkt der Raum festgelegt werden:
![image](https://user-images.githubusercontent.com/61651011/75631250-94ce1080-5bf1-11ea-952a-286c58b44788.png)

**Comment by rg-engineering** [comment]
mit 0.3.18 kann man zumindest die channels einem Raum zuordnen. Im Moment aber weiterhin manuell...

**Comment by rg-engineering** [comment]
solved with 0.3.19

**Comment by rg-engineering** [comment]
@Gsiberger2 ist das soweit okay?

**Comment by Gsiberger2** [comment]
Hallo Rene
Super. Ich denke das wird vielen bei der Arbeit mit Blockly helfen.

Entschuldige die lange Zeit bis zu meiner Rückmeldung. Wir waren bei uns seit letzten Mittwoch mit Vorbereitung und dann diese Woche mit der Verteilung von Laptops und Daten für den HomeOffice Betrieb nahezu aller unserer Mitarbeiter die keinen Laptop sondern nur einen PC im Office haben, beschäftigt, da hatte ich um 21:00 Uhr keine Lust mehr deinen Adapter upzudaten und mir anzuschauen.

Vielen Dank für deine Arbeit und den super Adapter
