### ISSUE TITLE
MinimumTemperatur Field is undefined after First run

### ISSUE THREAD

**Issue by Pittini** [rg-engineering/ioBroker.heatingcontrol#84]
The MinimumTemperature field in Rooms.x.MinimumTemperature is initially undefined/null, this causes 
inevitable Skript Warnings at getState. Please set an default value.

![Inked2020-03-10 15_48_46-objects - ioBroker_LI](https://user-images.githubusercontent.com/51408942/76326274-b5305600-62e8-11ea-91ab-8bd6ab7bdfc9.jpg)

Any getState causes this:

`

javascript.0 | 2020-03-10 15:38:36.099 | warn | (1426) at process._tickCallback (internal/process/next_tick.js:68:7)
-- | -- | -- | --
javascript.0 | 2020-03-10 15:38:36.099 | warn | (1426) at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
javascript.0 | 2020-03-10 15:38:36.099 | warn | (1426) at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
javascript.0 | 2020-03-10 15:38:36.098 | warn | (1426) at (anonymous function).(anonymous function) (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:71697)
javascript.0 | 2020-03-10 15:38:36.098 | warn | (1426) at /opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1976:42
javascript.0 | 2020-03-10 15:38:36.098 | warn | (1426) at Object.<anonymous> (script.js.common.HeatingControlVis:158:13)
javascript.0 | 2020-03-10 15:38:36.098 | warn | (1426) at main (script.js.common.HeatingControlVis:172:5)
javascript.0 | 2020-03-10 15:38:36.098 | warn | (1426) at SetVis (script.js.common.HeatingControlVis:306:19)
javascript.0 | 2020-03-10 15:38:36.098 | warn | (1426) getState "heatingcontrol.0.Rooms.Toilette.MinimumTemperature" not found (3) states[id]=null

**Comment by rg-engineering** [comment]
solved with 0.3.19
