### ISSUE TITLE
Time state incorrect created, type date does not exist in ioBroker !

### ISSUE THREAD

**Issue by DutchmanNL** [rg-engineering/ioBroker.heatingcontrol#87]
As example the code used hier to declare the state is incorrect and results in errors for scripting and further modification oof the state : 

https://github.com/rg-engineering/ioBroker.heatingcontrol/blob/master/main.js#L651-L662

type "date" is not an valid ioBroker type and by that impossible assign causing errors.
Please adjust tot he proper definition of ioBroker state definition : 

Like : 
date (common.type = string - parsable by "new Date(ddd)" string
date (common.type = number - epoch seconds * 1000

reference : 

https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md

So please adjust all your time/date state to the proper format or used just "mixed" with the current formats used.

In addition, please also ensure you use the proper role definitions !
"Profile" is not an valid ioBroker role clarification, see reference : 

https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md

**Comment by rg-engineering** [comment]
@DutchmanNL after changing to string I get "invalid date" in object browser. This appears also if my adapter does not run, so I assume some internal checks?

![grafik](https://user-images.githubusercontent.com/8238668/76683826-4a905a80-6607-11ea-906e-23e11768cbe2.png)

![grafik](https://user-images.githubusercontent.com/8238668/76683839-58de7680-6607-11ea-9f81-6ec17cc78591.png)

Can you give me an hint where my mistake could be?

**Comment by rg-engineering** [comment]
can not use role "value.timer"... if I use role "value" everything works fine...

**Comment by rg-engineering** [comment]
solved with 0.3.19
