### ISSUE TITLE
Zeitsteuerung „hängt“ manchmal

### ISSUE THREAD

**Issue by eric2905** [rg-engineering/ioBroker.heatingcontrol#88]
Teste den Adapter nun zum zweiten Mal (nutze sonst das Script). Auch diesmal wieder gleiches Verhalten, was beim ersten Test zum Wechsel zurück auf das Script führte.

Heute früh wurde die zeitgesteuerte Anpassung der Temperatur (ab 03:00 Uhr auf 21 Grad) nicht ausgeführt.
- Ein Profil, 5 Zeiten pro Tag, jeder Tag einzeln
- Keine Einträge im Log, o.ä.
- Adapter grün
- Neustart des Adapters führte zu sofortiger Ausführung gemäß Zeitsteuerung

Was kann ich tun, um den Fehler einzugrenzen?

**Comment by rg-engineering** [comment]
heisst "manchmal" immer Sonntag? Ich hatte noch ein Problem beim Generieren der cron-Tabelle für den Sonntag im Profiltyp "jeden Tag einzeln", das habe ich mit der 0.3.19 behoben (kommt wahrscheinlich heute nachmittag in's latest...) oder jetzt schon hier in github..

**Comment by eric2905** [comment]
Hmmm, immer wieder Sonntags? .... gute Frage ...

Ziehe jetzt die v0.3.19 vom Git.
Melde mich dann

**Comment by rg-engineering** [comment]
Vielleicht dann den Adapter mal auf debug stellen, und dann im log die Zeilen suchen, wo die cron jobs angelegt werden und prüfen, ob das passt (oder hier posten).

**Comment by eric2905** [comment]
Debug mach ich später - ist auf dem iPhone etwas frickelig.

**Comment by eric2905** [comment]
Zwischendurch lief es gut. Jetzt habe ich iobroker neu aufgesetzt (neue VM, usw.) und die Steuerung hängt wieder. Keine Regelung der Heizung, obwohl der Adapter läuft.

Im Syslog find ich zum CRON folgende Einträge:
![3B0C305C-7CD0-467A-AEDE-6799BEE9976E](https://user-images.githubusercontent.com/18639287/78097244-1628e680-73dc-11ea-8862-bc815d15ca77.jpeg)

Adapter auf Debug mache ich später.

Gruß,
Eric

**Comment by eric2905** [comment]
Moin, 

> Zwischendurch lief es gut. Jetzt habe ich iobroker neu aufgesetzt (neue VM, usw.) und die Steuerung hängt wieder. Keine Regelung der Heizung, obwohl der Adapter läuft.
> 
> Im Syslog find ich zum CRON folgende Einträge:
> [Bild manuell entfernt]
> Adapter auf Debug mache ich später.
> 
> Gruß,
> Eric

Fehler gefunden:
Obwohl bei der Ubuntu-Installation deZeitzone richtig eingestellt wurde, war sie später nicht gesetzt .... -2 Stunden .... also alles verspätet.
Zeitzone am Commandprompt richtig gesetzt ... Tada, läuft.

Ich behalte das weiter im Auge.

**Comment by rg-engineering** [comment]
Ich schliesse das Ticket hier. Falls es wieder auftritt, bitte neues Ticket erstellen...
