### ISSUE TITLE
Integration Feiertagskalender

### ISSUE THREAD

**Issue by AlexanderSch90** [rg-engineering/ioBroker.heatingcontrol#9]
Hallo, wie du selbst im Forum beschrieben hast, soll der Feiertagskalender zukünftig integriert werden. Ich bitte aber darum, diesen nicht "hart" zu verdrahten, sondern in deinem Adapter einen beliebigen true/false Wert auswählen zu lassen. Ich habe mir z.B. einen eigenen Datenpunkt angelegt, welche je nach Feiertag / Urlaub / Ferien / Wochenende einen true / false vergibt, sprich die Tage wo auf jedefall jemand zu Hause ist auch einen true ausgibt. NUR der Feiertagskalender ist hier zu wenig... Deshalb bitte ich die Implementierung etwas freier zu gestalten. Jedem ist dann frei überlassen ob er "nur" den Feiertagskalender-Datenpunkt nimmt oder sich selbst was zusammengebaut hat...

Danke!

**Comment by rg-engineering** [comment]
das baue ich jetzt noch um...

**Comment by rg-engineering** [comment]
man kann jetzt entweder den Pfad zum Feiertag-Adapter eintragen. Dann erweitere ich mit ".heute.boolean". Alternativ trägt man irgendeinen Pfad zum Datenpunkt ein. Dann nehme ic das so...
