### ISSUE TITLE
Testing Update to js-controller 3

### ISSUE THREAD

**Issue by eric2905** [rg-engineering/ioBroker.heatingcontrol#92]
Updated the js-controller to v3 (see [here](https://forum.iobroker.net/topic/32036/beta-test-js-controller-3-0-x-auf-github)

Log entry for every object of heatingcontrol

heatingcontrol.0	2020-04-08 20:12:28.887	warn	(5140) Object Profiles.0.Dachgeschoss.Fri.Periods.2.Temperature is invalid: obj.type has to exist
heatingcontrol.0	2020-04-08 20:12:28.886	warn	(5140) This object will not be created in future versions. Please report this to the developer.

**Comment by rg-engineering** [comment]
closed wir 0.4.0
