### ISSUE TITLE
integration Netatmo Thermostat

### ISSUE THREAD

**Issue by Newpicsel** [rg-engineering/ioBroker.heatingcontrol#96]
Hallo, und ertsmal danke für deine Arbeit hier!

Der Adapter klingt jetzt schon sehr interessant und hat viel potenzial wie ich finde.
Leider habe ich mich, bevor ich mich mit ioBroker beschäftigt habe, für Thermostate von Netatmo entschieden, diese gefallen mir auch sehr gut aber sind wie es scheint nicht sehr verbreitet und werden was Adapter angeht so gut wie garnicht unterstützt, bis jetzt ist es mir nicht einmal möglich via ioB die Temperatur zu regeln, lediglich auslesen kann ich diese über den alexa2.0 Adapter.
Über Alexa und HomeKit lassen sich diese extern aber ohne Probleme steuern.

Hier der Link zu den Thermostaten:
[https://www.netatmo.com/de-de/energy/valves]([https://www.netatmo.com/de-de/energy/valves])

Danke und schöne Grüße

**Comment by rg-engineering** [comment]
Danke für das feedback. Leider setzte ich voraus, dass die zu steuernden Geräte bereits in ioBroker durch andere Adapter integriert sind. Ich habe hier kein einziges Gerät zusätzlich integriert. Ich würde dir raten, unter [Adapter Requests](https://github.com/ioBroker/AdapterRequests) einen Request für deine Geräte zu erstellen (evtl. gibt es den Request dort schon, dann bitte dafür voten)

**Comment by rg-engineering** [comment]
Das issue schliesse ich, weil hier keine weitere Aktivität nötig ist..
